// frontend/src/lib/templates/modern/Home.svelte
<script lang="ts">
	import type { PageData } from '../../../routes/$types';
	import HomeHero from '$components/HomeHero.svelte';
	import { currentLanguage } from '$stores/language';
	import { MultiLangUtils } from '$utils/multiLang';
	import { t } from '$stores/i18n';
	import { onMount } from 'svelte';

	export let data: PageData;

	let coverImages: Record<string, string> = {};
	let coverImagesLoading: Record<string, boolean> = {};

	onMount(async () => {
		if (!data.rootAlbums || data.rootAlbums.length === 0) return;

		// Initialize loading state for all albums
		data.rootAlbums.forEach((album) => {
			coverImagesLoading[album._id] = true;
		});

		// Fetch cover images for all albums using batch API
		try {
			const response = await fetch('/api/albums/cover-images', {
				method: 'POST',
				headers: {
					'Content-Type': 'application/json',
				},
				body: JSON.stringify({
					albumIds: data.rootAlbums.map((a) => a._id),
				}),
			});

			if (response.ok) {
				const result = await response.json();
				console.log('Cover images API response:', result);
				
				// Handle both wrapped {success, data} and direct Record<string, string> formats
				if (result.success && result.data) {
					// Wrapped format: {success: true, data: Record<string, string>}
					coverImages = result.data;
				} else if (result && typeof result === 'object' && !result.success) {
					// Direct format: Record<string, string> (albumId -> coverImageUrl)
					coverImages = result;
				} else {
					console.warn('Unexpected response structure:', result);
				}
			} else {
				console.error('Failed to fetch cover images, status:', response.status);
			}
		} catch (err) {
			console.error('Failed to fetch cover images:', err);
		} finally {
			// Mark all albums as no longer loading
			data.rootAlbums.forEach((album) => {
				coverImagesLoading[album._id] = false;
			});
		}
	});
</script>

<!-- Modern template home layout -->
<HomeHero />

<section class="bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900">
	<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
		<div class="flex items-center justify-between mb-10">
			<div>
				<h2 class="text-4xl font-bold text-white mb-2 tracking-tight">{$t('admin.featuredAlbums')}</h2>
				<p class="text-purple-300 text-lg">{$t('albums.rootLevelAlbumsDescription')}</p>
			</div>
			<a href="/albums" class="text-sm font-medium text-white hover:text-purple-300 transition-colors px-4 py-2 bg-purple-600/50 hover:bg-purple-600/70 rounded-lg backdrop-blur-sm">
				{$t('hero.browseAllAlbums')} →
			</a>
		</div>

		{#if data.albumsError}
			<div class="bg-red-900/50 text-red-200 px-4 py-3 rounded-lg text-sm border border-red-700">
				Failed to load albums: {data.albumsError}
			</div>
		{:else if !data.rootAlbums || data.rootAlbums.length === 0}
			<div class="bg-slate-800/50 text-gray-300 px-4 py-3 rounded-lg text-sm border border-slate-700">
				No albums available yet.
			</div>
		{:else}
			<div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
				{#each data.rootAlbums as album, idx}
					{@const coverImageUrl = coverImages[album._id]}
					{@const isLogo = coverImageUrl && (coverImageUrl.includes('/logos/') || coverImageUrl.includes('logo') || (coverImageUrl.includes('/api/storage/serve/') && coverImageUrl.includes('logo')))}
					<a
						href={`/albums/${album.alias ?? album._id}`}
						class="group relative overflow-hidden rounded-2xl cursor-pointer transform transition-all duration-500 hover:scale-105 hover:z-10"
						style="animation-delay: {idx * 0.1}s"
					>
						<div class="aspect-square bg-gradient-to-br from-purple-600 to-blue-600 relative overflow-hidden rounded-2xl">
							{#if coverImagesLoading[album._id]}
								<div class="absolute inset-0 flex items-center justify-center bg-slate-800/50">
									<div class="w-8 h-8 border-2 border-purple-400 border-t-transparent rounded-full animate-spin"></div>
								</div>
							{:else if coverImageUrl}
								<img
									src={coverImageUrl}
									alt={MultiLangUtils.getTextValue(album.name, $currentLanguage) || 'Album cover'}
									class="w-full h-full transition-all duration-500 {isLogo
										? 'object-contain p-4 bg-white'
										: 'object-cover group-hover:scale-110'}"
								/>
							{:else}
								<div class="absolute inset-0 flex items-center justify-center bg-gradient-to-br from-purple-600 to-blue-600">
									<svg class="w-16 h-16 text-white/30" fill="none" stroke="currentColor" viewBox="0 0 24 24">
										<path
											stroke-linecap="round"
											stroke-linejoin="round"
											stroke-width="1.5"
											d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z"
										/>
									</svg>
								</div>
							{/if}
							<div class="absolute inset-0 bg-black/20 group-hover:bg-black/40 transition-all duration-300"></div>
							<div class="absolute bottom-0 left-0 right-0 p-6 bg-gradient-to-t from-black/80 to-transparent translate-y-full group-hover:translate-y-0 transition-transform duration-300">
								<h3 class="text-white font-semibold text-lg mb-1">
									{#if album.name}
										{MultiLangUtils.getTextValue(album.name, $currentLanguage)}
									{:else}
										Untitled album
									{/if}
								</h3>
								{#if album.description}
									{@const desc = MultiLangUtils.getHTMLValue(album.description, $currentLanguage)}
									{#if desc}
										<p class="text-white/70 text-sm line-clamp-1">{@html desc.replace(/<[^>]*>/g, '')}</p>
									{/if}
								{/if}
							</div>
						</div>
					</a>
				{/each}
			</div>
		{/if}
	</div>
</section>

// src/templates/modern/pages/Home.tsx
'use client'

import { useState, useEffect } from 'react'
import Header from '../components/Header'
import Hero from '../components/Hero'
import AlbumList from '../components/AlbumList'
import Footer from '../components/Footer'
import { useI18n } from '@/hooks/useI18n'
import { useTemplateConfig } from '@/hooks/useTemplateConfig'
import { MultiLangUtils } from '@/types/multi-lang'
import { useLanguage } from '@/contexts/LanguageContext'

interface Album {
  _id: string
  name: string
  alias: string
  description: string
  photoCount: number
  childAlbumCount?: number
  coverImage?: string
  isPublic: boolean
  isFeatured: boolean
  createdAt: string
}

export default function HomePage() {
  const { t } = useI18n()
  const { isComponentVisible } = useTemplateConfig()
  const { currentLanguage } = useLanguage()
  const [rootAlbums, setRootAlbums] = useState<Album[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    const fetchRootAlbums = async () => {
      try {
        setLoading(true)
        // Fetch only root albums (no parent)
        const response = await fetch('/api/albums?parentId=root&isPublic=true')
        
        if (!response.ok) {
          throw new Error('Failed to fetch albums')
        }
        
        const result = await response.json()
        if (result.success) {
          const albums = result.data
          
          // Filter to only public albums
          const publicAlbums = albums.filter((album: Album) => album.isPublic)
          setRootAlbums(publicAlbums)
        } else {
          setError(result.error || 'Failed to fetch albums')
        }
      } catch (error) {
        console.error('Failed to fetch albums:', error)
        setError('Failed to fetch albums')
      } finally {
        setLoading(false)
      }
    }

    fetchRootAlbums()
  }, [])

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 via-white to-purple-50">
      {/* Header */}
      <Header />

      {/* Hero Section */}
      {isComponentVisible('hero') && <Hero />}
      
      {/* Featured Albums Section */}
      {rootAlbums.length > 0 && (
        <section className="py-20 bg-white/50 backdrop-blur-sm">
          <div className="max-w-7xl mx-auto px-6">
            <div className="text-center mb-16">
              <h2 className="text-4xl md:text-5xl font-bold bg-gradient-to-r from-gray-900 via-purple-900 to-gray-900 bg-clip-text text-transparent mb-6">
                {t('albums.galleryTitle')}
              </h2>
              <p className="text-xl text-gray-600 max-w-3xl mx-auto leading-relaxed">
                {t('albums.gallerySubtitle')}
              </p>
            </div>

            {/* Featured albums grid */}
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-8 mb-16">
              {rootAlbums.slice(0, 8).map((album) => (
                <div key={album._id} className="group">
                  <div className="relative overflow-hidden rounded-2xl bg-gradient-to-br from-white/80 to-white/40 backdrop-blur-xl border border-white/30 shadow-xl hover:shadow-2xl transition-all duration-500 transform hover:scale-105 hover:-translate-y-2">
                    {/* Image container */}
                    <div className="relative aspect-[4/3] overflow-hidden">
                      <img
                        src={album.coverImage || '/api/placeholder/400/300'}
                        alt={MultiLangUtils.getTextValue(album.name, currentLanguage)}
                        className="w-full h-full object-cover transition-transform duration-700 group-hover:scale-110"
                      />
                      
                      {/* Gradient overlay */}
                      <div className="absolute inset-0 bg-gradient-to-t from-black/60 via-transparent to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500"></div>
                      
                      {/* Featured badge */}
                      {album.isFeatured && (
                        <div className="absolute top-4 right-4">
                          <div className="px-3 py-1 bg-gradient-to-r from-yellow-400 to-orange-500 text-white text-xs font-bold rounded-full shadow-lg">
                            ⭐ Featured
                          </div>
                        </div>
                      )}

                      {/* Photo count badge */}
                      <div className="absolute bottom-4 left-4">
                        <div className="px-3 py-1 bg-black/50 backdrop-blur-sm text-white text-sm font-medium rounded-full">
                          📸 {album.photoCount} {album.photoCount === 1 ? 'photo' : 'photos'}
                        </div>
                      </div>

                      {/* Hover overlay */}
                      <div className="absolute inset-0 bg-black/40 backdrop-blur-sm opacity-0 group-hover:opacity-100 transition-all duration-500 flex items-center justify-center">
                        <div className="transform translate-y-4 group-hover:translate-y-0 transition-transform duration-500">
                          <div className="px-6 py-3 bg-white/20 backdrop-blur-xl border border-white/30 text-white font-semibold rounded-full hover:bg-white/30 transition-colors duration-300">
                            View Album →
                          </div>
                        </div>
                      </div>
                    </div>

                    {/* Content section */}
                    <div className="p-6">
                      <h3 className="text-xl font-bold text-gray-900 mb-2 group-hover:text-purple-600 transition-colors duration-300 line-clamp-2">
                        {MultiLangUtils.getTextValue(album.name, currentLanguage)}
                      </h3>
                      {album.description && (
                        <div 
                          className="text-gray-600 text-sm mb-4 line-clamp-2 group-hover:text-gray-700 transition-colors duration-300"
                          dangerouslySetInnerHTML={{ 
                            __html: MultiLangUtils.getHTMLValue(album.description, currentLanguage) 
                          }}
                        />
                      )}
                      <div className="flex items-center justify-between text-sm text-gray-500">
                        <div className="flex items-center space-x-4">
                          {typeof album.childAlbumCount === 'number' && album.childAlbumCount > 0 && (
                            <div className="flex items-center space-x-1">
                              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 7v10a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2H5a2 2 0 00-2-2z" />
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 5a2 2 0 012-2h4a2 2 0 012 2v2H8V5z" />
                              </svg>
                              <span>{album.childAlbumCount} sub-albums</span>
                            </div>
                          )}
                        </div>
                        <div className="text-xs text-gray-400">
                          {new Date(album.createdAt).toLocaleDateString('en-US', {
                            year: 'numeric',
                            month: 'short'
                          })}
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              ))}
            </div>

            {/* View all albums button */}
            {rootAlbums.length > 8 && (
              <div className="text-center">
                <a
                  href="/albums"
                  className="inline-flex items-center px-8 py-4 bg-gradient-to-r from-purple-600 to-blue-600 text-white font-semibold rounded-full shadow-lg hover:shadow-2xl transform hover:scale-105 transition-all duration-300"
                >
                  View All Albums
                  <svg className="w-5 h-5 ml-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
                  </svg>
                </a>
              </div>
            )}
          </div>
        </section>
      )}

      {/* Stats Section */}
      <section className="py-20 bg-gradient-to-r from-purple-600 to-blue-600 text-white">
        <div className="max-w-7xl mx-auto px-6">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 text-center">
            <div className="group">
              <div className="text-4xl md:text-5xl font-bold mb-4 group-hover:scale-110 transition-transform duration-300">
                {rootAlbums.length}
              </div>
              <div className="text-xl text-purple-100">
                Albums Created
              </div>
            </div>
            <div className="group">
              <div className="text-4xl md:text-5xl font-bold mb-4 group-hover:scale-110 transition-transform duration-300">
                {rootAlbums.reduce((total, album) => total + album.photoCount, 0)}
              </div>
              <div className="text-xl text-purple-100">
                Photos Shared
              </div>
            </div>
            <div className="group">
              <div className="text-4xl md:text-5xl font-bold mb-4 group-hover:scale-110 transition-transform duration-300">
                24/7
              </div>
              <div className="text-xl text-purple-100">
                Always Available
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20 bg-white">
        <div className="max-w-4xl mx-auto px-6 text-center">
          <h2 className="text-4xl md:text-5xl font-bold bg-gradient-to-r from-gray-900 via-purple-900 to-gray-900 bg-clip-text text-transparent mb-6">
            Ready to Share Your Story?
          </h2>
          <p className="text-xl text-gray-600 mb-8 leading-relaxed">
            Create beautiful galleries, organize your memories, and share them with the world.
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center">
            <a
              href="/albums"
              className="px-8 py-4 bg-gradient-to-r from-purple-600 to-blue-600 text-white font-semibold rounded-full shadow-lg hover:shadow-2xl transform hover:scale-105 transition-all duration-300"
            >
              Explore Gallery
            </a>
            <a
              href="/login"
              className="px-8 py-4 border-2 border-purple-600 text-purple-600 font-semibold rounded-full hover:bg-purple-600 hover:text-white transition-all duration-300"
            >
              Get Started
            </a>
          </div>
        </div>
      </section>

      {/* Footer */}
      {isComponentVisible('footerMenu') && <Footer />}
    </div>
  )
}
