// frontend/src/routes/admin/people/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { goto } from '$app/navigation';
	import { currentLanguage } from '$stores/language';
	import { MultiLangUtils } from '$utils/multiLang';
	import MultiLangInput from '$lib/components/MultiLangInput.svelte';
	import type { MultiLangText } from '$lib/types/multi-lang';

	export let data; // From +layout.server.ts, contains user info

	interface Person {
		_id: string;
		firstName: MultiLangText;
		lastName: MultiLangText;
		fullName: MultiLangText;
		nickname?: MultiLangText;
		birthDate?: string;
		description?: MultiLangText;
		tags?: string[] | Array<{ _id: string; name: string }>;
		isActive?: boolean;
		profileImage?: {
			url: string;
			storageProvider: string;
			fileId: string;
		};
		faceRecognition?: {
			descriptor?: number[];
			extractedAt?: string;
			modelVersion?: string;
		};
	}

	let people: Person[] = [];
	let loading = true;
	let saving = false;
	let deleting = false;
	let message = '';
	let error = '';
	let searchTerm = '';
	let showCreateDialog = false;
	let showEditDialog = false;
	let showDeleteDialog = false;
	let editingPerson: Person | null = null;
	let personToDelete: Person | null = null;

	// Form state
	let formData = {
		firstName: {} as MultiLangText,
		lastName: {} as MultiLangText,
		nickname: {} as MultiLangText,
		birthDate: '',
		description: {} as MultiLangText,
		tags: '',
		isActive: true
	};

	$: defaultLang = $currentLanguage;

	onMount(async () => {
		await loadPeople();
	});

	async function loadPeople() {
		loading = true;
		error = '';
		try {
			const params = new URLSearchParams();
			if (searchTerm) params.append('search', searchTerm);

			const response = await fetch(`/api/admin/people?${params.toString()}`);
			if (!response.ok) {
				throw new Error('Failed to load people');
			}
			const result = await response.json();
			// Handle both { data: [...], pagination: {...} } and direct array formats
			people = Array.isArray(result.data) ? result.data : (Array.isArray(result) ? result : []);
		} catch (err) {
			console.error('Error loading people:', err);
			error = `Failed to load people: ${err instanceof Error ? err.message : 'Unknown error'}`;
		} finally {
			loading = false;
		}
	}

	function resetForm() {
		formData = {
			firstName: {},
			lastName: {},
			nickname: {},
			birthDate: '',
			description: {},
			tags: '',
			isActive: true
		};
	}

	function openCreateDialog() {
		resetForm();
		showCreateDialog = true;
		error = '';
	}

	function openEditDialog(person: Person) {
		editingPerson = person;
		formData = {
			firstName: person.firstName || {},
			lastName: person.lastName || {},
			nickname: person.nickname || {},
			birthDate: person.birthDate
				? new Date(person.birthDate).toISOString().split('T')[0]
				: '',
			description: person.description || {},
			tags: Array.isArray(person.tags)
				? person.tags.map((tag) => (typeof tag === 'string' ? tag : tag.name)).join(', ')
				: '',
			isActive: person.isActive !== undefined ? person.isActive : true
		};
		showEditDialog = true;
		error = '';
	}

	function openDeleteDialog(person: Person) {
		personToDelete = person;
		showDeleteDialog = true;
	}

	async function handleCreate() {
		saving = true;
		error = '';
		message = '';

		try {
			const tagsArray = formData.tags
				.split(',')
				.map((tag) => tag.trim())
				.filter(Boolean);

			const response = await fetch('/api/admin/people', {
				method: 'POST',
				headers: {
					'Content-Type': 'application/json'
				},
				body: JSON.stringify({
					firstName: MultiLangUtils.clean(formData.firstName),
					lastName: MultiLangUtils.clean(formData.lastName),
					nickname: MultiLangUtils.clean(formData.nickname),
					birthDate: formData.birthDate || undefined,
					description: MultiLangUtils.clean(formData.description),
					tags: tagsArray,
					isActive: formData.isActive
				})
			});

			if (!response.ok) {
				const errorData = await response.json().catch(() => ({}));
				throw new Error(errorData.message || 'Failed to create person');
			}

			const newPerson = await response.json();
			people = [...people, newPerson];
			message = 'Person created successfully!';
			showCreateDialog = false;
			resetForm();

			setTimeout(() => {
				message = '';
			}, 3000);
		} catch (err) {
			console.error('Error creating person:', err);
			error = `Failed to create person: ${err instanceof Error ? err.message : 'Unknown error'}`;
		} finally {
			saving = false;
		}
	}

	async function handleEdit() {
		if (!editingPerson) return;

		saving = true;
		error = '';
		message = '';

		try {
			const tagsArray = formData.tags
				.split(',')
				.map((tag) => tag.trim())
				.filter(Boolean);

			const response = await fetch(`/api/admin/people/${editingPerson._id}`, {
				method: 'PUT',
				headers: {
					'Content-Type': 'application/json'
				},
				body: JSON.stringify({
					firstName: MultiLangUtils.clean(formData.firstName),
					lastName: MultiLangUtils.clean(formData.lastName),
					nickname: MultiLangUtils.clean(formData.nickname),
					birthDate: formData.birthDate || undefined,
					description: MultiLangUtils.clean(formData.description),
					tags: tagsArray,
					isActive: formData.isActive
				})
			});

			if (!response.ok) {
				const errorData = await response.json().catch(() => ({}));
				throw new Error(errorData.message || 'Failed to update person');
			}

			const updatedPerson = await response.json();
			people = people.map((p) => (p._id === editingPerson._id ? updatedPerson : p));
			message = 'Person updated successfully!';
			showEditDialog = false;
			editingPerson = null;
			resetForm();

			setTimeout(() => {
				message = '';
			}, 3000);
		} catch (err) {
			console.error('Error updating person:', err);
			error = `Failed to update person: ${err instanceof Error ? err.message : 'Unknown error'}`;
		} finally {
			saving = false;
		}
	}

	async function handleDelete() {
		if (!personToDelete) return;

		deleting = true;
		error = '';
		message = '';

		try {
			const response = await fetch(`/api/admin/people/${personToDelete._id}`, {
				method: 'DELETE'
			});

			if (!response.ok) {
				const errorData = await response.json().catch(() => ({}));
				throw new Error(errorData.message || 'Failed to delete person');
			}

			people = people.filter((p) => p._id !== personToDelete._id);
			message = 'Person deleted successfully!';
			showDeleteDialog = false;
			personToDelete = null;

			setTimeout(() => {
				message = '';
			}, 3000);
		} catch (err) {
			console.error('Error deleting person:', err);
			error = `Failed to delete person: ${err instanceof Error ? err.message : 'Unknown error'}`;
		} finally {
			deleting = false;
		}
	}

	function getPersonDisplayName(person: Person): string {
		return MultiLangUtils.getTextValue(person.fullName, $currentLanguage) ||
			MultiLangUtils.getTextValue(person.firstName, $currentLanguage) + ' ' +
			MultiLangUtils.getTextValue(person.lastName, $currentLanguage) ||
			'Unknown Person';
	}

	function formatDate(dateString: string): string {
		if (!dateString) return '';
		try {
			const date = new Date(dateString);
			return date.toLocaleDateString('en-US', { year: 'numeric', month: 'short', day: 'numeric' });
		} catch {
			return dateString;
		}
	}
</script>

<svelte:head>
	<title>People Management - Admin</title>
</svelte:head>

<div class="min-h-screen bg-gray-50 py-8">
	<div class="max-w-6xl mx-auto px-4">
		<div class="bg-white rounded-lg shadow-md p-6">
			<div class="flex items-center justify-between mb-6">
				<div>
					<h1 class="text-2xl font-bold text-gray-900">People Management</h1>
					<p class="text-gray-600 mt-2">Manage people who appear in your photos</p>
				</div>
				<a
					href="/admin"
					class="text-blue-600 hover:text-blue-800 text-sm font-medium"
				>
					← Back to Admin
				</a>
			</div>

			{#if message}
				<div class="mb-4 p-4 rounded-md bg-green-50 text-green-700">{message}</div>
			{/if}

			{#if error}
				<div class="mb-4 p-4 rounded-md bg-red-50 text-red-700">{error}</div>
			{/if}

			<!-- Search and Actions -->
			<div class="flex items-center justify-between mb-6">
				<div class="flex items-center space-x-4">
					<div class="relative">
						<input
							type="text"
							placeholder="Search people..."
							bind:value={searchTerm}
							on:input={() => loadPeople()}
							class="pl-10 pr-4 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-2 focus:ring-blue-500 focus:border-blue-500 w-64"
						/>
						<svg
							class="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 h-4 w-4"
							fill="none"
							stroke="currentColor"
							viewBox="0 0 24 24"
						>
							<path
								stroke-linecap="round"
								stroke-linejoin="round"
								stroke-width="2"
								d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"
							/>
						</svg>
					</div>
				</div>

				<button
					type="button"
					on:click={openCreateDialog}
					class="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 text-sm font-medium flex items-center gap-2"
				>
					<svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
						<path
							stroke-linecap="round"
							stroke-linejoin="round"
							stroke-width="2"
							d="M12 4v16m8-8H4"
						/>
					</svg>
					Add Person
				</button>
			</div>

			<!-- People List -->
			{#if loading}
				<div class="text-center py-8">
					<div class="inline-block animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
					<p class="mt-2 text-gray-600">Loading people...</p>
				</div>
			{:else if people.length === 0}
				<div class="text-center py-8">
					<svg
						class="h-12 w-12 text-gray-400 mx-auto mb-4"
						fill="none"
						stroke="currentColor"
						viewBox="0 0 24 24"
					>
						<path
							stroke-linecap="round"
							stroke-linejoin="round"
							stroke-width="2"
							d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"
						/>
					</svg>
					<h3 class="text-lg font-semibold text-gray-900 mb-2">No people found</h3>
					<p class="text-gray-600">Start by adding your first person.</p>
				</div>
			{:else}
				<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
					{#each people as person}
						<div class="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
							<div class="flex items-start justify-between mb-4">
								<div class="flex items-center space-x-3">
									{#if person.profileImage?.url}
										<img
											src={person.profileImage.url}
											alt={getPersonDisplayName(person)}
											class="w-10 h-10 rounded-full object-cover"
										/>
									{:else}
										<div class="w-10 h-10 bg-blue-100 rounded-full flex items-center justify-center">
											<svg
												class="h-5 w-5 text-blue-600"
												fill="none"
												stroke="currentColor"
												viewBox="0 0 24 24"
											>
												<path
													stroke-linecap="round"
													stroke-linejoin="round"
													stroke-width="2"
													d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"
												/>
											</svg>
										</div>
									{/if}
									<div>
										<h3 class="font-semibold text-gray-900">
											{getPersonDisplayName(person)}
										</h3>
										{#if person.nickname && MultiLangUtils.getTextValue(person.nickname, $currentLanguage)}
											<p class="text-sm text-gray-600">
												"{MultiLangUtils.getTextValue(person.nickname, $currentLanguage)}"
											</p>
										{/if}
									</div>
								</div>

								<div class="flex space-x-1">
									<button
										type="button"
										on:click={() => openEditDialog(person)}
										class="p-2 text-gray-600 hover:text-blue-600 hover:bg-blue-50 rounded"
									>
										<svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
											<path
												stroke-linecap="round"
												stroke-linejoin="round"
												stroke-width="2"
												d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"
											/>
										</svg>
									</button>
									<button
										type="button"
										on:click={() => openDeleteDialog(person)}
										class="p-2 text-gray-600 hover:text-red-600 hover:bg-red-50 rounded"
									>
										<svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
											<path
												stroke-linecap="round"
												stroke-linejoin="round"
												stroke-width="2"
												d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"
											/>
										</svg>
									</button>
								</div>
							</div>

							{#if person.description && MultiLangUtils.getTextValue(person.description, $currentLanguage)}
								<p class="text-sm text-gray-600 mb-3">
									{MultiLangUtils.getTextValue(person.description, $currentLanguage)}
								</p>
							{/if}

							{#if person.birthDate}
								<p class="text-sm text-gray-500 mb-3">Born: {formatDate(person.birthDate)}</p>
							{/if}

							{#if person.tags && person.tags.length > 0}
								<div class="flex flex-wrap gap-1">
									{#each person.tags as tag}
										<span
											class="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-gray-100 text-gray-800"
										>
											{typeof tag === 'string' ? tag : tag.name}
										</span>
									{/each}
								</div>
							{/if}

							{#if person.faceRecognition?.descriptor}
								<div class="mt-3 pt-3 border-t border-gray-200">
									<span
										class="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-green-100 text-green-800"
									>
										Face Recognition Enabled
									</span>
								</div>
							{/if}
						</div>
					{/each}
				</div>
			{/if}
		</div>
	</div>
</div>

<!-- Create Dialog -->
{#if showCreateDialog}
	<div class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
		<div class="bg-white rounded-lg shadow-xl w-full max-w-md p-6">
			<h2 class="text-xl font-bold text-gray-900 mb-4">Add New Person</h2>

			{#if error}
				<div class="mb-4 p-4 bg-red-50 text-red-700 rounded-md">{error}</div>
			{/if}

			<div class="space-y-4">
				<div class="grid grid-cols-2 gap-4">
					<div>
						<label class="block text-sm font-medium text-gray-700 mb-2">
							First Name *
						</label>
						<MultiLangInput
							value={formData.firstName}
							onChange={(value) => (formData.firstName = value)}
							placeholder="John"
							required={true}
							defaultLanguage={defaultLang}
						/>
					</div>
					<div>
						<label class="block text-sm font-medium text-gray-700 mb-2">
							Last Name *
						</label>
						<MultiLangInput
							value={formData.lastName}
							onChange={(value) => (formData.lastName = value)}
							placeholder="Doe"
							required={true}
							defaultLanguage={defaultLang}
						/>
					</div>
				</div>

				<div>
					<label class="block text-sm font-medium text-gray-700 mb-2">
						Nickname
					</label>
					<MultiLangInput
						value={formData.nickname}
						onChange={(value) => (formData.nickname = value)}
						placeholder="Johnny"
						defaultLanguage={defaultLang}
					/>
				</div>

				<div>
					<label class="block text-sm font-medium text-gray-700 mb-2">
						Birth Date
					</label>
					<input
						type="date"
						bind:value={formData.birthDate}
						class="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
					/>
				</div>

				<div>
					<label class="block text-sm font-medium text-gray-700 mb-2">
						Description
					</label>
					<MultiLangInput
						value={formData.description}
						onChange={(value) => (formData.description = value)}
						placeholder="Brief description..."
						multiline={true}
						rows={3}
						defaultLanguage={defaultLang}
					/>
				</div>

				<div>
					<label class="block text-sm font-medium text-gray-700 mb-2">
						Tags (comma-separated)
					</label>
					<input
						type="text"
						bind:value={formData.tags}
						placeholder="family, friend, colleague"
						class="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
					/>
				</div>

				<div class="flex justify-end space-x-2 pt-4">
					<button
						type="button"
						on:click={() => {
							showCreateDialog = false;
							resetForm();
						}}
						class="px-4 py-2 bg-gray-200 text-gray-700 rounded-md hover:bg-gray-300 text-sm font-medium"
					>
						Cancel
					</button>
					<button
						type="button"
						on:click={handleCreate}
						disabled={saving}
						class="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 disabled:opacity-50 text-sm font-medium"
					>
						{#if saving}
							Creating...
						{:else}
							Create Person
						{/if}
					</button>
				</div>
			</div>
		</div>
	</div>
{/if}

<!-- Edit Dialog -->
{#if showEditDialog && editingPerson}
	<div class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
		<div class="bg-white rounded-lg shadow-xl w-full max-w-md p-6">
			<h2 class="text-xl font-bold text-gray-900 mb-4">Edit Person</h2>

			{#if error}
				<div class="mb-4 p-4 bg-red-50 text-red-700 rounded-md">{error}</div>
			{/if}

			<div class="space-y-4">
				<div class="grid grid-cols-2 gap-4">
					<div>
						<label class="block text-sm font-medium text-gray-700 mb-2">
							First Name *
						</label>
						<MultiLangInput
							value={formData.firstName}
							onChange={(value) => (formData.firstName = value)}
							placeholder="John"
							required={true}
							defaultLanguage={defaultLang}
						/>
					</div>
					<div>
						<label class="block text-sm font-medium text-gray-700 mb-2">
							Last Name *
						</label>
						<MultiLangInput
							value={formData.lastName}
							onChange={(value) => (formData.lastName = value)}
							placeholder="Doe"
							required={true}
							defaultLanguage={defaultLang}
						/>
					</div>
				</div>

				<div>
					<label class="block text-sm font-medium text-gray-700 mb-2">
						Nickname
					</label>
					<MultiLangInput
						value={formData.nickname}
						onChange={(value) => (formData.nickname = value)}
						placeholder="Johnny"
						defaultLanguage={defaultLang}
					/>
				</div>

				<div>
					<label class="block text-sm font-medium text-gray-700 mb-2">
						Birth Date
					</label>
					<input
						type="date"
						bind:value={formData.birthDate}
						class="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
					/>
				</div>

				<div>
					<label class="block text-sm font-medium text-gray-700 mb-2">
						Description
					</label>
					<MultiLangInput
						value={formData.description}
						onChange={(value) => (formData.description = value)}
						placeholder="Brief description..."
						multiline={true}
						rows={3}
						defaultLanguage={defaultLang}
					/>
				</div>

				<div>
					<label class="block text-sm font-medium text-gray-700 mb-2">
						Tags (comma-separated)
					</label>
					<input
						type="text"
						bind:value={formData.tags}
						placeholder="family, friend, colleague"
						class="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
					/>
				</div>

				<div class="flex justify-end space-x-2 pt-4">
					<button
						type="button"
						on:click={() => {
							showEditDialog = false;
							editingPerson = null;
							resetForm();
						}}
						class="px-4 py-2 bg-gray-200 text-gray-700 rounded-md hover:bg-gray-300 text-sm font-medium"
					>
						Cancel
					</button>
					<button
						type="button"
						on:click={handleEdit}
						disabled={saving}
						class="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 disabled:opacity-50 text-sm font-medium"
					>
						{#if saving}
							Updating...
						{:else}
							Update Person
						{/if}
					</button>
				</div>
			</div>
		</div>
	</div>
{/if}

<!-- Delete Dialog -->
{#if showDeleteDialog && personToDelete}
	<div class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
		<div class="bg-white rounded-lg shadow-xl w-full max-w-md p-6">
			<h2 class="text-xl font-bold text-gray-900 mb-4">Delete Person</h2>

			{#if error}
				<div class="mb-4 p-4 bg-red-50 text-red-700 rounded-md">{error}</div>
			{/if}

			<div class="space-y-4">
				<p class="text-gray-600">
					Are you sure you want to delete <strong>{getPersonDisplayName(personToDelete)}</strong>?
					This action cannot be undone.
				</p>
				<div class="flex justify-end space-x-2">
					<button
						type="button"
						on:click={() => {
							showDeleteDialog = false;
							personToDelete = null;
						}}
						class="px-4 py-2 bg-gray-200 text-gray-700 rounded-md hover:bg-gray-300 text-sm font-medium"
					>
						Cancel
					</button>
					<button
						type="button"
						on:click={handleDelete}
						disabled={deleting}
						class="px-4 py-2 bg-red-600 text-white rounded-md hover:bg-red-700 disabled:opacity-50 text-sm font-medium"
					>
						{#if deleting}
							Deleting...
						{:else}
							Delete Person
						{/if}
					</button>
				</div>
			</div>
		</div>
	</div>
{/if}

// src/app/admin/people/page.tsx
'use client'

import { useState, useEffect } from 'react'
import { useSession } from 'next-auth/react'
import { useRouter } from 'next/navigation'
import { useI18n } from '@/hooks/useI18n'
import { useLanguage } from '@/contexts/LanguageContext'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog'
import { Plus, Search, Edit, Trash2, User, AlertCircle } from 'lucide-react'
import { format } from 'date-fns'
import { MultiLangText, MultiLangUtils } from '@/types/multi-lang'
import { MultiLangInput } from '@/components/MultiLangInput'
import AdminTemplate from '@/components/admin/AdminTemplate'
import { Person } from '@/types/index'

// Using IPerson from @/lib/models/Person.ts instead of local interface


export default function PeopleManagementPage() {
  const { t } = useI18n()
  const { currentLanguage } = useLanguage()
  const { data: session, status } = useSession()
  const router = useRouter()
  const [people, setPeople] = useState<Person[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [mounted, setMounted] = useState(false)
  const [searchTerm, setSearchTerm] = useState('')
  const [isCreateDialogOpen, setIsCreateDialogOpen] = useState(false)
  const [isEditDialogOpen, setIsEditDialogOpen] = useState(false)
  const [editingPerson, setEditingPerson] = useState<Person | null>(null)
  const [isDeleteDialogOpen, setIsDeleteDialogOpen] = useState(false)
  const [personToDelete, setPersonToDelete] = useState<Person | null>(null)
  
  // Form state
  const [formData, setFormData] = useState({
    firstName: { en: '', he: '' } as MultiLangText,
    lastName: { en: '', he: '' } as MultiLangText,
    nickname: { en: '', he: '' } as MultiLangText,
    birthDate: '',
    description: { en: '', he: '' } as MultiLangText,
    tags: '',
    isActive: true
  })
  
  // Set mounted to true after component mounts
  useEffect(() => {
    setMounted(true)
  }, [])

  // Redirect if not authenticated
  useEffect(() => {
    if (!mounted) return // Wait for component to mount
    if (status === 'loading') return // Still loading
    if (!session) {
      router.push('/login?callbackUrl=/admin/people')
      return
    }
    fetchPeople()
  }, [mounted, session, status, router, searchTerm])
  
  const fetchPeople = async () => {
    try {
      setLoading(true)
      const params = new URLSearchParams()
      if (searchTerm) params.append('search', searchTerm)
      
      const response = await fetch(`/api/people?${params.toString()}`)
      
      if (!response.ok) {
        if (response.status === 401) {
          throw new Error('Please log in to access this page')
        }
        throw new Error('Failed to fetch people')
      }
      
      const data = await response.json()
      if (data.success) {
        setPeople(data.data)
      } else {
        throw new Error(data.error || 'Failed to fetch people')
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'An error occurred')
    } finally {
      setLoading(false)
    }
  }
  
  const handleCreate = async () => {
    try {
      const tagsArray = formData.tags.split(',').map(tag => tag.trim()).filter(Boolean)
      
      const response = await fetch('/api/people', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          ...formData,
          tags: tagsArray
        }),
      })
      
      if (!response.ok) {
        const errorData = await response.json()
        throw new Error(errorData.error || 'Failed to create person')
      }
      
      const data = await response.json()
      if (data.success) {
        setPeople([...people, data.data])
        resetForm()
        setIsCreateDialogOpen(false)
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to create person')
    }
  }
  
  const handleEdit = async () => {
    if (!editingPerson) return
    
    try {
      const tagsArray = formData.tags.split(',').map(tag => tag.trim()).filter(Boolean)
      
      const response = await fetch(`/api/people/${editingPerson._id}`, {
        method: 'PUT',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          ...formData,
          tags: tagsArray
        }),
      })
      
      if (!response.ok) {
        const errorData = await response.json()
        throw new Error(errorData.error || 'Failed to update person')
      }
      
      const data = await response.json()
      if (data.success) {
        setPeople(people.map(p => p._id === editingPerson._id ? data.data : p))
        resetForm()
        setIsEditDialogOpen(false)
        setEditingPerson(null)
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to update person')
    }
  }
  
  const handleDelete = async () => {
    if (!personToDelete) return
    
    try {
      const response = await fetch(`/api/people/${personToDelete._id}`, {
        method: 'DELETE',
      })
      
      if (!response.ok) {
        const errorData = await response.json()
        throw new Error(errorData.error || 'Failed to delete person')
      }
      
      const data = await response.json()
      if (data.success) {
        setPeople(people.filter(p => p._id !== personToDelete._id))
        setIsDeleteDialogOpen(false)
        setPersonToDelete(null)
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to delete person')
    }
  }
  
  const resetForm = () => {
    setFormData({
      firstName: { en: '', he: '' } as MultiLangText,
      lastName: { en: '', he: '' } as MultiLangText,
      nickname: { en: '', he: '' } as MultiLangText,
      birthDate: '',
      description: { en: '', he: '' } as MultiLangText,
      tags: '',
      isActive: true
    })
  }
  
  const openEditDialog = (person: Person) => {
    setEditingPerson(person)
    setFormData({
      firstName: person.firstName || { en: '', he: '' } as MultiLangText,
      lastName: person.lastName || { en: '', he: '' } as MultiLangText,
      nickname: person.nickname || { en: '', he: '' } as MultiLangText,
      birthDate: person.birthDate ? format(new Date(person.birthDate), 'yyyy-MM-dd') : '',
      description: person.description || { en: '', he: '' } as MultiLangText,
      tags: person.tags.map(tag => typeof tag === 'string' ? tag : tag.name).join(', '),
      isActive: person.isActive
    })
    setIsEditDialogOpen(true)
  }
  
  const openDeleteDialog = (person: Person) => {
    setPersonToDelete(person)
    setIsDeleteDialogOpen(true)
  }
  
  // Always show loading state until component is mounted and authenticated
  if (!mounted || status === 'loading' || loading) {
    return (
      <AdminTemplate 
        title={t('admin.peopleManagement')}
        description={t('admin.managePeopleStructuredData')}
      >
        <div className="p-6">
          <div className="animate-pulse">
            <div className="h-64 bg-gray-200 rounded"></div>
          </div>
        </div>
      </AdminTemplate>
    )
  }

  return (
    <AdminTemplate 
      title={t('admin.peopleManagement')}
      description={t('admin.managePeopleStructuredData')}
    >
      <div className="p-6">
        {/* Search and Actions */}
      <div className="flex items-center justify-between mb-6">
        <div className="flex items-center space-x-4">
          <div className="relative">
            <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 h-4 w-4" />
            <Input
              placeholder="Search people..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="pl-10 w-64"
            />
          </div>
        </div>
        
        <Dialog open={isCreateDialogOpen} onOpenChange={setIsCreateDialogOpen}>
          <DialogTrigger asChild>
            <Button onClick={() => resetForm()}>
              <Plus className="h-4 w-4 mr-2" />
              Add Person
            </Button>
          </DialogTrigger>
          <DialogContent className="max-w-md">
            <DialogHeader>
              <DialogTitle>Add New Person</DialogTitle>
            </DialogHeader>
            
            {/* Error Message */}
            {error && (
              <div className="mb-4 p-4 bg-red-50 border border-red-200 rounded-md relative z-10">
                <p className="text-red-600">{error}</p>
              </div>
            )}
            
            <div className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <Label htmlFor="firstName">First Name *</Label>
                  <MultiLangInput
                    value={formData.firstName}
                    onChange={(value) => setFormData({...formData, firstName: value})}
                    placeholder="John"
                  />
                </div>
                <div>
                  <Label htmlFor="lastName">Last Name *</Label>
                  <MultiLangInput
                    value={formData.lastName}
                    onChange={(value) => setFormData({...formData, lastName: value})}
                    placeholder="Doe"
                  />
                </div>
              </div>
              
              <div>
                <Label htmlFor="nickname">Nickname</Label>
                <MultiLangInput
                  value={formData.nickname}
                  onChange={(value) => setFormData({...formData, nickname: value})}
                  placeholder="Johnny"
                />
              </div>
              
              <div>
                <Label htmlFor="birthDate">Birth Date</Label>
                <Input
                  id="birthDate"
                  type="date"
                  value={formData.birthDate}
                  onChange={(e) => setFormData({...formData, birthDate: e.target.value})}
                />
              </div>
              
              <div>
                <Label htmlFor="description">Description</Label>
                <MultiLangInput
                  value={formData.description}
                  onChange={(value) => setFormData({...formData, description: value})}
                  placeholder="Brief description..."
                />
              </div>
              
              <div>
                <Label htmlFor="tags">Tags (comma-separated)</Label>
                <Input
                  id="tags"
                  value={formData.tags}
                  onChange={(e) => setFormData({...formData, tags: e.target.value})}
                  placeholder="family, friend, colleague"
                />
              </div>
              
              <div className="flex justify-end space-x-2">
                <Button variant="outline" onClick={() => setIsCreateDialogOpen(false)}>
                  Cancel
                </Button>
                <Button onClick={handleCreate}>
                  Create Person
                </Button>
              </div>
            </div>
          </DialogContent>
        </Dialog>
      </div>
      
      {/* People List */}
      {loading ? (
        <div className="text-center py-8">
          <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600 mx-auto"></div>
          <p className="mt-2 text-gray-600">Loading people...</p>
        </div>
      ) : error ? (
        <div className="text-center py-8">
          <AlertCircle className="h-12 w-12 text-red-400 mx-auto mb-4" />
          <h3 className="text-lg font-semibold text-gray-900 mb-2">Error loading people</h3>
          <p className="text-gray-600">{error}</p>
        </div>
      ) : people.length === 0 ? (
        <div className="text-center py-8">
          <User className="h-12 w-12 text-gray-400 mx-auto mb-4" />
          <h3 className="text-lg font-semibold text-gray-900 mb-2">No people found</h3>
          <p className="text-gray-600">Start by adding your first person.</p>
        </div>
      ) : (
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {people.map((person) => (
            <div key={person._id} className="bg-white rounded-lg shadow-sm border p-6">
              <div className="flex items-start justify-between mb-4">
                <div className="flex items-center space-x-3">
                  <div className="w-10 h-10 bg-blue-100 rounded-full flex items-center justify-center">
                    <User className="h-5 w-5 text-blue-600" />
                  </div>
                  <div>
                    <h3 className="font-semibold text-gray-900">
                      {typeof person.fullName === 'string' ? person.fullName : MultiLangUtils.getValue(person.fullName as any, currentLanguage)}
                    </h3>
                    {person.nickname && (typeof person.nickname === 'string' ? person.nickname : MultiLangUtils.getValue(person.nickname as any, currentLanguage)) && (
                      <p className="text-sm text-gray-600">
                        "{typeof person.nickname === 'string' ? person.nickname : MultiLangUtils.getValue(person.nickname as any, currentLanguage)}"
                      </p>
                    )}
                  </div>
                </div>
                
                <div className="flex space-x-1">
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => openEditDialog(person)}
                  >
                    <Edit className="h-4 w-4" />
                  </Button>
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => openDeleteDialog(person)}
                    className="text-red-600 hover:text-red-700"
                  >
                    <Trash2 className="h-4 w-4" />
                  </Button>
                </div>
              </div>
              
              {person.description && (typeof person.description === 'string' ? person.description : MultiLangUtils.getValue(person.description as any, currentLanguage)) && (
                <p className="text-sm text-gray-600 mb-3">
                  {typeof person.description === 'string' ? person.description : MultiLangUtils.getValue(person.description as any, currentLanguage)}
                </p>
              )}
              
              {person.birthDate && (
                <p className="text-sm text-gray-500 mb-3">
                  Born: {format(new Date(person.birthDate), 'MMM dd, yyyy')}
                </p>
              )}
              
              {person.tags && person.tags.length > 0 && (
                <div className="flex flex-wrap gap-1">
                  {person.tags.map((tag, index) => (
                    <span
                      key={index}
                      className="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-gray-100 text-gray-800"
                    >
                      {typeof tag === 'string' ? tag : tag.name}
                    </span>
                  ))}
                </div>
              )}
            </div>
          ))}
        </div>
      )}
      
      {/* Edit Dialog */}
      <Dialog open={isEditDialogOpen} onOpenChange={setIsEditDialogOpen}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle>Edit Person</DialogTitle>
          </DialogHeader>
          <div className="space-y-4">
            <div className="grid grid-cols-2 gap-4">
              <div>
                <Label htmlFor="editFirstName">First Name *</Label>
                <MultiLangInput
                  value={formData.firstName}
                  onChange={(value) => setFormData({...formData, firstName: value})}
                />
              </div>
              <div>
                <Label htmlFor="editLastName">Last Name *</Label>
                <MultiLangInput
                  value={formData.lastName}
                  onChange={(value) => setFormData({...formData, lastName: value})}
                />
              </div>
            </div>
            
            <div>
              <Label htmlFor="editNickname">Nickname</Label>
              <MultiLangInput
                value={formData.nickname}
                onChange={(value) => setFormData({...formData, nickname: value})}
              />
            </div>
            
            <div>
              <Label htmlFor="editBirthDate">Birth Date</Label>
              <Input
                id="editBirthDate"
                type="date"
                value={formData.birthDate}
                onChange={(e) => setFormData({...formData, birthDate: e.target.value})}
              />
            </div>
            
            <div>
              <Label htmlFor="editDescription">Description</Label>
              <MultiLangInput
                value={formData.description}
                onChange={(value) => setFormData({...formData, description: value})}
              />
            </div>
            
            <div>
              <Label htmlFor="editTags">Tags (comma-separated)</Label>
              <Input
                id="editTags"
                value={formData.tags}
                onChange={(e) => setFormData({...formData, tags: e.target.value})}
              />
            </div>
            
            <div className="flex justify-end space-x-2">
              <Button variant="outline" onClick={() => setIsEditDialogOpen(false)}>
                Cancel
              </Button>
              <Button onClick={handleEdit}>
                Update Person
              </Button>
            </div>
          </div>
        </DialogContent>
      </Dialog>
      
      {/* Delete Dialog */}
      <Dialog open={isDeleteDialogOpen} onOpenChange={setIsDeleteDialogOpen}>
        <DialogContent className="max-w-md">
          <DialogHeader>
            <DialogTitle>Delete Person</DialogTitle>
          </DialogHeader>
          <div className="space-y-4">
            <p className="text-gray-600">
              Are you sure you want to delete <strong>
                {personToDelete && personToDelete.fullName 
                  ? (typeof personToDelete.fullName === 'string' 
                      ? personToDelete.fullName 
                      : MultiLangUtils.getValue(personToDelete.fullName as any, currentLanguage))
                  : ''}
              </strong>? 
              This action cannot be undone.
            </p>
            <div className="flex justify-end space-x-2">
              <Button variant="outline" onClick={() => setIsDeleteDialogOpen(false)}>
                Cancel
              </Button>
              <Button 
                variant="destructive" 
                onClick={handleDelete}
              >
                Delete Person
              </Button>
            </div>
          </div>
        </DialogContent>
      </Dialog>
      </div>
    </AdminTemplate>
  )
}
