// src/templates/default/pages/Album.tsx
'use client'

import { useState, useEffect } from 'react'
import Image from 'next/image'
import Link from 'next/link'
import { useParams } from 'next/navigation'
import { MultiLangUtils } from '@/types/multi-lang'
import { useLanguage } from '@/contexts/LanguageContext'
import { useI18n } from '@/hooks/useI18n'
import { TemplateAlbum, TemplatePhoto } from '@/types'
import Header from '../components/Header'
import Footer from '../components/Footer'
import styles from '../styles.module.scss'

export default function AlbumPage() {
  const params = useParams()
  const alias = params?.alias as string
  const { currentLanguage } = useLanguage()
  const { t } = useI18n()

  const [album, setAlbum] = useState<TemplateAlbum | null>(null)
  const [photos, setPhotos] = useState<TemplatePhoto[]>([])
  const [subAlbums, setSubAlbums] = useState<TemplateAlbum[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)

  useEffect(() => {
    const fetchAlbumData = async () => {
      if (!alias) return
      try {
        setLoading(true)

        const albumRes = await fetch(`/api/albums/by-alias/${alias}`)
        if (!albumRes.ok) throw new Error('Album not found')
        const albumJson = await albumRes.json()
        if (!albumJson.success) throw new Error(albumJson.error || 'Failed to fetch album')
        const a: TemplateAlbum = albumJson.data
        setAlbum(a)

        const photosRes = await fetch(`/api/albums/${a._id}/photos`)
        if (photosRes.ok) {
          const photosJson = await photosRes.json()
          if (photosJson.success) setPhotos(photosJson.data)
        }

        const subAlbumsRes = await fetch(`/api/albums?parentId=${a._id}`)
        if (subAlbumsRes.ok) {
          const subAlbumsJson = await subAlbumsRes.json()
          if (subAlbumsJson.success) setSubAlbums(subAlbumsJson.data)
        }
      } catch (err) {
        setError(err instanceof Error ? err.message : 'Failed to fetch album')
      } finally {
        setLoading(false)
      }
    }

    fetchAlbumData()
  }, [alias])

  if (loading) {
    return (
      <div className={`min-h-screen ${styles.theme}`}>
        <Header />
        <div className="flex-1 flex items-center justify-center">
          <div className="text-center">
            <div className={`w-16 h-16 ${styles.loading} rounded-full mx-auto mb-4`}></div>
            <div className={styles.textSecondary}>Loading album...</div>
          </div>
        </div>
        <Footer />
      </div>
    )
  }

  if (error || !album) {
    return (
      <div className={`min-h-screen ${styles.theme}`}>
        <Header />
        <div className="flex-1 flex items-center justify-center">
          <div className="text-center">
            <div className={`${styles.textSecondary} mb-4`}>{error || 'Album not found'}</div>
            <Link href="/albums" className={styles.button}>Back to Albums</Link>
          </div>
        </div>
        <Footer />
      </div>
    )
  }

  return (
    <div className={`min-h-screen ${styles.theme}`}>
      <Header />

      <main className="flex-1">
        <section className={styles.section}>
          <div className="max-w-6xl mx-auto text-center">
            <h1 className={styles.sectionTitle}>
              {MultiLangUtils.getTextValue(album.name, currentLanguage)}
            </h1>
            {album.description && (
              <div
                className={styles.sectionContent}
                dangerouslySetInnerHTML={{
                  __html: MultiLangUtils.getHTMLValue(album.description, currentLanguage)
                }}
              />
            )}
          </div>
        </section>

        {subAlbums.length > 0 && (
          <section className={styles.section}>
            <div className="max-w-6xl mx-auto">
              <h2 className={styles.heading2}>Sub Albums</h2>
              <div className={styles.galleryGrid}>
                {subAlbums.map((sa) => (
                  <Link key={sa._id} href={`/albums/${sa.alias}`}>
                    <div className={`${styles.card} h-full`}> 
                      <div className="overflow-hidden">
                        <div className={`${styles.cardImage} ${styles.bgSecondary} flex items-center justify-center`}>
                          <div className="text-4xl text-gray-400">📁</div>
                        </div>
                      </div>
                      <div className="p-4">
                        <h3 className={styles.heading3}>
                          {MultiLangUtils.getTextValue(sa.name, currentLanguage)}
                        </h3>
                        <div className={styles.textSecondary}>
                          {sa.photoCount} photos
                        </div>
                      </div>
                    </div>
                  </Link>
                ))}
              </div>
            </div>
          </section>
        )}

        {photos.length > 0 && (
          <section className={styles.gallery}>
            <div className="max-w-6xl mx-auto">
              <div className={styles.galleryGrid}>
                {photos.map((p, i) => (
                  <div key={p._id} className={`${styles.card}`}>
                    <div className="overflow-hidden">
                      <Image
                        src={p.storage?.thumbnailPath || p.url || '/placeholder.jpg'}
                        alt={p.alt ? MultiLangUtils.getTextValue(p.alt, currentLanguage) : `Photo ${i + 1}`}
                        width={400}
                        height={300}
                        className={styles.cardImage}
                        loading="lazy"
                      />
                    </div>
                  </div>
                ))}
              </div>
            </div>
          </section>
        )}

        {photos.length === 0 && subAlbums.length === 0 && (
          <section className={styles.section}>
            <div className="max-w-6xl mx-auto text-center">
              <div className={styles.textSecondary}>This album is empty.</div>
            </div>
          </section>
        )}
      </main>

      <Footer />
    </div>
  )
}

// frontend/src/lib/templates/minimal/Album.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { page } from '$app/stores';
	import { afterNavigate } from '$app/navigation';
	import { browser } from '$app/environment';
	import { currentLanguage } from '$stores/language';
	import { MultiLangUtils } from '$utils/multiLang';
	import AlbumBreadcrumbs from '$lib/components/AlbumBreadcrumbs.svelte';
	import PhotoLightbox from '$lib/components/PhotoLightbox.svelte';

	interface AlbumData {
		album: {
			_id: string;
			name: any;
			description?: any;
			alias: string;
			photoCount?: number;
		};
		subAlbums: any[];
		photos: any[];
	}

	let alias = $page.params.alias || $page.params.id;
	let albumData: AlbumData | null = null;
	let loading = true;
	let error: string | null = null;
	let lightboxOpen = false;
	let lightboxIndex = 0;
	let isInitialLoad = true;

	// React to route parameter changes
	afterNavigate(({ to, from }) => {
		if (!browser) return;
		
		const newAlias = to?.params?.alias || to?.params?.id;
		const oldAlias = from?.params?.alias || from?.params?.id;
		
		// Only fetch if the alias actually changed (not on initial load)
		if (newAlias && newAlias !== oldAlias) {
			alias = newAlias;
			fetchAlbumData();
		} else if (isInitialLoad && newAlias) {
			// Handle initial load
			alias = newAlias;
			fetchAlbumData();
			isInitialLoad = false;
		}
	});

	onMount(async () => {
		if (alias && isInitialLoad) {
			await fetchAlbumData();
			isInitialLoad = false;
		}
	});

	async function fetchAlbumData() {
		if (!alias || !browser) return;
		try {
			loading = true;
			error = null;
			const res = await fetch(`/api/albums/${encodeURIComponent(alias)}/data?page=1&limit=50&t=${Date.now()}`, {
				cache: 'no-store'
			});
			if (!res.ok) {
				const errorData = await res.json().catch(() => ({ error: 'Album not found' }));
				throw new Error(errorData.error || 'Album not found');
			}
			const data = await res.json();
			albumData = data;
			console.log('Album data loaded:', albumData);
		} catch (err) {
			error = err instanceof Error ? err.message : 'Failed to fetch album';
			albumData = null;
		} finally {
			loading = false;
		}
	}

	function openLightbox(index: number) {
		lightboxIndex = index;
		lightboxOpen = true;
	}
</script>

{#if loading}
	<div class="min-h-screen flex items-center justify-center bg-white">
		<div class="text-center">
			<div class="w-8 h-8 border-2 border-black border-t-transparent rounded-full animate-spin mx-auto mb-4"></div>
			<p class="text-sm text-gray-600">Loading album...</p>
		</div>
	</div>
{:else if error}
	<div class="min-h-screen flex items-center justify-center bg-white">
		<div class="text-center">
			<p class="text-sm text-black">{error}</p>
		</div>
	</div>
{:else if albumData}
	<div class="min-h-screen bg-white">
		<!-- Breadcrumbs -->
		{#if albumData.album}
			<AlbumBreadcrumbs albumId={albumData.album._id} />
		{/if}

		<!-- Album Header -->
		<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
			<h1 class="text-3xl font-light text-black mb-4 tracking-tight">
				{MultiLangUtils.getTextValue(albumData.album.name, $currentLanguage)}
			</h1>
			{#if albumData.album.description}
				<div class="prose prose-sm max-w-4xl mb-6 text-gray-600">
					{@html MultiLangUtils.getHTMLValue(albumData.album.description, $currentLanguage)}
				</div>
			{/if}
		</div>

		<!-- Sub-albums -->
		{#if albumData.subAlbums && albumData.subAlbums.length > 0}
			<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 border-t border-gray-200">
				<h2 class="text-xl font-light text-black mb-4 tracking-tight">Sub-albums</h2>
				<div class="grid grid-cols-1 md:grid-cols-3 gap-4">
					{#each albumData.subAlbums as subAlbum}
						<a
							href={`/albums/${subAlbum.alias || subAlbum._id}`}
							class="bg-white border border-black hover:border-gray-600 transition-colors p-4"
						>
							<h3 class="text-base font-normal text-black mb-1">
								{MultiLangUtils.getTextValue(subAlbum.name, $currentLanguage)}
							</h3>
							<p class="text-xs text-gray-600">
								{#if subAlbum.photoCount && subAlbum.photoCount > 0}
									{subAlbum.photoCount} photos
								{/if}
								{#if subAlbum.photoCount && subAlbum.photoCount > 0 && subAlbum.childAlbumCount && subAlbum.childAlbumCount > 0}
									• 
								{/if}
								{#if subAlbum.childAlbumCount && subAlbum.childAlbumCount > 0}
									{subAlbum.childAlbumCount} {subAlbum.childAlbumCount === 1 ? 'album' : 'albums'}
								{/if}
							</p>
						</a>
					{/each}
				</div>
			</div>
		{/if}

		<!-- Photos Grid -->
		{#if albumData.photos && albumData.photos.length > 0}
			<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 border-t border-gray-200">
				<h2 class="text-xl font-light text-black mb-4 tracking-tight">Photos</h2>
				<div class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-2">
					{#each albumData.photos as photo, index}
						<button
							on:click={() => openLightbox(index)}
							class="relative aspect-square bg-gray-100 overflow-hidden hover:opacity-80 transition-opacity"
						>
							{#if photo.storage?.thumbnailPath || photo.storage?.url || photo.url}
								<img
									src={photo.storage?.thumbnailPath || photo.storage?.url || photo.url}
									alt={MultiLangUtils.getTextValue(photo.title, $currentLanguage) || 'Photo'}
									class="w-full h-full object-cover"
									style="image-orientation: from-image;"
								/>
							{/if}
						</button>
					{/each}
				</div>
			</div>
		{:else}
			<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 border-t border-gray-200">
				<p class="text-sm text-gray-600 text-center">No photos in this album yet.</p>
			</div>
		{/if}
	</div>

	<!-- Photo Lightbox -->
	{#if lightboxOpen && albumData.photos}
		<PhotoLightbox
			photos={albumData.photos}
			initialIndex={lightboxIndex}
			on:close={() => (lightboxOpen = false)}
		/>
	{/if}
{/if}
