// frontend/src/routes/admin/templates/overrides/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { goto } from '$app/navigation';
	import { siteConfigData, siteConfig } from '$stores/siteConfig';

	export let data; // From +layout.server.ts, contains user info

	interface TemplateConfig {
		templateName: string;
		displayName: string;
		colors: {
			primary: string;
			secondary: string;
			accent: string;
			background: string;
			text: string;
			muted: string;
		};
		fonts: {
			heading: string;
			body: string;
		};
		layout: {
			maxWidth: string;
			containerPadding: string;
			gridGap: string;
		};
		visibility?: {
			hero?: boolean;
			languageSelector?: boolean;
			authButtons?: boolean;
			footerMenu?: boolean;
			statistics?: boolean;
			promotion?: boolean;
		};
		componentsConfig?: {
			header?: {
				showLogo?: boolean;
				showSiteTitle?: boolean;
				enableThemeToggle?: boolean;
				enableLanguageSelector?: boolean;
				showGreeting?: boolean;
				showAuthButtons?: boolean;
			};
		};
	}

	let templates: TemplateConfig[] = [];
	let activeTemplate: TemplateConfig | null = null;
	let loading = true;
	let saving = false;
	let resetting = false;
	let message = '';
	let error = '';
	let activeTab = 'colors';
	let hasChanges = false;

	// Local overrides state
	let localOverrides: {
		customColors?: Record<string, string>;
		customFonts?: Record<string, string>;
		customLayout?: Record<string, string>;
		componentVisibility?: Record<string, boolean>;
		headerConfig?: Record<string, any>;
	} = {};

	$: currentTemplateName = $siteConfigData?.template?.activeTemplate || 'modern';
	$: siteTemplateOverrides = $siteConfigData?.template || {};

	onMount(async () => {
		await loadTemplates();
		initializeLocalOverrides();
	});

	function initializeLocalOverrides() {
		localOverrides = {
			customColors: { ...siteTemplateOverrides.customColors },
			customFonts: { ...siteTemplateOverrides.customFonts },
			customLayout: { ...siteTemplateOverrides.customLayout },
			componentVisibility: { ...siteTemplateOverrides.componentVisibility },
			headerConfig: { ...siteTemplateOverrides.headerConfig }
		};
	}

	async function loadTemplates() {
		loading = true;
		error = '';
		try {
			const response = await fetch('/api/admin/templates');
			if (!response.ok) {
				throw new Error('Failed to load templates');
			}
			const data = await response.json();
			templates = Array.isArray(data) ? data : [];
			activeTemplate = templates.find((t) => t.templateName === currentTemplateName) || templates[0] || null;
		} catch (err) {
			console.error('Error loading templates:', err);
			error = `Failed to load templates: ${err instanceof Error ? err.message : 'Unknown error'}`;
		} finally {
			loading = false;
		}
	}

	function updateColor(colorType: string, value: string) {
		if (!localOverrides.customColors) {
			localOverrides.customColors = {};
		}
		localOverrides.customColors[colorType] = value;
		localOverrides = { ...localOverrides };
		hasChanges = true;
	}

	function updateFont(fontType: string, value: string) {
		if (!localOverrides.customFonts) {
			localOverrides.customFonts = {};
		}
		localOverrides.customFonts[fontType] = value;
		localOverrides = { ...localOverrides };
		hasChanges = true;
	}

	function updateLayout(layoutType: string, value: string) {
		if (!localOverrides.customLayout) {
			localOverrides.customLayout = {};
		}
		localOverrides.customLayout[layoutType] = value;
		localOverrides = { ...localOverrides };
		hasChanges = true;
	}

	function updateVisibility(component: string, value: boolean) {
		if (!localOverrides.componentVisibility) {
			localOverrides.componentVisibility = {};
		}
		localOverrides.componentVisibility[component] = value;
		localOverrides = { ...localOverrides };
		hasChanges = true;
	}

	function updateHeaderConfig(configType: string, value: any) {
		if (!localOverrides.headerConfig) {
			localOverrides.headerConfig = {};
		}
		localOverrides.headerConfig[configType] = value;
		localOverrides = { ...localOverrides };
		hasChanges = true;
	}

	function getEffectiveColor(colorType: string): string {
		return localOverrides.customColors?.[colorType] || activeTemplate?.colors[colorType] || '#000000';
	}

	function getEffectiveFont(fontType: string): string {
		return localOverrides.customFonts?.[fontType] || activeTemplate?.fonts[fontType] || 'Inter';
	}

	function getEffectiveLayout(layoutType: string): string {
		return localOverrides.customLayout?.[layoutType] || activeTemplate?.layout[layoutType] || '';
	}

	function getEffectiveVisibility(component: string): boolean {
		return localOverrides.componentVisibility?.[component] !== undefined
			? localOverrides.componentVisibility[component]
			: activeTemplate?.visibility?.[component] ?? true;
	}

	function getEffectiveHeaderConfig(configType: string): boolean {
		return localOverrides.headerConfig?.[configType] !== undefined
			? localOverrides.headerConfig[configType]
			: activeTemplate?.componentsConfig?.header?.[configType] ?? true;
	}

	function hasOverrides(): boolean {
		return !!(
			(localOverrides.customColors && Object.keys(localOverrides.customColors).length > 0) ||
			(localOverrides.customFonts && Object.keys(localOverrides.customFonts).length > 0) ||
			(localOverrides.customLayout && Object.keys(localOverrides.customLayout).length > 0) ||
			(localOverrides.componentVisibility && Object.keys(localOverrides.componentVisibility).length > 0) ||
			(localOverrides.headerConfig && Object.keys(localOverrides.headerConfig).length > 0)
		);
	}

	async function saveOverrides() {
		saving = true;
		message = '';
		error = '';

		try {
			const response = await fetch('/api/admin/site-config', {
				method: 'PUT',
				headers: {
					'Content-Type': 'application/json'
				},
				body: JSON.stringify({
					template: {
						activeTemplate: currentTemplateName,
						...localOverrides
					}
				})
			});

			if (!response.ok) {
				const errorData = await response.json().catch(() => ({}));
				throw new Error(errorData.message || 'Failed to save overrides');
			}

			message = 'Template overrides saved successfully!';
			hasChanges = false;
			siteConfig.load(); // Refresh site config store

			setTimeout(() => {
				message = '';
			}, 3000);
		} catch (err) {
			console.error('Error saving overrides:', err);
			error = `Failed to save overrides: ${err instanceof Error ? err.message : 'Unknown error'}`;
		} finally {
			saving = false;
		}
	}

	async function resetOverrides() {
		if (!confirm('Are you sure you want to reset all template overrides to default?')) {
			return;
		}

		resetting = true;
		message = '';
		error = '';

		try {
			const response = await fetch('/api/admin/site-config', {
				method: 'PUT',
				headers: {
					'Content-Type': 'application/json'
				},
				body: JSON.stringify({
					template: {
						activeTemplate: currentTemplateName,
						customColors: {},
						customFonts: {},
						customLayout: {},
						componentVisibility: {},
						headerConfig: {}
					}
				})
			});

			if (!response.ok) {
				const errorData = await response.json().catch(() => ({}));
				throw new Error(errorData.message || 'Failed to reset overrides');
			}

			message = 'Template overrides reset to default!';
			localOverrides = {};
			hasChanges = false;
			siteConfig.load(); // Refresh site config store

			setTimeout(() => {
				message = '';
			}, 3000);
		} catch (err) {
			console.error('Error resetting overrides:', err);
			error = `Failed to reset overrides: ${err instanceof Error ? err.message : 'Unknown error'}`;
		} finally {
			resetting = false;
		}
	}

	function cancelChanges() {
		if (hasChanges && !confirm('You have unsaved changes. Are you sure you want to cancel?')) {
			return;
		}
		initializeLocalOverrides();
		hasChanges = false;
	}
</script>

<svelte:head>
	<title>Template Overrides - Admin</title>
</svelte:head>

<div class="min-h-screen bg-gray-50 py-8">
	<div class="max-w-6xl mx-auto px-4">
		<div class="bg-white rounded-lg shadow-md p-6">
			<!-- Header -->
			<div class="flex items-center justify-between mb-6">
				<div class="flex items-center gap-4">
					<a
						href="/admin/templates"
						class="text-blue-600 hover:text-blue-800 text-sm font-medium"
					>
						← Back to Templates
					</a>
					<div>
						<h1 class="text-2xl font-bold text-gray-900">Template Overrides</h1>
						<p class="text-gray-600 mt-1">
							Customize your active template:
							<span class="font-semibold">{activeTemplate?.displayName || currentTemplateName}</span>
						</p>
					</div>
				</div>
				<div class="flex gap-2">
					{#if hasChanges}
						<button
							type="button"
							on:click={cancelChanges}
							class="px-4 py-2 bg-gray-200 text-gray-700 rounded-md hover:bg-gray-300 text-sm font-medium"
						>
							Cancel
						</button>
					{/if}
					{#if hasOverrides()}
						<button
							type="button"
							on:click={resetOverrides}
							disabled={resetting}
							class="px-4 py-2 bg-orange-600 text-white rounded-md hover:bg-orange-700 disabled:opacity-50 text-sm font-medium"
						>
							{#if resetting}
								Resetting...
							{:else}
								Reset to Default
							{/if}
						</button>
					{/if}
					<button
						type="button"
						on:click={saveOverrides}
						disabled={!hasChanges || saving}
						class="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 disabled:opacity-50 text-sm font-medium"
					>
						{#if saving}
							Saving...
						{:else}
							Save Changes
						{/if}
					</button>
				</div>
			</div>

			{#if message}
				<div class="mb-4 p-4 rounded-md bg-green-50 text-green-700">{message}</div>
			{/if}

			{#if error}
				<div class="mb-4 p-4 rounded-md bg-red-50 text-red-700">{error}</div>
			{/if}

			{#if hasOverrides()}
				<div class="mb-4 p-4 rounded-md bg-blue-50 text-blue-700 text-sm">
					This template has custom overrides applied. Changes will be merged with the base template
					configuration.
				</div>
			{/if}

			{#if loading}
				<div class="text-center py-8">
					<div class="inline-block animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
					<p class="mt-2 text-gray-600">Loading template overrides...</p>
				</div>
			{:else if !activeTemplate}
				<div class="text-center py-8">
					<p class="text-gray-600">No active template found.</p>
				</div>
			{:else}
				<!-- Tabs -->
				<div class="border-b border-gray-200 mb-6">
					<nav class="-mb-px flex space-x-8">
						<button
							type="button"
							on:click={() => (activeTab = 'colors')}
							class="py-4 px-1 border-b-2 font-medium text-sm {activeTab === 'colors'
								? 'border-blue-500 text-blue-600'
								: 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'}"
						>
							🎨 Colors
						</button>
						<button
							type="button"
							on:click={() => (activeTab = 'fonts')}
							class="py-4 px-1 border-b-2 font-medium text-sm {activeTab === 'fonts'
								? 'border-blue-500 text-blue-600'
								: 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'}"
						>
							🔤 Fonts
						</button>
						<button
							type="button"
							on:click={() => (activeTab = 'layout')}
							class="py-4 px-1 border-b-2 font-medium text-sm {activeTab === 'layout'
								? 'border-blue-500 text-blue-600'
								: 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'}"
						>
							📐 Layout
						</button>
						<button
							type="button"
							on:click={() => (activeTab = 'visibility')}
							class="py-4 px-1 border-b-2 font-medium text-sm {activeTab === 'visibility'
								? 'border-blue-500 text-blue-600'
								: 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'}"
						>
							👁️ Visibility
						</button>
						<button
							type="button"
							on:click={() => (activeTab = 'header')}
							class="py-4 px-1 border-b-2 font-medium text-sm {activeTab === 'header'
								? 'border-blue-500 text-blue-600'
								: 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'}"
						>
							⚙️ Header
						</button>
					</nav>
				</div>

				<!-- Tab Content -->
				{#if activeTab === 'colors'}
					<div class="space-y-6">
						<h2 class="text-xl font-semibold text-gray-900">Color Customization</h2>
						<div class="grid grid-cols-1 md:grid-cols-2 gap-6">
							{#each ['primary', 'secondary', 'accent', 'background', 'text', 'muted'] as colorType}
								<div>
									<label class="block text-sm font-medium text-gray-700 mb-2">
										{colorType.charAt(0).toUpperCase() + colorType.slice(1)} Color
									</label>
									<div class="flex gap-2">
										<input
											type="color"
											value={getEffectiveColor(colorType)}
											on:input={(e) => updateColor(colorType, e.target.value)}
											class="w-16 h-10 border border-gray-300 rounded cursor-pointer"
										/>
										<input
											type="text"
											value={getEffectiveColor(colorType)}
											on:input={(e) => updateColor(colorType, e.target.value)}
											placeholder="#000000"
											class="flex-1 px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
										/>
									</div>
									<p class="mt-1 text-xs text-gray-500">
										Default: {activeTemplate.colors[colorType]}
									</p>
								</div>
							{/each}
						</div>
					</div>
				{:else if activeTab === 'fonts'}
					<div class="space-y-6">
						<h2 class="text-xl font-semibold text-gray-900">Font Customization</h2>
						<div class="grid grid-cols-1 md:grid-cols-2 gap-6">
							<div>
								<label class="block text-sm font-medium text-gray-700 mb-2">
									Heading Font
								</label>
								<input
									type="text"
									value={getEffectiveFont('heading')}
									on:input={(e) => updateFont('heading', e.target.value)}
									placeholder="Inter"
									class="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
								/>
								<p class="mt-1 text-xs text-gray-500">Default: {activeTemplate.fonts.heading}</p>
							</div>
							<div>
								<label class="block text-sm font-medium text-gray-700 mb-2">
									Body Font
								</label>
								<input
									type="text"
									value={getEffectiveFont('body')}
									on:input={(e) => updateFont('body', e.target.value)}
									placeholder="Inter"
									class="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
								/>
								<p class="mt-1 text-xs text-gray-500">Default: {activeTemplate.fonts.body}</p>
							</div>
						</div>
					</div>
				{:else if activeTab === 'layout'}
					<div class="space-y-6">
						<h2 class="text-xl font-semibold text-gray-900">Layout Customization</h2>
						<div class="grid grid-cols-1 md:grid-cols-3 gap-6">
							<div>
								<label class="block text-sm font-medium text-gray-700 mb-2">
									Max Width
								</label>
								<input
									type="text"
									value={getEffectiveLayout('maxWidth')}
									on:input={(e) => updateLayout('maxWidth', e.target.value)}
									placeholder="1200px"
									class="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
								/>
								<p class="mt-1 text-xs text-gray-500">Default: {activeTemplate.layout.maxWidth}</p>
							</div>
							<div>
								<label class="block text-sm font-medium text-gray-700 mb-2">
									Container Padding
								</label>
								<input
									type="text"
									value={getEffectiveLayout('containerPadding')}
									on:input={(e) => updateLayout('containerPadding', e.target.value)}
									placeholder="1rem"
									class="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
								/>
								<p class="mt-1 text-xs text-gray-500">
									Default: {activeTemplate.layout.containerPadding}
								</p>
							</div>
							<div>
								<label class="block text-sm font-medium text-gray-700 mb-2">
									Grid Gap
								</label>
								<input
									type="text"
									value={getEffectiveLayout('gridGap')}
									on:input={(e) => updateLayout('gridGap', e.target.value)}
									placeholder="1.5rem"
									class="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
								/>
								<p class="mt-1 text-xs text-gray-500">Default: {activeTemplate.layout.gridGap}</p>
							</div>
						</div>
					</div>
				{:else if activeTab === 'visibility'}
					<div class="space-y-6">
						<h2 class="text-xl font-semibold text-gray-900">Component Visibility</h2>
						<div class="space-y-4">
							{#each [
								{ key: 'hero', label: 'Hero Section', desc: 'Show the hero section on the home page' },
								{
									key: 'languageSelector',
									label: 'Language Selector',
									desc: 'Show the language selection dropdown'
								},
								{ key: 'authButtons', label: 'Auth Buttons', desc: 'Show login/logout buttons' },
								{ key: 'footerMenu', label: 'Footer Menu', desc: 'Show footer navigation menu' },
								{ key: 'statistics', label: 'Statistics', desc: 'Show site statistics' },
								{ key: 'promotion', label: 'Promotion', desc: 'Show promotional content' }
							] as component}
								<div class="flex items-center justify-between p-4 border border-gray-200 rounded-lg">
									<div>
										<label class="text-sm font-medium text-gray-900">{component.label}</label>
										<p class="text-xs text-gray-500 mt-1">{component.desc}</p>
									</div>
									<label class="relative inline-flex items-center cursor-pointer">
										<input
											type="checkbox"
											checked={getEffectiveVisibility(component.key)}
											on:change={(e) => updateVisibility(component.key, e.target.checked)}
											class="sr-only peer"
										/>
										<div
											class="w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-blue-300 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-blue-600"
										></div>
									</label>
								</div>
							{/each}
						</div>
					</div>
				{:else if activeTab === 'header'}
					<div class="space-y-6">
						<h2 class="text-xl font-semibold text-gray-900">Header Configuration</h2>
						<div class="space-y-4">
							{#each [
								{ key: 'showLogo', label: 'Show Logo', desc: 'Display the site logo in the header' },
								{
									key: 'showSiteTitle',
									label: 'Show Site Title',
									desc: 'Display the site title in the header'
								},
								{
									key: 'enableThemeToggle',
									label: 'Enable Theme Toggle',
									desc: 'Show dark/light mode toggle button'
								},
								{
									key: 'enableLanguageSelector',
									label: 'Enable Language Selector',
									desc: 'Show language selection dropdown'
								},
								{ key: 'showAuthButtons', label: 'Show Auth Buttons', desc: 'Display login/logout buttons' },
								{
									key: 'showGreeting',
									label: 'Show Greeting',
									desc: 'Display welcome message for logged-in users'
								}
							] as config}
								<div class="flex items-center justify-between p-4 border border-gray-200 rounded-lg">
									<div>
										<label class="text-sm font-medium text-gray-900">{config.label}</label>
										<p class="text-xs text-gray-500 mt-1">{config.desc}</p>
									</div>
									<label class="relative inline-flex items-center cursor-pointer">
										<input
											type="checkbox"
											checked={getEffectiveHeaderConfig(config.key)}
											on:change={(e) => updateHeaderConfig(config.key, e.target.checked)}
											class="sr-only peer"
										/>
										<div
											class="w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-blue-300 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-blue-600"
										></div>
									</label>
								</div>
							{/each}
						</div>
					</div>
				{/if}
			{/if}
		</div>
	</div>
</div>

// src/app/admin/templates/overrides/page.tsx
'use client'

import { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import { useTemplateOverrides } from '@/hooks/useTemplateOverrides'
import { useSiteConfig } from '@/hooks/useSiteConfig'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Switch } from '@/components/ui/switch'
import { Badge } from '@/components/ui/badge'
import { Separator } from '@/components/ui/separator'
import { Alert, AlertDescription } from '@/components/ui/alert'
import { Loader2, Palette, Type, Layout, Eye, Settings, RotateCcw, ArrowLeft } from 'lucide-react'

export default function TemplateOverridesPage() {
  const router = useRouter()
  const { template, hasOverrides, activeOverrides, loading, error, updateOverrides, resetOverrides } = useTemplateOverrides()
  const { config } = useSiteConfig()
  const [isUpdating, setIsUpdating] = useState(false)
  const [isResetting, setIsResetting] = useState(false)
  const [localOverrides, setLocalOverrides] = useState<any>({})
  const [hasChanges, setHasChanges] = useState(false)

  useEffect(() => {
    if (activeOverrides) {
      setLocalOverrides(activeOverrides)
    }
  }, [activeOverrides])

  const handleColorChange = (colorType: string, value: string) => {
    const newOverrides = {
      ...localOverrides,
      customColors: {
        ...localOverrides.customColors,
        [colorType]: value
      }
    }
    setLocalOverrides(newOverrides)
    setHasChanges(true)
  }

  const handleFontChange = (fontType: string, value: string) => {
    const newOverrides = {
      ...localOverrides,
      customFonts: {
        ...localOverrides.customFonts,
        [fontType]: value
      }
    }
    setLocalOverrides(newOverrides)
    setHasChanges(true)
  }

  const handleLayoutChange = (layoutType: string, value: string) => {
    const newOverrides = {
      ...localOverrides,
      customLayout: {
        ...localOverrides.customLayout,
        [layoutType]: value
      }
    }
    setLocalOverrides(newOverrides)
    setHasChanges(true)
  }

  const handleVisibilityChange = (component: string, value: boolean) => {
    const newOverrides = {
      ...localOverrides,
      componentVisibility: {
        ...localOverrides.componentVisibility,
        [component]: value
      }
    }
    setLocalOverrides(newOverrides)
    setHasChanges(true)
  }

  const handleHeaderConfigChange = (configType: string, value: any) => {
    const newOverrides = {
      ...localOverrides,
      headerConfig: {
        ...localOverrides.headerConfig,
        [configType]: value
      }
    }
    setLocalOverrides(newOverrides)
    setHasChanges(true)
  }

  const handleSave = async () => {
    try {
      setIsUpdating(true)
      await updateOverrides(localOverrides)
      setHasChanges(false)
    } catch (error) {
      console.error('Failed to save overrides:', error)
    } finally {
      setIsUpdating(false)
    }
  }

  const handleReset = async () => {
    try {
      setIsResetting(true)
      await resetOverrides()
      setLocalOverrides({})
      setHasChanges(false)
    } catch (error) {
      console.error('Failed to reset overrides:', error)
    } finally {
      setIsResetting(false)
    }
  }

  const handleBack = () => {
    if (hasChanges) {
      const confirmed = window.confirm('You have unsaved changes. Are you sure you want to go back?')
      if (confirmed) {
        router.push('/admin')
      }
    } else {
      router.push('/admin')
    }
  }

  const handleCancel = () => {
    if (hasChanges) {
      const confirmed = window.confirm('You have unsaved changes. Are you sure you want to cancel?')
      if (confirmed) {
        setLocalOverrides(activeOverrides)
        setHasChanges(false)
      }
    } else {
      setLocalOverrides(activeOverrides)
      setHasChanges(false)
    }
  }

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className="text-center">
          <Loader2 className="h-8 w-8 animate-spin mx-auto mb-4" />
          <p>Loading template overrides...</p>
        </div>
      </div>
    )
  }

  if (error) {
    return (
      <div className="container mx-auto py-8">
        <Alert variant="destructive">
          <AlertDescription>{error}</AlertDescription>
        </Alert>
      </div>
    )
  }

  if (!template) {
    return (
      <div className="container mx-auto py-8">
        <Alert>
          <AlertDescription>No template found</AlertDescription>
        </Alert>
      </div>
    )
  }

  return (
    <div className="container mx-auto py-8 space-y-6">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-4">
          <Button
            variant="outline"
            onClick={handleBack}
            className="flex items-center gap-2"
          >
            <ArrowLeft className="h-4 w-4" />
            Back to Admin
          </Button>
          <div>
            <h1 className="text-3xl font-bold">Template Overrides</h1>
            <p className="text-muted-foreground">
              Customize your active template: <Badge variant="outline">{template.displayName}</Badge>
            </p>
          </div>
        </div>
        <div className="flex gap-2">
          {hasChanges && (
            <Button
              variant="outline"
              onClick={handleCancel}
            >
              Cancel
            </Button>
          )}
          {hasOverrides && (
            <Button
              variant="outline"
              onClick={handleReset}
              disabled={isResetting}
            >
              {isResetting ? (
                <Loader2 className="h-4 w-4 animate-spin mr-2" />
              ) : (
                <RotateCcw className="h-4 w-4 mr-2" />
              )}
              Reset to Default
            </Button>
          )}
          <Button
            onClick={handleSave}
            disabled={!hasChanges || isUpdating}
          >
            {isUpdating ? (
              <Loader2 className="h-4 w-4 animate-spin mr-2" />
            ) : (
              <Settings className="h-4 w-4 mr-2" />
            )}
            Save Changes
          </Button>
        </div>
      </div>

      {hasOverrides && (
        <Alert>
          <AlertDescription>
            This template has custom overrides applied. Changes will be merged with the base template configuration.
          </AlertDescription>
        </Alert>
      )}

      <Tabs defaultValue="colors" className="space-y-6">
        <TabsList className="grid w-full grid-cols-5">
          <TabsTrigger value="colors" className="flex items-center gap-2">
            <Palette className="h-4 w-4" />
            Colors
          </TabsTrigger>
          <TabsTrigger value="fonts" className="flex items-center gap-2">
            <Type className="h-4 w-4" />
            Fonts
          </TabsTrigger>
          <TabsTrigger value="layout" className="flex items-center gap-2">
            <Layout className="h-4 w-4" />
            Layout
          </TabsTrigger>
          <TabsTrigger value="visibility" className="flex items-center gap-2">
            <Eye className="h-4 w-4" />
            Visibility
          </TabsTrigger>
          <TabsTrigger value="header" className="flex items-center gap-2">
            <Settings className="h-4 w-4" />
            Header
          </TabsTrigger>
        </TabsList>

        <TabsContent value="colors" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>Color Customization</CardTitle>
              <CardDescription>
                Override the template's color scheme
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="primary">Primary Color</Label>
                  <Input
                    id="primary"
                    type="color"
                    value={localOverrides.customColors?.primary || template.colors.primary}
                    onChange={(e) => handleColorChange('primary', e.target.value)}
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="secondary">Secondary Color</Label>
                  <Input
                    id="secondary"
                    type="color"
                    value={localOverrides.customColors?.secondary || template.colors.secondary}
                    onChange={(e) => handleColorChange('secondary', e.target.value)}
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="accent">Accent Color</Label>
                  <Input
                    id="accent"
                    type="color"
                    value={localOverrides.customColors?.accent || template.colors.accent}
                    onChange={(e) => handleColorChange('accent', e.target.value)}
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="background">Background Color</Label>
                  <Input
                    id="background"
                    type="color"
                    value={localOverrides.customColors?.background || template.colors.background}
                    onChange={(e) => handleColorChange('background', e.target.value)}
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="text">Text Color</Label>
                  <Input
                    id="text"
                    type="color"
                    value={localOverrides.customColors?.text || template.colors.text}
                    onChange={(e) => handleColorChange('text', e.target.value)}
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="muted">Muted Color</Label>
                  <Input
                    id="muted"
                    type="color"
                    value={localOverrides.customColors?.muted || template.colors.muted}
                    onChange={(e) => handleColorChange('muted', e.target.value)}
                  />
                </div>
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="fonts" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>Font Customization</CardTitle>
              <CardDescription>
                Override the template's font settings
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="heading-font">Heading Font</Label>
                  <Input
                    id="heading-font"
                    value={localOverrides.customFonts?.heading || template.fonts.heading}
                    onChange={(e) => handleFontChange('heading', e.target.value)}
                    placeholder="e.g., Inter, Roboto, Arial"
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="body-font">Body Font</Label>
                  <Input
                    id="body-font"
                    value={localOverrides.customFonts?.body || template.fonts.body}
                    onChange={(e) => handleFontChange('body', e.target.value)}
                    placeholder="e.g., Inter, Roboto, Arial"
                  />
                </div>
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="layout" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>Layout Customization</CardTitle>
              <CardDescription>
                Override the template's layout settings
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="grid grid-cols-3 gap-4">
                <div className="space-y-2">
                  <Label htmlFor="max-width">Max Width</Label>
                  <Input
                    id="max-width"
                    value={localOverrides.customLayout?.maxWidth || template.layout.maxWidth}
                    onChange={(e) => handleLayoutChange('maxWidth', e.target.value)}
                    placeholder="e.g., 1200px, 100%"
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="container-padding">Container Padding</Label>
                  <Input
                    id="container-padding"
                    value={localOverrides.customLayout?.containerPadding || template.layout.containerPadding}
                    onChange={(e) => handleLayoutChange('containerPadding', e.target.value)}
                    placeholder="e.g., 1rem, 2rem"
                  />
                </div>
                <div className="space-y-2">
                  <Label htmlFor="grid-gap">Grid Gap</Label>
                  <Input
                    id="grid-gap"
                    value={localOverrides.customLayout?.gridGap || template.layout.gridGap}
                    onChange={(e) => handleLayoutChange('gridGap', e.target.value)}
                    placeholder="e.g., 1.5rem, 2rem"
                  />
                </div>
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="visibility" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>Component Visibility</CardTitle>
              <CardDescription>
                Show or hide template components
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-4">
                {Object.entries(template.visibility || {}).map(([component, defaultValue]) => (
                  <div key={component} className="flex items-center justify-between">
                    <div className="space-y-0.5">
                      <Label className="text-sm font-medium capitalize">
                        {component.replace(/([A-Z])/g, ' $1').trim()}
                      </Label>
                      <p className="text-sm text-muted-foreground">
                        {defaultValue ? 'Visible by default' : 'Hidden by default'}
                      </p>
                    </div>
                    <Switch
                      checked={localOverrides.componentVisibility?.[component] ?? defaultValue}
                      onCheckedChange={(checked) => handleVisibilityChange(component, checked)}
                    />
                  </div>
                ))}
              </div>
            </CardContent>
          </Card>
        </TabsContent>

        <TabsContent value="header" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>Header Configuration</CardTitle>
              <CardDescription>
                Customize header component settings
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="space-y-4">
                <div className="flex items-center justify-between">
                  <div className="space-y-0.5">
                    <Label className="text-sm font-medium">Show Logo</Label>
                    <p className="text-sm text-muted-foreground">
                      Display the site logo in the header
                    </p>
                  </div>
                  <Switch
                    checked={localOverrides.headerConfig?.showLogo ?? template.componentsConfig?.header?.showLogo ?? true}
                    onCheckedChange={(checked) => handleHeaderConfigChange('showLogo', checked)}
                  />
                </div>
                <Separator />
                <div className="flex items-center justify-between">
                  <div className="space-y-0.5">
                    <Label className="text-sm font-medium">Show Site Title</Label>
                    <p className="text-sm text-muted-foreground">
                      Display the site title in the header
                    </p>
                  </div>
                  <Switch
                    checked={localOverrides.headerConfig?.showSiteTitle ?? template.componentsConfig?.header?.showSiteTitle ?? true}
                    onCheckedChange={(checked) => handleHeaderConfigChange('showSiteTitle', checked)}
                  />
                </div>
                <Separator />
                <div className="flex items-center justify-between">
                  <div className="space-y-0.5">
                    <Label className="text-sm font-medium">Enable Theme Toggle</Label>
                    <p className="text-sm text-muted-foreground">
                      Show dark/light mode toggle button
                    </p>
                  </div>
                  <Switch
                    checked={localOverrides.headerConfig?.enableThemeToggle ?? template.componentsConfig?.header?.enableThemeToggle ?? false}
                    onCheckedChange={(checked) => handleHeaderConfigChange('enableThemeToggle', checked)}
                  />
                </div>
                <Separator />
                <div className="flex items-center justify-between">
                  <div className="space-y-0.5">
                    <Label className="text-sm font-medium">Enable Language Selector</Label>
                    <p className="text-sm text-muted-foreground">
                      Show language selection dropdown
                    </p>
                  </div>
                  <Switch
                    checked={localOverrides.headerConfig?.enableLanguageSelector ?? template.componentsConfig?.header?.enableLanguageSelector ?? true}
                    onCheckedChange={(checked) => handleHeaderConfigChange('enableLanguageSelector', checked)}
                  />
                </div>
                <Separator />
                <div className="flex items-center justify-between">
                  <div className="space-y-0.5">
                    <Label className="text-sm font-medium">Show Auth Buttons</Label>
                    <p className="text-sm text-muted-foreground">
                      Display login/logout buttons
                    </p>
                  </div>
                  <Switch
                    checked={localOverrides.headerConfig?.showAuthButtons ?? template.componentsConfig?.header?.showAuthButtons ?? true}
                    onCheckedChange={(checked) => handleHeaderConfigChange('showAuthButtons', checked)}
                  />
                </div>
                <Separator />
                <div className="flex items-center justify-between">
                  <div className="space-y-0.5">
                    <Label className="text-sm font-medium">Show Greeting</Label>
                    <p className="text-sm text-muted-foreground">
                      Display welcome message for logged-in users
                    </p>
                  </div>
                  <Switch
                    checked={localOverrides.headerConfig?.showGreeting ?? template.componentsConfig?.header?.showGreeting ?? false}
                    onCheckedChange={(checked) => handleHeaderConfigChange('showGreeting', checked)}
                  />
                </div>
              </div>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  )
}
