// frontend/src/lib/components/PhotoLightbox.svelte
<script lang="ts">
	import { createEventDispatcher } from 'svelte';
	import { currentLanguage } from '$stores/language';
	import { MultiLangUtils } from '$utils/multiLang';
	import { logger } from '$lib/utils/logger';

	const dispatch = createEventDispatcher();

	export interface LightboxPhoto {
		_id?: string;
		url?: string;
		thumbnailUrl?: string;
		title?: string | any; // Can be string or multi-language object
		description?: string | any; // Can be string or multi-language HTML object
		takenAt?: string | Date;
		storage?: {
			url?: string;
			thumbnailPath?: string;
		};
		faceRecognition?: {
			faces?: Array<{
				box: { x: number; y: number; width: number; height: number };
				matchedPersonId?: string;
				confidence?: number;
			}>;
		};
		exif?: {
			make?: string;
			model?: string;
			serialNumber?: string;
			dateTime?: string | Date;
			dateTimeOriginal?: string | Date;
			dateTimeDigitized?: string | Date;
			offsetTime?: string;
			offsetTimeOriginal?: string;
			offsetTimeDigitized?: string;
			exposureTime?: string;
			fNumber?: number;
			iso?: number;
			focalLength?: number;
			exposureProgram?: string;
			exposureMode?: string;
			exposureBiasValue?: number;
			maxApertureValue?: number;
			shutterSpeedValue?: string;
			apertureValue?: string;
			whiteBalance?: string;
			meteringMode?: string;
			flash?: string;
			colorSpace?: string;
			customRendered?: string;
			sceneCaptureType?: string;
			xResolution?: number;
			yResolution?: number;
			resolutionUnit?: string;
			focalPlaneXResolution?: number;
			focalPlaneYResolution?: number;
			focalPlaneResolutionUnit?: string;
			lensInfo?: string;
			lensModel?: string;
			lensSerialNumber?: string;
			software?: string;
			copyright?: string;
			exifVersion?: string;
			gps?: {
				latitude?: number;
				longitude?: number;
				altitude?: number;
			};
			recommendedExposureIndex?: number;
			subsecTimeOriginal?: string;
			subsecTimeDigitized?: string;
			gpsLatitude?: number;
			gpsLongitude?: number;
		};
		metadata?: {
			width?: number;
			height?: number;
			fileSize?: number;
			format?: string;
		};
	}

	interface Props {
		photos: LightboxPhoto[];
		initialIndex?: number;
		startIndex?: number;
		isOpen?: boolean;
		autoPlay?: boolean;
		intervalMs?: number;
		onClose?: () => void;
		showExifData?: boolean; // Whether to show EXIF data (defaults to true if not specified)
	}

	let {
		photos,
		initialIndex,
		startIndex,
		isOpen = true,
		autoPlay = false,
		intervalMs = 4000,
		onClose,
		showExifData = true // Default to showing EXIF data if not specified
	}: Props = $props();

	// Support both initialIndex and startIndex for backward compatibility
	let actualIndex = startIndex ?? initialIndex ?? 0;

	let current = $state(initialIndex);
	let playing = $state(autoPlay);
	let showInfo = $state(false);
	let showFaces = $state(false);
	let selectedFaceIndex = $state<number | null>(null);
	let faceData = $state<{
		faces: Array<{
			box: { x: number; y: number; width: number; height: number };
			matchedPersonId?: string;
			confidence?: number;
			personName?: string;
		}>;
		imageSize: { width: number; height: number };
	} | null>(null);

	let touchStart = $state<number | null>(null);
	let touchEnd = $state<number | null>(null);
	let timerRef: ReturnType<typeof setInterval> | null = null;
	let containerRef: HTMLDivElement;
	let imageRef: HTMLImageElement;
	let canvasRef: HTMLCanvasElement;

	// Update current when index changes
	$effect(() => {
		actualIndex = startIndex ?? initialIndex ?? 0;
		current = actualIndex;
	});

	// Fetch face data when photo changes
	$effect(() => {
		if (!isOpen) return;

		// Reset selected face when photo changes
		selectedFaceIndex = null;

		const photo = photos[current];
		if (!photo?._id) {
			const faces = photo?.faceRecognition?.faces;
			if (faces && Array.isArray(faces) && faces.length > 0) {
				// Fetch person names for faces with matchedPersonId
				const fetchFacesWithNames = async () => {
					const facesWithNames = await Promise.all(
						faces.map(async (face: any) => {
							const baseFace = {
								box: face.box,
								matchedPersonId: face.matchedPersonId?.toString(),
								confidence: face.confidence
							};
							
							if (face.matchedPersonId) {
								try {
									const personResponse = await fetch(`/api/people/${face.matchedPersonId}`);
									if (personResponse.ok) {
										const personData = await personResponse.json();
										const person = personData.success ? personData.data : personData;
										const name =
											person.fullName?.en ||
											person.fullName?.he ||
											person.firstName?.en ||
											person.firstName?.he ||
											null;
										return { ...baseFace, personName: name };
									}
								} catch (err) {
									console.debug('Could not fetch person name:', err);
								}
							}
							return baseFace;
						})
					);
					
					faceData = {
						faces: facesWithNames,
						imageSize: { width: 0, height: 0 }
					};
				};
				
				fetchFacesWithNames();
				return;
			}
			faceData = null;
			return;
		}

		const fetchFaceData = async () => {
			try {
				const response = await fetch(`/api/photos/${photo._id}`);
				if (response.ok) {
					const photoData = await response.json();
					if (photoData?.faceRecognition?.faces?.length > 0) {
						const facesWithNames = await Promise.all(
							photoData.faceRecognition.faces.map(async (face: any) => {
								if (face.matchedPersonId) {
									const personName = await fetchPersonName(face.matchedPersonId);
									if (personName) {
										return { ...face, personName };
									}
								}
								return face;
							})
						);
						faceData = {
							faces: facesWithNames,
							imageSize: { width: 0, height: 0 }
						};
					} else {
						faceData = null;
					}
				}
			} catch (error) {
				logger.error('Failed to fetch face data:', error);
				faceData = null;
			}
		};

		fetchFaceData();
	});

	// Draw faces on canvas (only matched faces)
	$effect(() => {
		if (!showFaces || matchedFaces.length === 0 || !imageRef || !canvasRef) return;
		
		// React to selectedFaceIndex changes
		selectedFaceIndex;

		const img = imageRef;
		const canvas = canvasRef;
		const ctx = canvas.getContext('2d');
		if (!ctx) return;

		const drawFaces = () => {
			if (!ctx || !img || !faceData) return;

			ctx.clearRect(0, 0, canvas.width, canvas.height);

			const imgNaturalWidth = img.naturalWidth || faceData.imageSize.width;
			const imgNaturalHeight = img.naturalHeight || faceData.imageSize.height;

			if (!imgNaturalWidth || !imgNaturalHeight) return;

			const displayedWidth = img.offsetWidth;
			const displayedHeight = img.offsetHeight;
			const scaleX = displayedWidth / imgNaturalWidth;
			const scaleY = displayedHeight / imgNaturalHeight;

			// Only draw matched faces
			matchedFaces.forEach((face, index) => {
				const x = face.box.x * scaleX;
				const y = face.box.y * scaleY;
				const width = face.box.width * scaleX;
				const height = face.box.height * scaleY;

				// Use blue border for selected face, green for others
				const isSelected = selectedFaceIndex === index;
				ctx.strokeStyle = isSelected ? '#3b82f6' : '#10b981'; // Blue when selected, green otherwise
				ctx.lineWidth = isSelected ? 3 : 2;
				ctx.strokeRect(x, y, width, height);

				// Show name above the border when face is selected
				if (isSelected) {
					// Get label text - prefer personName, fallback to matchedPersonId
					const labelText = face.personName || (face.matchedPersonId ? `Person ${face.matchedPersonId.slice(-4)}` : 'Unknown');
					
					ctx.font = 'bold 16px sans-serif';
					const textMetrics = ctx.measureText(labelText);
					const labelWidth = textMetrics.width + 12;
					const labelHeight = 24;
					const labelX = x;
					const labelY = Math.max(0, y - labelHeight); // Ensure label doesn't go above canvas
					
					// Draw rounded rectangle background
					ctx.fillStyle = 'rgba(0, 0, 0, 0.8)';
					ctx.beginPath();
					if (ctx.roundRect) {
						ctx.roundRect(labelX, labelY, labelWidth, labelHeight, 4);
					} else {
						// Fallback for browsers that don't support roundRect
						ctx.fillRect(labelX, labelY, labelWidth, labelHeight);
					}
					ctx.fill();
					
					// Draw text
					ctx.fillStyle = '#ffffff';
					ctx.fillText(labelText, labelX + 6, labelY + 17);
				}
			});
		};

		if (!img.complete) {
			img.onload = () => {
				canvas.width = img.offsetWidth;
				canvas.height = img.offsetHeight;
				drawFaces();
			};
		} else {
			canvas.width = img.offsetWidth;
			canvas.height = img.offsetHeight;
			drawFaces();
		}

		const handleResize = () => {
			if (img.complete) {
				canvas.width = img.offsetWidth;
				canvas.height = img.offsetHeight;
				drawFaces();
			}
		};
		window.addEventListener('resize', handleResize);
		return () => window.removeEventListener('resize', handleResize);
	});

	// Keyboard handlers
	$effect(() => {
		if (!isOpen) return;
		const onKey = (e: KeyboardEvent) => {
			if (e.key === 'Escape') {
				if (onClose) onClose();
				dispatch('close');
			}
			if (e.key === 'ArrowRight') next();
			if (e.key === 'ArrowLeft') prev();
			if (e.key === ' ') {
				e.preventDefault();
				playing = !playing;
			}
			if (e.key.toLowerCase() === 'f') toggleFullscreen();
			if (e.key.toLowerCase() === 'i') showInfo = !showInfo;
		};
		window.addEventListener('keydown', onKey);
		return () => window.removeEventListener('keydown', onKey);
	});

	// Auto-play timer
	$effect(() => {
		if (!isOpen) return;
		if (playing) {
			if (timerRef) clearInterval(timerRef);
			timerRef = setInterval(() => {
				next();
			}, intervalMs);
		} else if (timerRef) {
			clearInterval(timerRef);
			timerRef = null;
		}
		return () => {
			if (timerRef) clearInterval(timerRef);
		};
	});

	function next() {
		current = (current + 1) % photos.length;
	}

	function prev() {
		current = (current - 1 + photos.length) % photos.length;
	}

	function handleTouchStart(e: TouchEvent) {
		touchEnd = null;
		touchStart = e.touches[0].clientX;
	}

	function handleTouchMove(e: TouchEvent) {
		touchEnd = e.touches[0].clientX;
	}

	function handleTouchEnd() {
		if (!touchStart || !touchEnd) return;

		const distance = touchStart - touchEnd;
		const isLeftSwipe = distance > 50;
		const isRightSwipe = distance < -50;

		if (isLeftSwipe) {
			next();
		} else if (isRightSwipe) {
			prev();
		}
	}

	async function toggleFullscreen() {
		if (!containerRef) return;
		const doc: any = document;
		const isFs = doc.fullscreenElement || doc.webkitFullscreenElement;
		try {
			if (!isFs) {
				await (containerRef.requestFullscreen?.() || (containerRef as any).webkitRequestFullscreen?.());
			} else {
				await (document.exitFullscreen?.() || (doc as any).webkitExitFullscreen?.());
			}
		} catch {}
	}

	function handleImageLoad() {
		if (faceData && canvasRef && imageRef) {
			canvasRef.width = imageRef.offsetWidth;
			canvasRef.height = imageRef.offsetHeight;
			faceData = {
				...faceData,
				imageSize: { width: imageRef.naturalWidth, height: imageRef.naturalHeight }
			};
		}
	}

	async function fetchPersonName(personId: string): Promise<string | null> {
		try {
			// Try public route first
			let personResponse = await fetch(`/api/people/${personId}`);
			if (!personResponse.ok) {
				// Fallback: try admin route (if user is authenticated)
				personResponse = await fetch(`/api/admin/people/${personId}`);
			}
			
			if (personResponse.ok) {
				const personData = await personResponse.json();
				let person = personData.success ? personData.data : personData;
				
				// Handle array response (from search)
				if (Array.isArray(person) && person.length > 0) {
					person = person.find((p: any) => p._id === personId || p._id?.toString() === personId) || person[0];
				}
				
				// Extract name with better multi-language support
				const extractName = (nameObj: any): string | null => {
					if (!nameObj) return null;
					if (typeof nameObj === 'string') return nameObj;
					if (typeof nameObj === 'object') {
						// Try en first, then he, then any string value
						return nameObj.en || nameObj.he || Object.values(nameObj).find((v: any) => typeof v === 'string' && v.trim() !== '') as string || null;
					}
					return null;
				};
				
				const name = extractName(person.fullName) || extractName(person.firstName);
				if (name) {
					logger.debug(`Fetched person name for ${personId}: ${name}`);
				} else {
					logger.warn(`Person name not found for ${personId}, person data:`, person);
				}
				return name;
			} else {
				logger.warn(`Failed to fetch person ${personId}: ${personResponse.status} ${personResponse.statusText}`);
			}
		} catch (err) {
			logger.error('Could not fetch person name:', err);
		}
		return null;
	}

	async function handleCanvasClick(e: MouseEvent) {
		if (!canvasRef || !imageRef || !faceData || matchedFaces.length === 0) return;

		const canvas = canvasRef;
		const img = imageRef;
		const rect = canvas.getBoundingClientRect();
		
		// Get click coordinates relative to canvas
		const clickX = e.clientX - rect.left;
		const clickY = e.clientY - rect.top;

		// Calculate scale factors
		const imgNaturalWidth = img.naturalWidth || faceData.imageSize.width;
		const imgNaturalHeight = img.naturalHeight || faceData.imageSize.height;
		if (!imgNaturalWidth || !imgNaturalHeight) return;

		const displayedWidth = img.offsetWidth;
		const displayedHeight = img.offsetHeight;
		const scaleX = displayedWidth / imgNaturalWidth;
		const scaleY = displayedHeight / imgNaturalHeight;

		// Convert click coordinates to natural image coordinates
		const naturalX = clickX / scaleX;
		const naturalY = clickY / scaleY;

		// Check if click is on any face (check in reverse order to get topmost face)
		for (let i = matchedFaces.length - 1; i >= 0; i--) {
			const face = matchedFaces[i];
			const box = face.box;
			if (
				naturalX >= box.x &&
				naturalX <= box.x + box.width &&
				naturalY >= box.y &&
				naturalY <= box.y + box.height
			) {
				// If face has matchedPersonId but no personName, fetch it
				if (face.matchedPersonId && !face.personName && faceData) {
					const personName = await fetchPersonName(face.matchedPersonId);
					if (personName) {
						// Find the corresponding face in faceData.faces by matching box coordinates
						const updatedFaces = faceData.faces.map((f) => {
							// Match by box coordinates (within small tolerance) or matchedPersonId
							const boxMatch = Math.abs(f.box.x - box.x) < 1 && 
							                 Math.abs(f.box.y - box.y) < 1 &&
							                 Math.abs(f.box.width - box.width) < 1 &&
							                 Math.abs(f.box.height - box.height) < 1;
							const idMatch = f.matchedPersonId === face.matchedPersonId;
							
							if ((boxMatch || idMatch) && f.matchedPersonId === face.matchedPersonId) {
								return { ...f, personName };
							}
							return f;
						});
						faceData = {
							...faceData,
							faces: updatedFaces
						};
					}
				}
				
				// Toggle selection: if same face clicked, deselect; otherwise select new face
				selectedFaceIndex = selectedFaceIndex === i ? null : i;
				// The $effect will automatically redraw when selectedFaceIndex changes
				return;
			}
		}

		// Click was not on any face, deselect
		selectedFaceIndex = null;
	}

	function formatDate(date: string | Date | undefined): string {
		if (!date) return 'Unknown';
		return new Date(date).toLocaleDateString('en-US', {
			year: 'numeric',
			month: 'long',
			day: 'numeric',
			hour: '2-digit',
			minute: '2-digit'
		});
	}

	let photo = $derived(photos[current]);
	let photoUrl = $derived(photo?.url || photo?.storage?.url || photo?.storage?.thumbnailPath || '');
	let photoTitle = $derived(
		typeof photo?.title === 'string' 
			? photo.title 
			: photo?.title?.en || photo?.title?.he || ''
	);
	let photoDescription = $derived(
		photo?.description
			? typeof photo.description === 'string'
				? photo.description
				: MultiLangUtils.getHTMLValue(photo.description, $currentLanguage) || ''
			: ''
	);
	
	// Only show faces that are matched to a person (have matchedPersonId or personName)
	let matchedFaces = $derived(
		faceData && faceData.faces && Array.isArray(faceData.faces)
			? faceData.faces.filter((face: any) => face.matchedPersonId || face.personName)
			: []
	);
</script>

{#if isOpen}
	<div
		bind:this={containerRef}
		class="fixed inset-0 z-1000 bg-black/95 text-white flex flex-col"
		role="dialog"
		aria-modal="true"
	>
		<!-- Top bar -->
		<div class="flex items-center justify-between px-4 py-2 text-sm">
			<div class="opacity-80">{current + 1} / {photos.length}</div>
			<div class="flex items-center gap-2">
				{#if matchedFaces.length > 0}
					<button
						onclick={() => (showFaces = !showFaces)}
						class="px-2 py-1 rounded hover:bg-white/10"
						aria-label="Toggle Face Detection"
						title="{showFaces ? 'Hide' : 'Show'} detected people"
					>
						{showFaces ? '👤' : '👥'}
					</button>
				{/if}
				<button
					onclick={toggleFullscreen}
					class="px-2 py-1 rounded hover:bg-white/10"
					aria-label="Toggle Fullscreen"
				>
					⛶
				</button>
				<button
					onclick={() => (playing = !playing)}
					class="px-2 py-1 rounded hover:bg-white/10"
					aria-label="Play/Pause"
				>
					{playing ? 'Pause' : 'Play'}
				</button>
				<button
					onclick={() => (showInfo = !showInfo)}
					class="px-2 py-1 rounded hover:bg-white/10"
					aria-label="Toggle Info"
				>
					{showInfo ? '📋' : 'ℹ️'}
				</button>
				<button
					onclick={() => {
						if (onClose) onClose();
						dispatch('close');
					}}
					class="px-2 py-1 rounded hover:bg-white/10"
					aria-label="Close"
				>
					✕
				</button>
			</div>
		</div>

		<!-- Content -->
		<div
			class="flex-1 flex items-center justify-center select-none"
			ontouchstart={handleTouchStart}
			ontouchmove={handleTouchMove}
			ontouchend={handleTouchEnd}
		>
			<button
				onclick={prev}
				class="px-6 py-4 mx-4 rounded-lg hover:bg-white/20 transition-all duration-200 text-4xl font-bold"
				aria-label="Previous"
			>
				‹
			</button>
			<div class="max-h-[85vh] max-w-[92vw] relative flex items-center">
				<div class="relative shrink-0">
					<img
						bind:this={imageRef}
						src={photoUrl}
						alt={photoTitle}
						class="object-contain max-h-[85vh] max-w-[92vw]"
						draggable="false"
						onload={handleImageLoad}
					/>
					{#if showFaces && matchedFaces.length > 0}
						<canvas
							bind:this={canvasRef}
							class="absolute top-0 left-0 cursor-pointer"
							style="max-width: 100%; max-height: 100%;"
							onclick={handleCanvasClick}
						/>
					{/if}
				</div>

				<!-- Info Overlay -->
				{#if showInfo}
					<div
						class="ml-4 bg-black/90 text-white p-4 rounded-lg max-w-[400px] max-h-[85vh] overflow-y-auto z-10 shrink-0"
					>
						<div class="space-y-3">
							<!-- Photo Title -->
							{#if photoTitle}
								<div class="text-lg font-semibold border-b border-white/20 pb-2">{photoTitle}</div>
							{/if}

							<!-- Photo Description -->
							{#if photoDescription}
								<div class="text-sm text-white/90 prose prose-invert prose-sm max-w-none" style="--tw-prose-body: rgba(255, 255, 255, 0.9);">
									{@html photoDescription}
								</div>
							{/if}

							<!-- Basic Info -->
							<div class="grid grid-cols-2 gap-2 text-sm">
								<div class="opacity-60">Photo {current + 1} of {photos.length}</div>
								{#if photo.metadata?.width && photo.metadata?.height}
									<div class="opacity-60">
										{photo.metadata.width} × {photo.metadata.height}
									</div>
								{/if}
							</div>

							<!-- Date/Time -->
							{#if photo.takenAt || photo.exif?.dateTime || photo.exif?.dateTimeOriginal}
								<div class="text-sm">
									<span class="opacity-60">📅 Taken:</span>
									{formatDate(photo.takenAt || photo.exif?.dateTime || photo.exif?.dateTimeOriginal)}
								</div>
							{/if}

							<!-- EXIF Data -->
							{#if showExifData && photo.exif}
								<div class="space-y-3 border-t border-white/20 pt-2">
									<div class="text-sm font-semibold opacity-80">EXIF Data</div>

									<!-- Camera Information -->
									{#if photo.exif.make || photo.exif.model || photo.exif.serialNumber}
										<div class="space-y-1">
											<div class="text-xs font-medium opacity-70">Camera</div>
											{#if photo.exif.make}
												<div class="text-sm"><span class="opacity-60">Make:</span> {photo.exif.make}</div>
											{/if}
											{#if photo.exif.model}
												<div class="text-sm"><span class="opacity-60">Model:</span> {photo.exif.model}</div>
											{/if}
											{#if photo.exif.serialNumber}
												<div class="text-sm">
													<span class="opacity-60">Serial:</span> {photo.exif.serialNumber}
												</div>
											{/if}
										</div>
									{/if}

									<!-- Lens Information -->
									{#if photo.exif.lensModel || photo.exif.lensInfo || photo.exif.lensSerialNumber}
										<div class="space-y-1">
											<div class="text-xs font-medium opacity-70">Lens</div>
											{#if photo.exif.lensModel}
												<div class="text-sm">
													<span class="opacity-60">Model:</span> {photo.exif.lensModel}
												</div>
											{/if}
											{#if photo.exif.lensInfo}
												<div class="text-sm"><span class="opacity-60">Info:</span> {photo.exif.lensInfo}</div>
											{/if}
											{#if photo.exif.lensSerialNumber}
												<div class="text-sm">
													<span class="opacity-60">Serial:</span> {photo.exif.lensSerialNumber}
												</div>
											{/if}
										</div>
									{/if}

									<!-- Exposure Settings -->
									{#if photo.exif.fNumber ||
										photo.exif.exposureTime ||
										photo.exif.iso ||
										photo.exif.focalLength ||
										photo.exif.exposureProgram ||
										photo.exif.exposureMode}
										<div class="space-y-1">
											<div class="text-xs font-medium opacity-70">Exposure</div>
											<div class="grid grid-cols-2 gap-2 text-sm">
												{#if photo.exif.fNumber}
													<div><span class="opacity-60">f/</span>{photo.exif.fNumber}</div>
												{/if}
												{#if photo.exif.exposureTime}
													<div><span class="opacity-60">1/</span>{photo.exif.exposureTime}</div>
												{/if}
												{#if photo.exif.iso}
													<div><span class="opacity-60">ISO</span> {photo.exif.iso}</div>
												{/if}
												{#if photo.exif.focalLength}
													<div><span class="opacity-60">{photo.exif.focalLength}mm</span></div>
												{/if}
											</div>
											{#if photo.exif.exposureProgram}
												<div class="text-sm">
													<span class="opacity-60">Program:</span> {photo.exif.exposureProgram}
												</div>
											{/if}
											{#if photo.exif.exposureMode}
												<div class="text-sm">
													<span class="opacity-60">Mode:</span> {photo.exif.exposureMode}
												</div>
											{/if}
											{#if photo.exif.exposureBiasValue}
												<div class="text-sm">
													<span class="opacity-60">Bias:</span> {photo.exif.exposureBiasValue} EV
												</div>
											{/if}
										</div>
									{/if}

									<!-- Image Quality Settings -->
									{#if photo.exif.whiteBalance ||
										photo.exif.meteringMode ||
										photo.exif.flash ||
										photo.exif.colorSpace}
										<div class="space-y-1">
											<div class="text-xs font-medium opacity-70">Image Quality</div>
											{#if photo.exif.whiteBalance}
												<div class="text-sm">
													<span class="opacity-60">White Balance:</span> {photo.exif.whiteBalance}
												</div>
											{/if}
											{#if photo.exif.meteringMode}
												<div class="text-sm">
													<span class="opacity-60">Metering:</span> {photo.exif.meteringMode}
												</div>
											{/if}
											{#if photo.exif.flash}
												<div class="text-sm">
													<span class="opacity-60">Flash:</span> {photo.exif.flash}
												</div>
											{/if}
											{#if photo.exif.colorSpace}
												<div class="text-sm">
													<span class="opacity-60">Color Space:</span> {photo.exif.colorSpace}
												</div>
											{/if}
											{#if photo.exif.sceneCaptureType}
												<div class="text-sm">
													<span class="opacity-60">Scene:</span> {photo.exif.sceneCaptureType}
												</div>
											{/if}
										</div>
									{/if}

									<!-- GPS Location -->
									{#if (photo.exif.gps?.latitude && photo.exif.gps?.longitude) ||
										(photo.exif.gpsLatitude && photo.exif.gpsLongitude)}
										<div class="space-y-1">
											<div class="text-xs font-medium opacity-70">Location</div>
											<div class="text-sm">
												<span class="opacity-60">📍 GPS:</span>
												{#if photo.exif.gps?.latitude && photo.exif.gps?.longitude}
													{photo.exif.gps.latitude.toFixed(6)}, {photo.exif.gps.longitude.toFixed(6)}
												{:else}
													{photo.exif.gpsLatitude?.toFixed(6)}, {photo.exif.gpsLongitude?.toFixed(6)}
												{/if}
												{#if photo.exif.gps?.altitude}
													({photo.exif.gps.altitude}m)
												{/if}
											</div>
										</div>
									{/if}
								</div>
							{/if}

							<!-- Face Recognition (only show matched people) -->
							{#if matchedFaces.length > 0}
								<div class="space-y-1 border-t border-white/20 pt-2">
									<div class="text-xs font-medium opacity-70">Detected People</div>
									<div class="space-y-1">
										{#each matchedFaces as face, idx}
											<div class="text-sm">
												{#if face.personName}
													<span class="text-green-400">✓ {face.personName}</span>
												{:else if face.matchedPersonId}
													<span class="text-green-400">✓ Person (ID: {face.matchedPersonId})</span>
												{:else}
													<span class="opacity-60">Matched Person {idx + 1}</span>
												{/if}
												{#if face.confidence && face.confidence < 1.0}
													<span class="opacity-60 ml-2">
														({(face.confidence * 100).toFixed(0)}%)
													</span>
												{/if}
											</div>
										{/each}
									</div>
								</div>
							{/if}

							<!-- File Info -->
							{#if photo.metadata}
								<div class="space-y-1 border-t border-white/20 pt-2 text-xs opacity-60">
									{#if photo.metadata.format}
										<div>Format: {photo.metadata.format.toUpperCase()}</div>
									{/if}
									{#if photo.metadata.fileSize}
										<div>Size: {(photo.metadata.fileSize / 1024 / 1024).toFixed(1)} MB</div>
									{/if}
								</div>
							{/if}
						</div>
					</div>
				{/if}
			</div>
			<button
				onclick={next}
				class="px-6 py-4 mx-4 rounded-lg hover:bg-white/20 transition-all duration-200 text-4xl font-bold"
				aria-label="Next"
			>
				›
			</button>
		</div>

		<!-- Hints -->
		<div class="px-4 py-2 text-xs text-white/60">
			Arrow keys to navigate • Space to play/pause • F for fullscreen • I for info • Esc to close • Swipe
			left/right on mobile
		</div>
	</div>
{/if}

// frontend/src/components/PhotoLightbox.tsx
'use client'

import { useEffect, useRef, useState } from 'react'

export interface LightboxPhoto {
  _id: string
  url: string
  thumbnailUrl?: string
  title?: string
  takenAt?: string | Date
  faceRecognition?: {
    faces?: Array<{
      box: { x: number; y: number; width: number; height: number }
      matchedPersonId?: string
      confidence?: number
    }>
  }
  exif?: {
    // Basic Camera Information
    make?: string
    model?: string
    serialNumber?: string
    
    // Date and Time
    dateTime?: string | Date
    dateTimeOriginal?: string | Date
    dateTimeDigitized?: string | Date
    offsetTime?: string
    offsetTimeOriginal?: string
    offsetTimeDigitized?: string
    
    // Camera Settings
    exposureTime?: string
    fNumber?: number
    iso?: number
    focalLength?: number
    exposureProgram?: string
    exposureMode?: string
    exposureBiasValue?: number
    maxApertureValue?: number
    shutterSpeedValue?: string
    apertureValue?: string
    
    // Image Quality
    whiteBalance?: string
    meteringMode?: string
    flash?: string
    colorSpace?: string
    customRendered?: string
    sceneCaptureType?: string
    
    // Resolution
    xResolution?: number
    yResolution?: number
    resolutionUnit?: string
    focalPlaneXResolution?: number
    focalPlaneYResolution?: number
    focalPlaneResolutionUnit?: string
    
    // Lens Information
    lensInfo?: string
    lensModel?: string
    lensSerialNumber?: string
    
    // Software and Processing
    software?: string
    copyright?: string
    exifVersion?: string
    
    // GPS Information
    gps?: {
      latitude?: number
      longitude?: number
      altitude?: number
    }
    
    // Additional Technical Data
    recommendedExposureIndex?: number
    subsecTimeOriginal?: string
    subsecTimeDigitized?: string
    
    // Legacy fields for backward compatibility
    gpsLatitude?: number
    gpsLongitude?: number
  }
  metadata?: {
    width?: number
    height?: number
    fileSize?: number
    format?: string
  }
}

interface PhotoLightboxProps {
  photos: LightboxPhoto[]
  startIndex: number
  isOpen: boolean
  onClose: () => void
  autoPlay?: boolean
  intervalMs?: number
}

export default function PhotoLightbox({
  photos,
  startIndex,
  isOpen,
  onClose,
  autoPlay = false,
  intervalMs = 4000,
}: PhotoLightboxProps) {
  const [current, setCurrent] = useState(startIndex)
  const [playing, setPlaying] = useState(autoPlay)
  const timerRef = useRef<NodeJS.Timeout | null>(null)
  const [touchStart, setTouchStart] = useState<number | null>(null)
  const [touchEnd, setTouchEnd] = useState<number | null>(null)
  const [showInfo, setShowInfo] = useState(false)
  const [showFaces, setShowFaces] = useState(false)
  const [faceData, setFaceData] = useState<{
    faces: Array<{
      box: { x: number; y: number; width: number; height: number }
      matchedPersonId?: string
      confidence?: number
      personName?: string
    }>
    imageSize: { width: number; height: number }
  } | null>(null)
  const imageRef = useRef<HTMLImageElement>(null)
  const canvasRef = useRef<HTMLCanvasElement>(null)

  useEffect(() => {
    setCurrent(startIndex)
  }, [startIndex])

  // Fetch face data when photo changes
  useEffect(() => {
    if (!isOpen) return
    
    const photo = photos[current]
    if (!photo?._id) {
      // Check if face data is already in photo object
      const faces = photo?.faceRecognition?.faces
      if (faces && Array.isArray(faces) && faces.length > 0) {
        setFaceData({
          faces: faces.map((face: any) => ({
            box: face.box,
            matchedPersonId: face.matchedPersonId?.toString(),
            confidence: face.confidence
          })),
          imageSize: { width: 0, height: 0 }
        })
        return
      }
      setFaceData(null)
      return
    }

    const fetchFaceData = async () => {
      try {
        const response = await fetch(`/api/photos/${photo._id}`)
        if (response.ok) {
          const photoData = await response.json()
          if (photoData?.faceRecognition?.faces?.length > 0) {
            // Fetch person names for matched faces (only if authenticated)
            const facesWithNames = await Promise.all(
              photoData.faceRecognition.faces.map(async (face: any) => {
                if (face.matchedPersonId) {
                  try {
                    const personResponse = await fetch(`/api/people/${face.matchedPersonId}`)
                    if (personResponse.ok) {
                      const personData = await personResponse.json()
                      // Note: /api/people is a Next.js route, may still use success wrapper
                      const person = personData.success ? personData.data : personData
                      const name = person.fullName?.en || person.fullName?.he || person.firstName?.en || person.firstName?.he || 'Unknown'
                      return { ...face, personName: name }
                    }
                  } catch (err) {
                    // Silently fail if not authenticated or person not found
                    console.debug('Could not fetch person name:', err)
                  }
                }
                return face
              })
            )
            setFaceData({
              faces: facesWithNames,
              imageSize: { width: 0, height: 0 } // Will be updated when image loads
            })
          } else {
            setFaceData(null)
          }
        }
      } catch (error) {
        console.error('Failed to fetch face data:', error)
        setFaceData(null)
      }
    }

    fetchFaceData()
  }, [current, isOpen, photos])

  // Draw faces on canvas when image loads or face data changes
  useEffect(() => {
    if (!showFaces || !faceData || !imageRef.current || !canvasRef.current) return

    const img = imageRef.current
    const canvas = canvasRef.current
    const ctx = canvas.getContext('2d')
    if (!ctx) return

    // Wait for image to load
    if (!img.complete) {
      img.onload = () => {
        canvas.width = img.offsetWidth
        canvas.height = img.offsetHeight
        drawFaces()
      }
    } else {
      canvas.width = img.offsetWidth
      canvas.height = img.offsetHeight
      drawFaces()
    }

    function drawFaces() {
      if (!ctx || !img || !faceData) return

      ctx.clearRect(0, 0, canvas.width, canvas.height)

      // Get actual image dimensions
      const imgNaturalWidth = img.naturalWidth || faceData.imageSize.width
      const imgNaturalHeight = img.naturalHeight || faceData.imageSize.height
      
      if (!imgNaturalWidth || !imgNaturalHeight) return

      // Calculate scale factors - face boxes are relative to natural image size
      const displayedWidth = img.offsetWidth
      const displayedHeight = img.offsetHeight
      const scaleX = displayedWidth / imgNaturalWidth
      const scaleY = displayedHeight / imgNaturalHeight

      faceData.faces.forEach((face) => {
        const x = face.box.x * scaleX
        const y = face.box.y * scaleY
        const width = face.box.width * scaleX
        const height = face.box.height * scaleY

        // Draw bounding box
        ctx.strokeStyle = face.matchedPersonId ? '#10b981' : '#f59e0b'
        ctx.lineWidth = 2
        ctx.strokeRect(x, y, width, height)

        // Draw label background
        if (face.personName) {
          ctx.fillStyle = 'rgba(0, 0, 0, 0.7)'
          const labelText = face.personName
          ctx.font = '14px sans-serif'
          const textMetrics = ctx.measureText(labelText)
          const labelWidth = textMetrics.width + 8
          const labelHeight = 20
          ctx.fillRect(x, y - labelHeight, labelWidth, labelHeight)

          // Draw label text
          ctx.fillStyle = '#ffffff'
          ctx.fillText(labelText, x + 4, y - 6)
        }
      })
    }

    // Redraw on resize
    const handleResize = () => {
      if (img.complete) {
        canvas.width = img.offsetWidth
        canvas.height = img.offsetHeight
        drawFaces()
      }
    }
    window.addEventListener('resize', handleResize)
    return () => window.removeEventListener('resize', handleResize)
  }, [showFaces, faceData, current])

  useEffect(() => {
    if (!isOpen) return
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose()
      if (e.key === 'ArrowRight') next()
      if (e.key === 'ArrowLeft') prev()
      if (e.key === ' ') {
        e.preventDefault()
        setPlaying(p => !p)
      }
      if (e.key.toLowerCase() === 'f') toggleFullscreen()
      if (e.key.toLowerCase() === 'i') setShowInfo(s => !s)
    }
    window.addEventListener('keydown', onKey)
    return () => window.removeEventListener('keydown', onKey)
  }, [isOpen])

  useEffect(() => {
    if (!isOpen) return
    if (playing) {
      timerRef.current && clearInterval(timerRef.current)
      timerRef.current = setInterval(() => {
        next()
      }, intervalMs)
    } else if (timerRef.current) {
      clearInterval(timerRef.current)
      timerRef.current = null
    }
    return () => {
      if (timerRef.current) clearInterval(timerRef.current)
    }
  }, [playing, intervalMs, isOpen, current])

  const next = () => setCurrent(c => (c + 1) % photos.length)
  const prev = () => setCurrent(c => (c - 1 + photos.length) % photos.length)

  // Touch handlers for swipe navigation
  const handleTouchStart = (e: React.TouchEvent) => {
    setTouchEnd(null)
    setTouchStart(e.targetTouches[0].clientX)
  }

  const handleTouchMove = (e: React.TouchEvent) => {
    setTouchEnd(e.targetTouches[0].clientX)
  }

  const handleTouchEnd = () => {
    if (!touchStart || !touchEnd) return
    
    const distance = touchStart - touchEnd
    const isLeftSwipe = distance > 50
    const isRightSwipe = distance < -50

    if (isLeftSwipe) {
      next()
    } else if (isRightSwipe) {
      prev()
    }
  }

  const containerRef = useRef<HTMLDivElement>(null)
  const toggleFullscreen = async () => {
    const el = containerRef.current
    if (!el) return
    const doc: any = document
    const isFs = doc.fullscreenElement || doc.webkitFullscreenElement
    try {
      if (!isFs) {
        await (el.requestFullscreen?.() || (el as any).webkitRequestFullscreen?.())
      } else {
        await (document.exitFullscreen?.() || (doc as any).webkitExitFullscreen?.())
      }
    } catch {}
  }

  if (!isOpen) return null

  const photo = photos[current]

  return (
    <div
      ref={containerRef}
      className="fixed inset-0 z-1000 bg-black/95 text-white flex flex-col"
      role="dialog"
      aria-modal="true"
    >
      {/* Top bar */}
      <div className="flex items-center justify-between px-4 py-2 text-sm">
        <div className="opacity-80">{current + 1} / {photos.length}</div>
        <div className="flex items-center gap-2">
          {faceData && faceData.faces.length > 0 && (
            <button 
              onClick={() => setShowFaces(s => !s)} 
              className="px-2 py-1 rounded hover:bg-white/10" 
              aria-label="Toggle Face Detection"
              title={`${showFaces ? 'Hide' : 'Show'} detected faces`}
            >
              {showFaces ? '👤' : '👥'}
            </button>
          )}
          <button onClick={toggleFullscreen} className="px-2 py-1 rounded hover:bg-white/10" aria-label="Toggle Fullscreen">⛶</button>
          <button onClick={() => setPlaying(p => !p)} className="px-2 py-1 rounded hover:bg-white/10" aria-label="Play/Pause">
            {playing ? 'Pause' : 'Play'}
          </button>
          <button onClick={() => setShowInfo(s => !s)} className="px-2 py-1 rounded hover:bg-white/10" aria-label="Toggle Info">
            {showInfo ? '📋' : 'ℹ️'}
          </button>
          <button onClick={onClose} className="px-2 py-1 rounded hover:bg-white/10" aria-label="Close">✕</button>
        </div>
      </div>

      {/* Content */}
      <div 
        className="flex-1 flex items-center justify-center select-none"
        onTouchStart={handleTouchStart}
        onTouchMove={handleTouchMove}
        onTouchEnd={handleTouchEnd}
      >
        <button 
          onClick={prev} 
          className="px-6 py-4 mx-4 rounded-lg hover:bg-white/20 transition-all duration-200 text-4xl font-bold" 
          aria-label="Previous"
        >
          ‹
        </button>
        <div className="max-h-[85vh] max-w-[92vw] relative">
          <img
            ref={imageRef}
            src={photo.url}
            alt={photo.title || ''}
            className="object-contain max-h-[85vh] max-w-[92vw]"
            draggable={false}
            onLoad={(e) => {
              const img = e.currentTarget
              if (faceData && canvasRef.current) {
                canvasRef.current.width = img.offsetWidth
                canvasRef.current.height = img.offsetHeight
                setFaceData({
                  ...faceData,
                  imageSize: { width: img.naturalWidth, height: img.naturalHeight }
                })
              }
            }}
          />
          {showFaces && faceData && faceData.faces.length > 0 && (
            <canvas
              ref={canvasRef}
              className="absolute top-0 left-0 pointer-events-none"
              style={{ maxWidth: '100%', maxHeight: '100%' }}
            />
          )}
          
          {/* Info Overlay */}
          {showInfo && (
            <div className="absolute top-0 right-0 bg-black/90 text-white p-4 rounded-l-lg max-w-[400px] max-h-[85vh] overflow-y-auto z-10">
              <div className="space-y-3">
                {/* Photo Title */}
                {photo.title && (
                  <div className="text-lg font-semibold border-b border-white/20 pb-2">{photo.title}</div>
                )}
                
                {/* Basic Info */}
                <div className="grid grid-cols-2 gap-2 text-sm">
                  <div className="opacity-60">Photo {current + 1} of {photos.length}</div>
                  {photo.metadata?.width && photo.metadata?.height && (
                    <div className="opacity-60">{photo.metadata.width} × {photo.metadata.height}</div>
                  )}
                </div>

                {/* Date/Time */}
                {(photo.takenAt || photo.exif?.dateTime || photo.exif?.dateTimeOriginal) && (
                  <div className="text-sm">
                    <span className="opacity-60">📅 Taken:</span> {(() => {
                      const date = photo.takenAt || photo.exif?.dateTime || photo.exif?.dateTimeOriginal
                      if (!date) return 'Unknown'
                      return new Date(date).toLocaleDateString('en-US', {
                        year: 'numeric',
                        month: 'long',
                        day: 'numeric',
                        hour: '2-digit',
                        minute: '2-digit'
                      })
                    })()}
                  </div>
                )}

                {/* EXIF Data */}
                {photo.exif && (
                  <div className="space-y-3 border-t border-white/20 pt-2">
                    <div className="text-sm font-semibold opacity-80">EXIF Data</div>
                    
                    {/* Basic Camera Information */}
                    {(photo.exif.make || photo.exif.model || photo.exif.serialNumber) && (
                      <div className="space-y-1">
                        <div className="text-xs font-medium opacity-70">Camera</div>
                        {photo.exif.make && (
                          <div className="text-sm"><span className="opacity-60">Make:</span> {photo.exif.make}</div>
                        )}
                        {photo.exif.model && (
                          <div className="text-sm"><span className="opacity-60">Model:</span> {photo.exif.model}</div>
                        )}
                        {photo.exif.serialNumber && (
                          <div className="text-sm"><span className="opacity-60">Serial:</span> {photo.exif.serialNumber}</div>
                        )}
                      </div>
                    )}

                    {/* Lens Information */}
                    {(photo.exif.lensModel || photo.exif.lensInfo || photo.exif.lensSerialNumber) && (
                      <div className="space-y-1">
                        <div className="text-xs font-medium opacity-70">Lens</div>
                        {photo.exif.lensModel && (
                          <div className="text-sm"><span className="opacity-60">Model:</span> {photo.exif.lensModel}</div>
                        )}
                        {photo.exif.lensInfo && (
                          <div className="text-sm"><span className="opacity-60">Info:</span> {photo.exif.lensInfo}</div>
                        )}
                        {photo.exif.lensSerialNumber && (
                          <div className="text-sm"><span className="opacity-60">Serial:</span> {photo.exif.lensSerialNumber}</div>
                        )}
                      </div>
                    )}

                    {/* Exposure Settings */}
                    {(photo.exif.fNumber || photo.exif.exposureTime || photo.exif.iso || photo.exif.focalLength || photo.exif.exposureProgram || photo.exif.exposureMode) && (
                      <div className="space-y-1">
                        <div className="text-xs font-medium opacity-70">Exposure</div>
                        <div className="grid grid-cols-2 gap-2 text-sm">
                          {photo.exif.fNumber && (
                            <div><span className="opacity-60">f/</span>{photo.exif.fNumber}</div>
                          )}
                          {photo.exif.exposureTime && (
                            <div><span className="opacity-60">1/</span>{photo.exif.exposureTime}</div>
                          )}
                          {photo.exif.iso && (
                            <div><span className="opacity-60">ISO</span> {photo.exif.iso}</div>
                          )}
                          {photo.exif.focalLength && (
                            <div><span className="opacity-60">{photo.exif.focalLength}mm</span></div>
                          )}
                        </div>
                        {photo.exif.exposureProgram && (
                          <div className="text-sm"><span className="opacity-60">Program:</span> {photo.exif.exposureProgram}</div>
                        )}
                        {photo.exif.exposureMode && (
                          <div className="text-sm"><span className="opacity-60">Mode:</span> {photo.exif.exposureMode}</div>
                        )}
                        {photo.exif.exposureBiasValue && (
                          <div className="text-sm"><span className="opacity-60">Bias:</span> {photo.exif.exposureBiasValue} EV</div>
                        )}
                      </div>
                    )}

                    {/* Image Quality Settings */}
                    {(photo.exif.whiteBalance || photo.exif.meteringMode || photo.exif.flash || photo.exif.colorSpace) && (
                      <div className="space-y-1">
                        <div className="text-xs font-medium opacity-70">Image Quality</div>
                        {photo.exif.whiteBalance && (
                          <div className="text-sm"><span className="opacity-60">White Balance:</span> {photo.exif.whiteBalance}</div>
                        )}
                        {photo.exif.meteringMode && (
                          <div className="text-sm"><span className="opacity-60">Metering:</span> {photo.exif.meteringMode}</div>
                        )}
                        {photo.exif.flash && (
                          <div className="text-sm"><span className="opacity-60">Flash:</span> {photo.exif.flash}</div>
                        )}
                        {photo.exif.colorSpace && (
                          <div className="text-sm"><span className="opacity-60">Color Space:</span> {photo.exif.colorSpace}</div>
                        )}
                        {photo.exif.sceneCaptureType && (
                          <div className="text-sm"><span className="opacity-60">Scene:</span> {photo.exif.sceneCaptureType}</div>
                        )}
                      </div>
                    )}

                    {/* Resolution Information */}
                    {(photo.exif.xResolution || photo.exif.yResolution || photo.exif.resolutionUnit) && (
                      <div className="space-y-1">
                        <div className="text-xs font-medium opacity-70">Resolution</div>
                        {photo.exif.xResolution && photo.exif.yResolution && (
                          <div className="text-sm">
                            <span className="opacity-60">DPI:</span> {photo.exif.xResolution} × {photo.exif.yResolution}
                            {photo.exif.resolutionUnit && ` ${photo.exif.resolutionUnit}`}
                          </div>
                        )}
                      </div>
                    )}

                    {/* Software and Processing */}
                    {(photo.exif.software || photo.exif.copyright || photo.exif.exifVersion) && (
                      <div className="space-y-1">
                        <div className="text-xs font-medium opacity-70">Processing</div>
                        {photo.exif.software && (
                          <div className="text-sm"><span className="opacity-60">Software:</span> {photo.exif.software}</div>
                        )}
                        {photo.exif.copyright && (
                          <div className="text-sm"><span className="opacity-60">Copyright:</span> {photo.exif.copyright}</div>
                        )}
                        {photo.exif.exifVersion && (
                          <div className="text-sm"><span className="opacity-60">EXIF Version:</span> {photo.exif.exifVersion}</div>
                        )}
                      </div>
                    )}

                    {/* GPS Location */}
                    {((photo.exif.gps?.latitude && photo.exif.gps?.longitude) || (photo.exif.gpsLatitude && photo.exif.gpsLongitude)) && (
                      <div className="space-y-1">
                        <div className="text-xs font-medium opacity-70">Location</div>
                        <div className="text-sm">
                          <span className="opacity-60">📍 GPS:</span> {
                            photo.exif.gps?.latitude && photo.exif.gps?.longitude 
                              ? `${photo.exif.gps.latitude.toFixed(6)}, ${photo.exif.gps.longitude.toFixed(6)}`
                              : `${photo.exif.gpsLatitude?.toFixed(6)}, ${photo.exif.gpsLongitude?.toFixed(6)}`
                          }
                          {photo.exif.gps?.altitude && ` (${photo.exif.gps.altitude}m)`}
                        </div>
                      </div>
                    )}

                    {/* Additional Technical Data */}
                    {(photo.exif.recommendedExposureIndex || photo.exif.subsecTimeOriginal || photo.exif.subsecTimeDigitized) && (
                      <div className="space-y-1">
                        <div className="text-xs font-medium opacity-70">Technical</div>
                        {photo.exif.recommendedExposureIndex && (
                          <div className="text-sm"><span className="opacity-60">REI:</span> {photo.exif.recommendedExposureIndex}</div>
                        )}
                        {photo.exif.subsecTimeOriginal && (
                          <div className="text-sm"><span className="opacity-60">Subsec Original:</span> {photo.exif.subsecTimeOriginal}</div>
                        )}
                        {photo.exif.subsecTimeDigitized && (
                          <div className="text-sm"><span className="opacity-60">Subsec Digitized:</span> {photo.exif.subsecTimeDigitized}</div>
                        )}
                      </div>
                    )}
                  </div>
                )}

                    {/* Face Recognition */}
                    {faceData && faceData.faces.length > 0 && (
                      <div className="space-y-1 border-t border-white/20 pt-2">
                        <div className="text-xs font-medium opacity-70">Detected People</div>
                        <div className="space-y-1">
                          {faceData.faces.map((face, idx) => (
                            <div key={idx} className="text-sm">
                              {face.personName ? (
                                <span className="text-green-400">✓ {face.personName}</span>
                              ) : (
                                <span className="opacity-60">Face {idx + 1} (unidentified)</span>
                              )}
                              {face.confidence && face.confidence < 1.0 && (
                                <span className="opacity-60 ml-2">
                                  ({(face.confidence * 100).toFixed(0)}%)
                                </span>
                              )}
                            </div>
                          ))}
                        </div>
                      </div>
                    )}

                    {/* File Info */}
                {photo.metadata && (
                  <div className="space-y-1 border-t border-white/20 pt-2 text-xs opacity-60">
                    {photo.metadata.format && <div>Format: {photo.metadata.format.toUpperCase()}</div>}
                    {photo.metadata.fileSize && (
                      <div>Size: {(photo.metadata.fileSize / 1024 / 1024).toFixed(1)} MB</div>
                    )}
                  </div>
                )}
              </div>
            </div>
          )}
        </div>
        <button 
          onClick={next} 
          className="px-6 py-4 mx-4 rounded-lg hover:bg-white/20 transition-all duration-200 text-4xl font-bold" 
          aria-label="Next"
        >
          ›
        </button>
      </div>

      {/* Hints */}
      <div className="px-4 py-2 text-xs text-white/60">
        Arrow keys to navigate • Space to play/pause • F for fullscreen • I for info • Esc to close • Swipe left/right on mobile
      </div>
    </div>
  )
}
