// frontend/src/lib/templates/modern/Gallery.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { currentLanguage } from '$stores/language';
	import { MultiLangUtils } from '$utils/multiLang';
	import Header from '$components/Header.svelte';
	import Footer from '$components/Footer.svelte';

	interface TemplateAlbum {
		_id: string;
		name: any;
		description?: any;
		alias: string;
		photoCount?: number;
		childAlbumCount?: number;
		coverPhotoId?: string;
	}

	interface TemplatePhoto {
		_id: string;
		url?: string;
		storage?: {
			url?: string;
			thumbnailPath?: string;
		};
	}

	let albums: TemplateAlbum[] = [];
	let loading = true;
	let error: string | null = null;
	let coverPhotos: Record<string, TemplatePhoto> = {};

	async function fetchCoverPhoto(albumId: string, coverPhotoId: string) {
		try {
			const response = await fetch(`/api/photos/${coverPhotoId}`);
			if (response.ok) {
				const photo = await response.json();
				coverPhotos = { ...coverPhotos, [albumId]: photo };
			}
		} catch (error) {
			console.error(`Failed to fetch cover photo for album ${albumId}:`, error);
		}
	}

	async function fetchRootAlbums() {
		try {
			loading = true;
			const response = await fetch('/api/albums?parentId=root');
			if (!response.ok) {
				throw new Error('Failed to fetch albums');
			}
			const albumsData = await response.json();
			if (Array.isArray(albumsData)) {
				albums = albumsData.sort((a: TemplateAlbum, b: TemplateAlbum) => (a.order || 0) - (b.order || 0));
				albums.forEach((album: TemplateAlbum) => {
					if (album.coverPhotoId) {
						fetchCoverPhoto(album._id, album.coverPhotoId);
					}
				});
			} else {
				error = 'Failed to fetch albums';
			}
		} catch (err) {
			console.error('Failed to fetch albums:', err);
			error = 'Failed to fetch albums';
		} finally {
			loading = false;
		}
	}

	onMount(() => {
		fetchRootAlbums();
	});
</script>

<Header />

{#if loading}
	<div class="min-h-screen bg-gray-50 flex items-center justify-center">
		<div class="text-center">
			<div class="w-16 h-16 border-4 border-blue-600 border-t-transparent rounded-full animate-spin mx-auto mb-4"></div>
			<div class="text-gray-600">Loading gallery...</div>
		</div>
	</div>
{:else}
	<main class="flex-1 min-h-screen bg-gray-50">
		{#if error}
			<section class="py-8">
				<div class="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
					<div class="text-gray-600 mb-4">{error}</div>
				</div>
			</section>
		{:else if albums.length === 0}
			<section class="py-12">
				<div class="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
					<div class="text-gray-600 mb-4">No albums found. Create your first album to get started!</div>
					<a href="/albums/new" class="inline-block px-6 py-3 bg-blue-600 text-white rounded-md hover:bg-blue-700">
						Create New Album
					</a>
				</div>
			</section>
		{:else}
			<section class="py-8">
				<div class="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
					<div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
						{#each albums as album}
							<a href={`/albums/${album.alias}`} class="group">
								<div class="bg-white rounded-lg shadow-sm hover:shadow-md transition-shadow overflow-hidden h-full flex flex-col">
									<div class="aspect-[4/3] bg-gray-100 flex items-center justify-center overflow-hidden flex-shrink-0">
										{#if album.coverPhotoId && coverPhotos[album._id]}
											<img
												src={coverPhotos[album._id].storage?.thumbnailPath ||
													coverPhotos[album._id].url ||
													'/placeholder.jpg'}
												alt={MultiLangUtils.getTextValue(album.name, $currentLanguage)}
												class="w-full h-full object-cover group-hover:scale-105 transition-transform"
											/>
										{:else}
											<div class="text-4xl text-gray-400">📷</div>
										{/if}
									</div>
									<div class="p-4 flex flex-col flex-grow">
										<h3 class="text-lg font-semibold text-gray-900 group-hover:text-blue-600 mb-2">
											{MultiLangUtils.getTextValue(album.name, $currentLanguage) || album.alias || 'Untitled Album'}
										</h3>
										<div class="text-sm text-gray-500 mb-2">
											{#if album.photoCount && album.photoCount > 0}
												{album.photoCount} photos
											{/if}
											{#if album.photoCount && album.photoCount > 0 && album.childAlbumCount && album.childAlbumCount > 0}
												•
											{/if}
											{#if album.childAlbumCount && album.childAlbumCount > 0}
												{album.childAlbumCount} sub-albums
											{/if}
											{#if (!album.photoCount || album.photoCount === 0) && (!album.childAlbumCount || album.childAlbumCount === 0)}
												Empty album
											{/if}
										</div>
										{#if album.description}
											<div
												class="text-sm text-gray-600 flex-grow line-clamp-2"
												{@html MultiLangUtils.getHTMLValue(album.description, $currentLanguage) || ''}
											></div>
										{/if}
									</div>
								</div>
							</a>
						{/each}
					</div>
				</div>
			</section>
		{/if}
	</main>
{/if}

<Footer />

// frontend/src/templates/modern/pages/Gallery.tsx
'use client'

import { useState, useEffect } from 'react'
import Image from 'next/image'
import Link from 'next/link'
import ProgressiveImage from '@/components/ProgressiveImage'
import { useSiteConfig } from '@/hooks/useSiteConfig'
import { MultiLangUtils } from '@/types/multi-lang'
import { useLanguage } from '@/contexts/LanguageContext'
import { useI18n } from '@/hooks/useI18n'
import { TemplateAlbum, TemplatePhoto } from '@/types'
import Header from '../components/Header'
import Footer from '../components/Footer'
import styles from '../styles.module.scss'

export default function GalleryPage() {
  const { config, loading: configLoading } = useSiteConfig()
  const { currentLanguage } = useLanguage()
  const { t } = useI18n()
  const [albums, setAlbums] = useState<TemplateAlbum[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [coverPhotos, setCoverPhotos] = useState<Record<string, TemplatePhoto>>({})

  // Function to fetch cover photo for an album
  const fetchCoverPhoto = async (albumId: string, coverPhotoId: string) => {
    try {
      const response = await fetch(`/api/photos/${coverPhotoId}`)
      if (response.ok) {
        const photo = await response.json()
        setCoverPhotos(prev => ({
          ...prev,
          [albumId]: photo
        }))
      }
    } catch (error) {
      console.error(`Failed to fetch cover photo for album ${albumId}:`, error)
    }
  }

  useEffect(() => {
    const fetchRootAlbums = async () => {
      try {
        setLoading(true)
        // Fetch only root albums (no parent) - API handles access control
        const response = await fetch('/api/albums?parentId=root')
        
        if (!response.ok) {
          throw new Error('Failed to fetch albums')
        }
        
        const albums = await response.json()
        // Backend returns array directly
        if (Array.isArray(albums)) {
          
          // Debug: Log album data to see what we're getting
          console.log('Albums data:', albums)
          
          // API already handles access control, so we can use all returned albums
          const sortedAlbums = albums.sort((a: TemplateAlbum, b: TemplateAlbum) => a.order - b.order)
          setAlbums(sortedAlbums)
          
          // Fetch cover photos for albums that have them
          sortedAlbums.forEach((album: TemplateAlbum) => {
            if (album.coverPhotoId) {
              fetchCoverPhoto(album._id, album.coverPhotoId)
            }
          })
        } else {
          console.error('API returned unexpected format:', albums)
          setError('Failed to fetch albums')
        }
      } catch (error) {
        console.error('Failed to fetch albums:', error)
        setError('Failed to fetch albums')
      } finally {
        setLoading(false)
      }
    }

    fetchRootAlbums()
  }, [])

  // Show loading state while config or albums are loading
  if (configLoading || loading) {
    return (
      <div className={`min-h-screen ${styles.theme}`}>
        <Header />
        <div className="flex-1 flex items-center justify-center">
          <div className="text-center">
            <div className={`w-16 h-16 ${styles.loading} rounded-full mx-auto mb-4`}></div>
            <div className={styles.textSecondary}>Loading gallery...</div>
          </div>
        </div>
        <Footer />
      </div>
    )
  }

  return (
    <div className={`min-h-screen ${styles.theme}`}>
      <Header />
      
      <main className="flex-1">

        {/* Error State */}
        {error && (
          <section className={styles.section}>
            <div className="max-w-6xl mx-auto text-center">
              <div className={`${styles.textSecondary} mb-4`}>
                {error}
              </div>
            </div>
          </section>
        )}

        {/* Gallery Grid */}
        <section className={styles.gallery}>
          <div className={styles.galleryGrid}>
            {albums.length > 0 ? (
              albums.map((album, i) => (
                <Link key={album._id} href={`/albums/${album.alias}`}>
                  <div className={`${styles.card} ${styles.animateScaleIn} h-full flex flex-col`} style={{ animationDelay: `${i * 0.1}s` }}>
                    <div className="overflow-hidden flex-shrink-0">
                      {album.coverPhotoId && coverPhotos[album._id] ? (
                        <ProgressiveImage
                          photo={coverPhotos[album._id]}
                          alt={MultiLangUtils.getTextValue(album.name, currentLanguage)}
                          width={400}
                          height={300}
                          className={styles.cardImage}
                          sizes="(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 33vw"
                          loading="lazy"
                          fetchPriority="low"
                          useOptimalDimensions={true}
                        />
                      ) : null}
                      <div 
                        className={`${styles.cardImage} ${styles.bgSecondary} flex items-center justify-center`}
                        style={{ display: (album.coverPhotoId && coverPhotos[album._id]) ? 'none' : 'flex' }}
                      >
                        <div className="text-4xl text-gray-400">📷</div>
                      </div>
                    </div>
                    <div className="p-4 flex flex-col flex-grow">
                      <h3 className={`${styles.heading3} mb-2`}>
                        {album.name 
                          ? MultiLangUtils.getTextValue(album.name, currentLanguage)
                          : album.alias || 'Untitled Album'}
                      </h3>
                      <div className={`${styles.textSecondary} text-sm mb-2`}>
                        {album.photoCount > 0 && (
                          <span>{album.photoCount} photos</span>
                        )}
                        {album.photoCount > 0 && album.childAlbumCount && album.childAlbumCount > 0 && (
                          <span> • </span>
                        )}
                        {album.childAlbumCount && album.childAlbumCount > 0 && (
                          <span>{album.childAlbumCount} sub-albums</span>
                        )}
                        {album.photoCount === 0 && (!album.childAlbumCount || album.childAlbumCount === 0) && (
                          <span>Empty album</span>
                        )}
                      </div>
                      {album.description && (
                        <div 
                          className={`${styles.textSecondary} text-sm flex-grow`}
                          dangerouslySetInnerHTML={{
                            __html: MultiLangUtils.getHTMLValue(album.description, currentLanguage)
                          }}
                        />
                      )}
                    </div>
                  </div>
                </Link>
              ))
            ) : !loading && !error && (
              <div className="col-span-full text-center py-12">
                <div className={`${styles.textSecondary} mb-4`}>
                  No albums found. Create your first album to get started!
                </div>
                <Link href="/albums/new" className={styles.button}>
                  Create New Album
                </Link>
              </div>
            )}
          </div>
        </section>

        {/* Call to Action - Commented out */}
        {/* <section className={`${styles.section} ${styles.bgSecondary}`}>
          <div className="max-w-4xl mx-auto text-center">
            <h2 className={`${styles.sectionTitle} ${styles.animateFadeInUp}`}>
              Ready to Create Your Own Gallery?
            </h2>
            <p className={`${styles.sectionContent} ${styles.animateFadeIn}`} style={{ animationDelay: '0.2s' }}>
              Join thousands of photographers who trust OpenShutter to showcase their work
            </p>
            <div className={styles.animateFadeIn} style={{ animationDelay: '0.4s' }}>
              <Link href="/albums/new" className={styles.button}>
                Create New Album
              </Link>
            </div>
          </div>
        </section> */}
      </main>
      
      <Footer />
    </div>
  )
}
