// src/app/admin/albums/[id]/page.tsx
'use client'

import { useState, useEffect } from 'react'
import { use } from 'react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import AdminGuard from '@/components/AdminGuard'
import { MultiLangUtils } from '@/types/multi-lang'
import { useLanguage } from '@/contexts/LanguageContext'
import ConfirmDialog from '@/components/ConfirmDialog'
import { TemplateAlbum, TemplatePhoto } from '@/types'

export default function AdminAlbumDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { currentLanguage } = useLanguage()
  const resolvedParams = use(params)
  const router = useRouter()
  const [album, setAlbum] = useState<TemplateAlbum | null>(null)
  const [photos, setPhotos] = useState<TemplatePhoto[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [showDeleteDialog, setShowDeleteDialog] = useState(false)
  const [deletingPhoto, setDeletingPhoto] = useState<string | null>(null)

  useEffect(() => {
    const fetchAlbum = async () => {
      try {
        setLoading(true)
        const response = await fetch(`/api/albums/${resolvedParams.id}`)
        if (!response.ok) {
          throw new Error('Failed to fetch album')
        }
        
        const result = await response.json()
        if (result.success) {
          setAlbum(result.data)
        } else {
          setError(result.error || 'Failed to fetch album')
        }
      } catch (error) {
        console.error('Failed to fetch album:', error)
        setError('Failed to fetch album')
      } finally {
        setLoading(false)
      }
    }

    const fetchPhotos = async () => {
      try {
        const response = await fetch(`/api/albums/${resolvedParams.id}/photos`)
        if (response.ok) {
          const result = await response.json()
          if (result.success) {
            setPhotos(result.data)
          }
        }
      } catch (error) {
        console.error('Failed to fetch photos:', error)
      }
    }

    fetchAlbum()
    fetchPhotos()
  }, [resolvedParams.id])

  const handleDeletePhoto = async (photoId: string) => {
    try {
      setDeletingPhoto(photoId)
      const response = await fetch(`/api/photos/${photoId}`, {
        method: 'DELETE',
      })

      if (response.ok) {
        setPhotos(photos.filter(photo => photo._id !== photoId))
        if (album) {
          setAlbum({ ...album, photoCount: album.photoCount - 1 })
        }
      } else {
        setError('Failed to delete photo')
      }
    } catch (error) {
      console.error('Failed to delete photo:', error)
      setError('Failed to delete photo')
    } finally {
      setDeletingPhoto(null)
      setShowDeleteDialog(false)
    }
  }

  const handleDeleteAlbum = async () => {
    try {
      const response = await fetch(`/api/albums/${resolvedParams.id}`, {
        method: 'DELETE',
      })

      if (response.ok) {
        router.push('/admin/albums')
      } else {
        setError('Failed to delete album')
      }
    } catch (error) {
      console.error('Failed to delete album:', error)
      setError('Failed to delete album')
    }
  }

  if (loading) {
    return (
      <AdminGuard>
        <div className="min-h-screen bg-gray-50">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
            <div className="text-center">
              <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600 mx-auto"></div>
              <p className="mt-4 text-gray-600">Loading album...</p>
            </div>
          </div>
        </div>
      </AdminGuard>
    )
  }

  if (error || !album) {
    return (
      <AdminGuard>
        <div className="min-h-screen bg-gray-50">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
            <div className="text-center">
              <h1 className="text-2xl font-bold text-gray-900 mb-4">Error</h1>
              <p className="text-gray-600 mb-4">{error || 'Album not found'}</p>
              <Link href="/admin/albums" className="btn-primary">
                Back to Albums
              </Link>
            </div>
          </div>
        </div>
      </AdminGuard>
    )
  }

  return (
    <AdminGuard>
      <div className="min-h-screen bg-gray-50">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
          {/* Header */}
          <div className="flex items-center justify-between mb-8">
            <div>
              <h1 className="text-3xl font-bold text-gray-900">{MultiLangUtils.getTextValue(album.name as any, currentLanguage)}</h1>
              {album.description && (
                <div
                  className="mt-2 text-gray-600 prose max-w-none"
                  dangerouslySetInnerHTML={{ __html: MultiLangUtils.getHTMLValue(album.description as any, currentLanguage) }}
                />
              )}
            </div>
            <div className="flex space-x-3">
              <Link href="/admin/albums" className="btn-secondary">
                Back to Albums
              </Link>
              <Link href={`/admin/albums/${resolvedParams.id}/edit`} className="btn-primary">
                Edit Album
              </Link>
              <button
                onClick={() => setShowDeleteDialog(true)}
                className="btn-danger"
              >
                Delete Album
              </button>
            </div>
          </div>

          {/* Album Info */}
          <div className="bg-white rounded-lg shadow-md p-6 mb-8">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              <div>
                <h3 className="text-lg font-semibold text-gray-900 mb-2">Album Details</h3>
                <div className="space-y-2 text-sm text-gray-600">
                  <p><span className="font-medium">Alias:</span> {album.alias}</p>
                  <p><span className="font-medium">Photos:</span> {album.photoCount}</p>
                  <p><span className="font-medium">Created:</span> {new Date(album.createdAt).toLocaleDateString()}</p>
                  <p><span className="font-medium">Updated:</span> {new Date(album.updatedAt).toLocaleDateString()}</p>
                </div>
              </div>
              <div>
                <h3 className="text-lg font-semibold text-gray-900 mb-2">Status</h3>
                <div className="space-y-2">
                  <span className={`inline-flex items-center px-2 py-1 rounded-full text-xs font-medium ${
                    album.isPublic ? 'bg-green-100 text-green-800' : 'bg-gray-100 text-gray-800'
                  }`}>
                    {album.isPublic ? 'Public' : 'Private'}
                  </span>
                  {album.isFeatured && (
                    <span className="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-yellow-100 text-yellow-800">
                      Featured
                    </span>
                  )}
                </div>
              </div>
              <div>
                <h3 className="text-lg font-semibold text-gray-900 mb-2">Actions</h3>
                <div className="space-y-2">
                  <Link href={`/albums/${album.alias}`} className="btn-secondary w-full text-center">
                    View Public Page
                  </Link>
                                     <Link href={`/admin/photos/upload?albumId=${resolvedParams.id}`} className="btn-primary w-full text-center">
                     Upload Photos
                   </Link>
                </div>
              </div>
            </div>
          </div>

          {/* Photos Grid */}
          <div className="bg-white rounded-lg shadow-md p-6">
            <div className="flex items-center justify-between mb-6">
              <h2 className="text-2xl font-bold text-gray-900">Photos ({photos.length})</h2>
              <Link href={`/admin/photos/upload?albumId=${resolvedParams.id}`} className="btn-primary">
                Upload Photos
              </Link>
            </div>

            {photos.length === 0 ? (
              <div className="text-center py-12">
                <svg className="mx-auto h-12 w-12 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
                </svg>
                <h3 className="mt-2 text-sm font-medium text-gray-900">No photos</h3>
                <p className="mt-1 text-sm text-gray-500">Get started by uploading some photos to this album.</p>
                <div className="mt-6">
                  <Link href={`/admin/photos/upload?albumId=${resolvedParams.id}`} className="btn-primary">
                    Upload Photos
                  </Link>
                </div>
              </div>
            ) : (
              <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
                {photos.map((photo) => (
                  <div key={photo._id} className="relative group">
                    <div className="aspect-w-1 aspect-h-1 bg-gray-200 rounded-lg overflow-hidden">
                      <img
                        src={photo.storage.thumbnailPath || photo.storage.url}
                        alt={typeof photo.title === 'string' ? photo.title : photo.title.en}
                        className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300"
                        onError={(e) => {
                          e.currentTarget.style.display = 'none'
                          const fallback = e.currentTarget.nextElementSibling
                          if (fallback) {
                            fallback.classList.remove('hidden')
                            fallback.classList.add('flex')
                          }
                        }}
                      />
                      <div className="absolute inset-0 items-center justify-center bg-gray-100 hidden">
                        <svg className="w-8 h-8 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
                        </svg>
                      </div>
                    </div>
                    
                    {/* Photo Info */}
                    <div className="mt-2">
                      <h3 className="text-sm font-medium text-gray-900 truncate">
                        {typeof photo.title === 'string' ? photo.title : photo.title.en}
                      </h3>
                      {(photo.metadata || photo.dimensions) && (
                        <p className="text-xs text-gray-500">
                          {(photo.metadata?.width || photo.dimensions?.width) || 0} × {(photo.metadata?.height || photo.dimensions?.height) || 0}
                        </p>
                      )}
                      {/* EXIF Date */}
                      {photo.exif?.dateTimeOriginal && (
                        <p className="text-xs text-gray-400 mt-1">
                          📅 {new Date(photo.exif.dateTimeOriginal).toLocaleDateString()}
                        </p>
                      )}
                    </div>

                    {/* Action Buttons */}
                    <div className="absolute top-2 right-2 opacity-0 group-hover:opacity-100 transition-opacity duration-200">
                      <div className="flex space-x-1">
                        <Link
                          href={`/admin/photos/${photo._id}/edit`}
                          className="p-1 bg-blue-600 text-white rounded-full hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500"
                          title="Edit photo"
                        >
                          <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
                          </svg>
                        </Link>
                        <button
                          onClick={() => handleDeletePhoto(photo._id)}
                          className="p-1 bg-red-600 text-white rounded-full hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-500"
                          title="Delete photo"
                          disabled={deletingPhoto === photo._id}
                        >
                          {deletingPhoto === photo._id ? (
                            <svg className="w-4 h-4 animate-spin" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
                            </svg>
                          ) : (
                            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                            </svg>
                          )}
                        </button>
                      </div>
                    </div>

                    {/* Status Badges */}
                    <div className="absolute top-2 left-2">
                      <div className="flex space-x-1">
                        {photo.isGalleryLeading && (
                          <span className="inline-flex items-center px-1 py-0.5 rounded text-xs font-medium bg-purple-100 text-purple-800">
                            Gallery Hero
                          </span>
                        )}
                        {photo.isLeading && (
                          <span className="inline-flex items-center px-1 py-0.5 rounded text-xs font-medium bg-blue-100 text-blue-800">
                            Leading
                          </span>
                        )}
                        {photo.isPublished ? (
                          <span className="inline-flex items-center px-1 py-0.5 rounded text-xs font-medium bg-green-100 text-green-800">
                            Published
                          </span>
                        ) : (
                          <span className="inline-flex items-center px-1 py-0.5 rounded text-xs font-medium bg-gray-100 text-gray-800">
                            Draft
                          </span>
                        )}
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Delete Confirmation Dialog */}
      <ConfirmDialog
        isOpen={showDeleteDialog}
        onCancel={() => setShowDeleteDialog(false)}
        onConfirm={handleDeleteAlbum}
        title="Delete Album"
        message={`Are you sure you want to delete "${MultiLangUtils.getTextValue(album.name as any, currentLanguage)}"? This action cannot be undone and will also delete all photos in this album.`}
        confirmText="Delete Album"
        variant="danger"
      />
    </AdminGuard>
  )
}

// frontend/src/routes/admin/albums/[id]/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { page } from '$app/stores';
	import { goto } from '$app/navigation';
	import { currentLanguage } from '$stores/language';
	import { MultiLangUtils } from '$utils/multiLang';
	import AlbumBreadcrumbs from '$lib/components/AlbumBreadcrumbs.svelte';
	import ConfirmDialog from '$lib/components/ConfirmDialog.svelte';
	import { getPhotoUrl } from '$lib/utils/photoUrl';
	import { getAlbumName } from '$lib/utils/albumUtils';
	import { getPhotoTitle } from '$lib/utils/photoUtils';
	import { logger } from '$lib/utils/logger';
	import { handleError, handleApiErrorResponse } from '$lib/utils/errorHandler';

  export const data = undefined as any; // From +layout.server.ts, not used in this component

	interface Album {
		_id: string;
		name: string | { en?: string; he?: string };
		description?: string | { en?: string; he?: string };
		alias: string;
		level: number;
		isFeatured: boolean;
		isPublic: boolean;
		photoCount: number;
		coverPhotoId?: string;
		parentAlbumId?: string;
		storagePath: string;
	}

	interface Photo {
		_id: string;
		title?: string | { en?: string; he?: string };
		filename: string;
		url?: string;
		storage?: {
			provider?: string;
			url?: string;
			path?: string;
			thumbnailPath?: string;
			thumbnails?: Record<string, string>;
		};
		isPublished: boolean;
	}

	const albumId = $page.params.id;
	let album: Album | null = null;
	let photos: Photo[] = [];
	let loading = true;
	let error = '';
	let successMessage = '';
	let showDeleteDialog = false;
	let photoDeleteDialog: {
		isOpen: boolean;
		photoId: string | null;
		photoTitle: string;
		isDeleting: boolean;
	} = {
		isOpen: false,
		photoId: null,
		photoTitle: '',
		isDeleting: false,
	};
	
	// Bulk operations
	let selectedPhotoIds = new Set<string>();
	let showBulkActions = false;
	let showLocationDialog = false;
	let locations: any[] = [];
	let selectedLocationId: string | null = null;
	let isBulkUpdating = false;

	// Album and photo utility functions are now imported from shared utilities

	// Photo URL function is now imported from shared utility
	// Using empty string fallback for admin pages (as per original implementation)

	async function loadAlbum() {
		try {
			loading = true;
			error = '';
			const response = await fetch(`/api/admin/albums/${albumId}?t=${Date.now()}`, {
				cache: 'no-store',
			});
			if (!response.ok) {
				await handleApiErrorResponse(response);
			}
			const result = await response.json();
			album = result.data || result;
		} catch (err) {
			logger.error('Failed to fetch album:', err);
			error = handleError(err, 'Failed to load album');
		} finally {
			loading = false;
		}
	}

	async function loadPhotos() {
		try {
			const response = await fetch(`/api/admin/albums/${albumId}/photos?t=${Date.now()}`, {
				cache: 'no-store',
			});
			logger.debug('Photos API response status:', response.status);
			
			if (!response.ok) {
				await handleApiErrorResponse(response);
			}
			
			const result = await response.json();
			logger.debug('Photos API result:', result);
			if (result.success) {
				photos = result.data || [];
				logger.debug(`Loaded ${photos.length} photos`);
				if (photos.length > 0) {
					logger.debug('Sample photo:', {
						_id: photos[0]._id,
						filename: photos[0].filename,
						hasStorage: !!photos[0].storage,
						storage: photos[0].storage,
						thumbnailPath: photos[0].storage?.thumbnailPath,
						url: photos[0].storage?.url,
						constructedUrl: getPhotoUrl(photos[0], { fallback: '' }),
					});
				}
			} else {
				throw new Error(result.error || 'Failed to load photos');
			}
		} catch (err) {
			logger.error('Failed to fetch photos:', err);
			error = handleError(err, 'Failed to fetch photos');
		}
	}

	function openPhotoDeleteDialog(photo: Photo) {
		photoDeleteDialog = {
			isOpen: true,
			photoId: photo._id,
			photoTitle: getPhotoTitle(photo),
			isDeleting: false,
		};
	}

	function closePhotoDeleteDialog() {
		// Create a new object to ensure reactivity
		photoDeleteDialog = {
			isOpen: false,
			photoId: null,
			photoTitle: '',
			isDeleting: false,
		};
	}

	async function confirmDeletePhoto() {
		if (!photoDeleteDialog.photoId || photoDeleteDialog.isDeleting) return;

		// Save values before any async operations
		const deletedPhotoId = photoDeleteDialog.photoId;
		const photoTitle = photoDeleteDialog.photoTitle;

		// Update isDeleting by creating a new object to ensure reactivity
		photoDeleteDialog = {
			...photoDeleteDialog,
			isDeleting: true,
		};
		error = '';
		successMessage = '';

		try {
			logger.debug('[confirmDeletePhoto] Deleting photo:', deletedPhotoId);
			const response = await fetch(`/api/admin/photos/${deletedPhotoId}`, {
				method: 'DELETE',
			});

			logger.debug('[confirmDeletePhoto] Response status:', response.status, response.statusText);

			let result: any = {};
			try {
				result = await response.json();
				logger.debug('[confirmDeletePhoto] Response data:', result);
			} catch (parseError) {
				logger.warn('[confirmDeletePhoto] Failed to parse JSON response:', parseError);
			}

			if (response.ok && (result.success !== false)) {
				// Photo deleted successfully
				logger.debug('[confirmDeletePhoto] Photo deleted successfully, closing dialog');
				
				// Close dialog immediately
				closePhotoDeleteDialog();
				
				// Remove photo from local array immediately for better UX
				photos = photos.filter((p) => p._id !== deletedPhotoId);
				
				// Show success message
				successMessage = `Photo "${photoTitle}" deleted successfully`;
				
				// Clear success message after 3 seconds
				setTimeout(() => {
					successMessage = '';
				}, 3000);
				
				// Reload album and photos to update counts
				await Promise.all([loadAlbum(), loadPhotos()]);
			} else {
				const errorMsg = result.error || result.message || `Failed to delete photo (${response.status})`;
				error = errorMsg;
				// Update isDeleting by creating a new object
				photoDeleteDialog = {
					...photoDeleteDialog,
					isDeleting: false,
				};
				logger.error('[confirmDeletePhoto] Delete failed:', errorMsg);
			}
		} catch (err) {
			logger.error('[confirmDeletePhoto] Exception during delete:', err);
			error = handleError(err, 'Failed to delete photo');
			// Update isDeleting by creating a new object
			photoDeleteDialog = {
				...photoDeleteDialog,
				isDeleting: false,
			};
		}
	}

	async function deleteAlbum() {
		showDeleteDialog = false;
		error = '';
		
		const deleteUrl = `/api/admin/albums/${albumId}`;
		logger.debug('[deleteAlbum] Deleting album:', albumId, 'URL:', deleteUrl);
		
		try {
			const response = await fetch(deleteUrl, { method: 'DELETE' });
			logger.debug('[deleteAlbum] Response status:', response.status, response.statusText);
			
			if (response.ok) {
				logger.debug('[deleteAlbum] Album deleted successfully, redirecting...');
				goto('/admin/albums');
			} else {
				const errorText = await response.text();
				logger.error('[deleteAlbum] Delete failed:', response.status, errorText);
				
				let errorData: any = {};
				try {
					errorData = JSON.parse(errorText);
				} catch (parseError) {
					logger.warn('[deleteAlbum] Failed to parse error response as JSON');
				}
				
				error = errorData.error || errorData.message || `Failed to delete album (${response.status} ${response.statusText})`;
			}
		} catch (err) {
			logger.error('[deleteAlbum] Exception during delete:', err);
			error = handleError(err, 'Failed to delete album');
		}
	}

	function togglePhotoSelection(photoId: string) {
		if (selectedPhotoIds.has(photoId)) {
			selectedPhotoIds.delete(photoId);
		} else {
			selectedPhotoIds.add(photoId);
		}
		selectedPhotoIds = selectedPhotoIds; // Trigger reactivity
		showBulkActions = selectedPhotoIds.size > 0;
	}

	function toggleSelectAll() {
		if (selectedPhotoIds.size === photos.length) {
			selectedPhotoIds.clear();
		} else {
			selectedPhotoIds = new Set(photos.map(p => p._id));
		}
		selectedPhotoIds = selectedPhotoIds; // Trigger reactivity
		showBulkActions = selectedPhotoIds.size > 0;
	}

	async function loadLocations() {
		try {
			const response = await fetch('/api/admin/locations?limit=1000');
			if (response.ok) {
				const result = await response.json();
				locations = Array.isArray(result.data) ? result.data : [];
			}
		} catch (err) {
			logger.error('Failed to load locations:', err);
		}
	}

	async function bulkUpdatePhotos(updates: { isPublished?: boolean; location?: string | null }) {
		if (selectedPhotoIds.size === 0 || isBulkUpdating) return;

		isBulkUpdating = true;
		error = '';
		successMessage = '';

		try {
			const response = await fetch('/api/admin/photos/bulk-update', {
				method: 'POST',
				headers: { 'Content-Type': 'application/json' },
				body: JSON.stringify({
					photoIds: Array.from(selectedPhotoIds),
					updates
				})
			});

			const result = await response.json();

			if (result.success) {
				successMessage = result.data?.message || `Updated ${selectedPhotoIds.size} photo(s)`;
				selectedPhotoIds.clear();
				showBulkActions = false;
				showLocationDialog = false;
				selectedLocationId = null;
				
				// Reload photos to reflect changes
				await loadPhotos();
				
				setTimeout(() => {
					successMessage = '';
				}, 3000);
			} else {
				error = result.error || 'Failed to update photos';
			}
		} catch (err) {
			logger.error('Bulk update failed:', err);
			error = `Failed to update photos: ${err instanceof Error ? err.message : 'Unknown error'}`;
		} finally {
			isBulkUpdating = false;
		}
	}

	function openLocationDialog() {
		showLocationDialog = true;
		if (locations.length === 0) {
			loadLocations();
		}
	}

	function applyLocation() {
		if (selectedLocationId !== null) {
			bulkUpdatePhotos({ location: selectedLocationId });
		}
	}

	onMount(async () => {
		await Promise.all([loadAlbum(), loadPhotos()]);
	});
</script>

<svelte:head>
	<title>{album ? getAlbumName(album) : 'Album'} - Admin</title>
</svelte:head>

{#if loading}
	<div class="min-h-screen bg-gray-50 flex items-center justify-center">
		<div class="text-center">
			<div class="inline-block animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600"></div>
			<p class="mt-4 text-gray-600">Loading album...</p>
		</div>
	</div>
{:else if error || !album}
	<div class="min-h-screen bg-gray-50 flex items-center justify-center">
		<div class="text-center">
			<h1 class="text-2xl font-bold text-gray-900 mb-4">Error</h1>
			<p class="text-gray-600 mb-4">{error || 'Album not found'}</p>
			<a href="/admin/albums" class="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700">
				Back to Albums
			</a>
		</div>
	</div>
{:else}
	<div class="min-h-screen bg-gray-50 py-8">
		<div class="max-w-7xl mx-auto px-4">
			<!-- Breadcrumbs -->
			{#if album}
				<AlbumBreadcrumbs album={album} role="admin" />
			{/if}

			<!-- Header -->
			<div class="mb-6">
				<div class="flex items-center justify-between">
					<div>
						<h1 class="text-3xl font-bold text-gray-900">{getAlbumName(album)}</h1>
						<p class="mt-2 text-gray-600">
							{album.photoCount || 0} photos • {album.isPublic ? 'Public' : 'Private'}
							{#if album.isFeatured}
								• ⭐ Featured
							{/if}
						</p>
					</div>
					<div class="flex gap-3">
						<a
							href="/admin/photos/upload?albumId={albumId}"
							class="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700"
						>
							Upload Photos
						</a>
						<a
							href="/albums/new?parentAlbumId={albumId}"
							class="px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700"
						>
							Create Sub-Album
						</a>
						<a
							href="/admin/albums/{albumId}/edit"
							class="px-4 py-2 bg-gray-600 text-white rounded-md hover:bg-gray-700"
						>
							Edit Album
						</a>
						<button
							on:click={() => (showDeleteDialog = true)}
							class="px-4 py-2 bg-red-600 text-white rounded-md hover:bg-red-700"
						>
							Delete Album
						</button>
						<a href="/admin/albums" class="px-4 py-2 text-gray-700 bg-gray-100 rounded-md hover:bg-gray-200">
							← Back
						</a>
					</div>
				</div>
			</div>

			{#if error}
				<div class="mb-4 p-4 rounded-md bg-red-50 text-red-700 text-sm">{error}</div>
			{/if}

			{#if successMessage}
				<div class="mb-4 p-4 rounded-md bg-green-50 text-green-700 text-sm">{successMessage}</div>
			{/if}

			<!-- Album Description -->
			{#if album.description}
				<div class="mb-6 p-4 bg-white rounded-lg shadow-sm border border-gray-200">
					{@html MultiLangUtils.getHTMLValue(album.description, $currentLanguage) || ''}
				</div>
			{/if}

			<!-- Photos Grid -->
			<div class="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
				<div class="flex items-center justify-between mb-6">
					<h2 class="text-2xl font-bold text-gray-900">
						Photos ({photos.length}
						{#if album && album.photoCount !== photos.length}
							<span class="text-sm font-normal text-gray-500">
								/ {album.photoCount} total
							</span>
						{/if})
					</h2>
					{#if photos.length > 0}
						<div class="flex items-center gap-2">
							<button
								on:click={toggleSelectAll}
								class="px-3 py-1 text-sm text-gray-700 bg-gray-100 rounded-md hover:bg-gray-200"
							>
								{selectedPhotoIds.size === photos.length ? 'Deselect All' : 'Select All'}
							</button>
						</div>
					{/if}
				</div>

				{#if showBulkActions}
					<div class="mb-4 p-4 bg-blue-50 border border-blue-200 rounded-lg">
						<div class="flex items-center justify-between">
							<span class="text-sm font-medium text-blue-900">
								{selectedPhotoIds.size} photo{selectedPhotoIds.size === 1 ? '' : 's'} selected
							</span>
							<div class="flex gap-2">
								<button
									on:click={() => bulkUpdatePhotos({ isPublished: true })}
									disabled={isBulkUpdating}
									class="px-3 py-1 text-sm bg-green-600 text-white rounded-md hover:bg-green-700 disabled:opacity-50"
								>
									Publish
								</button>
								<button
									on:click={() => bulkUpdatePhotos({ isPublished: false })}
									disabled={isBulkUpdating}
									class="px-3 py-1 text-sm bg-yellow-600 text-white rounded-md hover:bg-yellow-700 disabled:opacity-50"
								>
									Unpublish
								</button>
								<button
									on:click={openLocationDialog}
									disabled={isBulkUpdating}
									class="px-3 py-1 text-sm bg-blue-600 text-white rounded-md hover:bg-blue-700 disabled:opacity-50"
								>
									Set Location
								</button>
								<button
									on:click={() => { selectedPhotoIds.clear(); showBulkActions = false; }}
									class="px-3 py-1 text-sm bg-gray-600 text-white rounded-md hover:bg-gray-700"
								>
									Cancel
								</button>
							</div>
						</div>
					</div>
				{/if}

				{#if photos.length === 0}
					<div class="text-center py-12">
						<svg
							class="mx-auto h-12 w-12 text-gray-400"
							fill="none"
							viewBox="0 0 24 24"
							stroke="currentColor"
						>
							<path
								stroke-linecap="round"
								stroke-linejoin="round"
								stroke-width="2"
								d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z"
							/>
						</svg>
						<h3 class="mt-2 text-sm font-medium text-gray-900">No photos yet</h3>
						<p class="mt-1 text-sm text-gray-500">Upload photos to get started</p>
						<div class="mt-6">
							<a
								href="/admin/photos/upload?albumId={albumId}"
								class="inline-flex items-center px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700"
							>
								Upload Photos
							</a>
						</div>
					</div>
				{:else}
					<div class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-6 gap-4">
						{#each photos as photo}
							{@const photoUrl = getPhotoUrl(photo, { fallback: '' })}
							{@const isSelected = selectedPhotoIds.has(photo._id)}
							<div class="relative group">
								{#if showBulkActions}
									<div class="absolute top-2 left-2 z-10">
										<input
											type="checkbox"
											checked={isSelected}
											on:change={() => togglePhotoSelection(photo._id)}
											class="w-5 h-5 text-blue-600 border-gray-300 rounded focus:ring-blue-500"
										/>
									</div>
								{/if}
								<div class="aspect-square bg-gray-200 rounded-lg overflow-hidden {isSelected ? 'ring-4 ring-blue-500' : ''}">
									{#if photoUrl}
										<img
											src={photoUrl}
											alt={getPhotoTitle(photo)}
											class="w-full h-full object-cover"
											style="image-orientation: from-image;"
											on:error={(e) => {
												logger.debug('Image failed to load:', photoUrl, photo);
												const target = e.currentTarget as HTMLImageElement;
												target.style.display = 'none';
											}}
											on:load={() => {
												logger.debug('Image loaded successfully:', photoUrl);
											}}
										/>
									{:else}
										<div class="w-full h-full flex items-center justify-center">
											<svg class="w-12 h-12 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
												<path
													stroke-linecap="round"
													stroke-linejoin="round"
													stroke-width="2"
													d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z"
												/>
											</svg>
										</div>
									{/if}
								</div>
								<div
									class="absolute inset-0 bg-black bg-opacity-0 group-hover:bg-opacity-50 transition-opacity rounded-lg flex items-center justify-center opacity-0 group-hover:opacity-100"
								>
									<div class="flex gap-2">
										<a
											href="/admin/photos/{photo._id}/edit"
											class="px-3 py-1 bg-blue-600 text-white text-sm rounded hover:bg-blue-700"
										>
											Edit
										</a>
										<button
											on:click={() => openPhotoDeleteDialog(photo)}
											disabled={photoDeleteDialog.isDeleting}
											class="px-3 py-1 bg-red-600 text-white text-sm rounded hover:bg-red-700 disabled:opacity-50"
										>
											Delete
										</button>
									</div>
								</div>
								{#if !photo.isPublished}
									<div class="absolute top-2 right-2">
										<span
											class="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-yellow-100 text-yellow-800"
										>
											Draft
										</span>
									</div>
								{/if}
							</div>
						{/each}
					</div>
				{/if}
			</div>
		</div>
	</div>
{/if}

<!-- Delete Album Confirmation Dialog -->
{#if album}
	<ConfirmDialog
		isOpen={showDeleteDialog}
		title="Delete Album"
		message="Are you sure you want to delete &quot;{getAlbumName(album)}&quot;? This action cannot be undone and will also delete all photos in this album."
		confirmText="Delete Album"
		cancelText="Cancel"
		variant="danger"
		on:confirm={deleteAlbum}
		on:cancel={() => (showDeleteDialog = false)}
	/>
{/if}

<!-- Delete Photo Confirmation Dialog -->
<ConfirmDialog
	isOpen={photoDeleteDialog.isOpen}
	title="Delete Photo"
	message="Are you sure you want to delete &quot;{photoDeleteDialog.photoTitle}&quot;? This action cannot be undone."
	confirmText={photoDeleteDialog.isDeleting ? 'Deleting...' : 'Delete'}
	cancelText="Cancel"
	variant="danger"
	disabled={photoDeleteDialog.isDeleting}
	on:confirm={confirmDeletePhoto}
	on:cancel={closePhotoDeleteDialog}
/>

<!-- Location Selection Dialog -->
{#if showLocationDialog}
	<div class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
		<div class="bg-white rounded-lg p-6 max-w-md w-full mx-4">
			<h3 class="text-lg font-semibold mb-4">Set Location for {selectedPhotoIds.size} Photo{selectedPhotoIds.size === 1 ? '' : 's'}</h3>
			<div class="mb-4">
				<label for="location-select" class="block text-sm font-medium text-gray-700 mb-2">
					Select Location
				</label>
				<select
					id="location-select"
					bind:value={selectedLocationId}
					class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500"
				>
					<option value="">No Location</option>
					{#each locations as location}
						<option value={location._id}>
							{typeof location.name === 'string' 
								? location.name 
								: MultiLangUtils.getTextValue(location.name, $currentLanguage) || location.address || 'Unnamed Location'}
						</option>
					{/each}
				</select>
			</div>
			<div class="flex justify-end gap-2">
				<button
					on:click={() => { showLocationDialog = false; selectedLocationId = null; }}
					class="px-4 py-2 text-gray-700 bg-gray-100 rounded-md hover:bg-gray-200"
				>
					Cancel
				</button>
				<button
					on:click={applyLocation}
					disabled={isBulkUpdating}
					class="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 disabled:opacity-50"
				>
					{isBulkUpdating ? 'Applying...' : 'Apply'}
				</button>
			</div>
		</div>
	</div>
{/if}
