// frontend/src/routes/[alias]/+page.svelte
<script lang="ts">
	import { page } from '$app/stores';
	import { goto } from '$app/navigation';
	import { onMount } from 'svelte';

	// Known routes that should not be handled here
	const knownRoutes = ['admin', 'api', 'login', 'albums', 'photos', 'owner', 'page'];

	onMount(() => {
		const alias = $page.params.alias;
		
		// Skip if it's a known route
		if (knownRoutes.includes(alias)) {
			return;
		}
		
		// Redirect to query parameter format
		goto(`/page?alias=${encodeURIComponent(alias)}`, { replaceState: true });
	});
</script>

<!-- This page will redirect immediately, so no content needed -->

// frontend/src/app/[alias]/page.tsx
import { redirect } from 'next/navigation'

interface PageProps {
  params: Promise<{ alias: string }>
}

export default async function AliasPage({ params }: PageProps) {
  const { alias } = await params
  
  // Skip if it's a known route
  const knownRoutes = ['admin', 'api', 'login', 'albums', 'photos', 'owner', 'page']
  if (knownRoutes.includes(alias)) {
    return null
  }
  
  // Redirect to query parameter format
  redirect(`/page?alias=${encodeURIComponent(alias)}`)
}
