// frontend/src/routes/owner/blog/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { goto } from '$app/navigation';
import { MultiLangUtils } from '$lib/utils/multiLang';
import { currentLanguage } from '$lib/stores/language';
import { logger } from '$lib/utils/logger';
import { handleError, handleApiErrorResponse } from '$lib/utils/errorHandler';
import { t } from '$stores/i18n';
	import type { PageData } from './$types';

	let { data }: { data: PageData } = $props();

	interface BlogArticle {
		_id: string;
		title: string | { en?: string; he?: string };
		category: string;
		isPublished: boolean;
		createdAt: string;
		viewCount?: number;
		leadingImage?: {
			url: string;
			
		};
	}

	let articles: BlogArticle[] = [];
	let loading = true;
	let error: string | null = null;
	let searchTerm = '';
	let categoryFilter = '';
	let statusFilter = '';
	let categories: string[] = [];

	onMount(async () => {
		await fetchArticles();
	});

	async function fetchArticles() {
		try {
			loading = true;
			const params = new URLSearchParams();
			if (searchTerm) params.append('search', searchTerm);
			if (categoryFilter) params.append('category', categoryFilter);
			if (statusFilter) params.append('isPublished', statusFilter);

			const response = await fetch(`/api/owner/blog?${params.toString()}`);
			if (!response.ok) {
				await handleApiErrorResponse(response);
			}

			const result = await response.json();
			if (result.success) {
				articles = result.data || [];
				const uniqueCategories = [
					...new Set(articles.map((article: BlogArticle) => article.category))
				] as string[];
				categories = uniqueCategories;
			}
		} catch (err) {
			logger.error('Failed to fetch articles:', err);
			error = handleError(err, $t('owner.requestFailed'));
		} finally {
			loading = false;
		}
	}

	async function handleDelete(articleId: string) {
		if (!confirm($t('owner.confirmDeleteArticle'))) return;

		try {
			const response = await fetch(`/api/owner/blog/${articleId}`, {
				method: 'DELETE'
			});

			if (!response.ok) {
				await handleApiErrorResponse(response);
			}

			articles = articles.filter((article) => article._id !== articleId);
		} catch (err) {
			logger.error('Failed to delete article:', err);
			error = handleError(err, $t('owner.failedToDelete'));
		}
	}

	async function handleTogglePublish(article: BlogArticle) {
		try {
			const response = await fetch(`/api/owner/blog/${article._id}`, {
				method: 'PUT',
				headers: {
					'Content-Type': 'application/json'
				},
				body: JSON.stringify({
					...article,
					isPublished: !article.isPublished
				})
			});

			if (!response.ok) {
				throw new Error($t('owner.failedToUpdate'));
			}

			const result = await response.json();
			if (result.success) {
				articles = articles.map((a) =>
					a._id === article._id ? { ...a, isPublished: !a.isPublished } : a
				);
			}
		} catch (err) {
			error = err instanceof Error ? err.message : $t('owner.failedToUpdate');
		}
	}
</script>

<svelte:head>
	<title>{$t('owner.blogManagement')} - {$t('owner.ownerPanel')}</title>
</svelte:head>

{#if loading}
	<div class="min-h-screen bg-gray-50 flex items-center justify-center">
		<div class="text-center">
			<div class="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600 mx-auto"></div>
			<p class="mt-4 text-gray-600">{$t('loading.loading')}</p>
		</div>
	</div>
{:else}
	<div class="min-h-screen bg-gray-50 py-8">
		<div class="max-w-6xl mx-auto px-4">
			<!-- Header -->
			<div class="flex justify-between items-center mb-8">
				<div>
					<h1 class="text-3xl font-bold text-gray-900">{$t('owner.blogManagement')}</h1>
					<p class="text-gray-600 mt-2">{$t('owner.manageYourBlogArticles')}</p>
				</div>
				<div class="flex space-x-3">
					<button
						onclick={() => goto('/owner/blog/new')}
						class="inline-flex items-center px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700"
					>
						<svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
							<path
								stroke-linecap="round"
								stroke-linejoin="round"
								stroke-width="2"
								d="M12 4v16m8-8H4"
							/>
						</svg>
						{$t('owner.createNewArticle')}
					</button>
					<button
						onclick={() => goto('/owner')}
						class="inline-flex items-center px-4 py-2 bg-gray-600 text-white rounded-md hover:bg-gray-700"
					>
						<svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
							<path
								stroke-linecap="round"
								stroke-linejoin="round"
								stroke-width="2"
								d="M10 19l-7-7m0 0l7-7m-7 7h18"
							/>
						</svg>
						{$t('owner.backToDashboard')}
					</button>
				</div>
			</div>

			<!-- Filters -->
			<div class="bg-white rounded-lg shadow-md p-6 mb-6">
				<div class="grid grid-cols-1 md:grid-cols-3 gap-4">
					<div>
						<label for="search" class="block text-sm font-medium text-gray-700 mb-2">
							{$t('owner.searchArticles')}
						</label>
						<input
							type="text"
							id="search"
							bind:value={searchTerm}
							class="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
							placeholder={$t('owner.searchPlaceholder')}
						/>
					</div>
					<div>
						<label for="category" class="block text-sm font-medium text-gray-700 mb-2">
							{$t('owner.category')}
						</label>
						<select
							id="category"
							bind:value={categoryFilter}
							class="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
						>
							<option value="">{ $t('owner.allCategories') }</option>
							{#each categories as category}
								<option value={category}>{category}</option>
							{/each}
						</select>
					</div>
					<div>
						<label for="status" class="block text-sm font-medium text-gray-700 mb-2">
							{$t('owner.status')}
						</label>
						<select
							id="status"
							bind:value={statusFilter}
							class="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
						>
							<option value="">{ $t('owner.allStatuses') }</option>
							<option value="true">{ $t('owner.published') }</option>
							<option value="false">{ $t('owner.draft') }</option>
						</select>
					</div>
				</div>
				<div class="mt-4">
					<button
						onclick={fetchArticles}
						class="inline-flex items-center px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700"
					>
						<svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
							<path
								stroke-linecap="round"
								stroke-linejoin="round"
								stroke-width="2"
								d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"
							/>
						</svg>
						{$t('owner.filter')}
					</button>
				</div>
			</div>

			<!-- Error Message -->
			{#if error}
				<div class="mb-6 bg-red-50 border border-red-200 rounded-md p-4">
					<p class="text-sm text-red-800">{error}</p>
				</div>
			{/if}

			<!-- Articles List -->
			<div class="bg-white rounded-lg shadow-md">
				{#if articles.length === 0}
					<div class="text-center py-12">
						<svg
							class="mx-auto h-12 w-12 text-gray-400"
							fill="none"
							stroke="currentColor"
							viewBox="0 0 24 24"
						>
							<path
								stroke-linecap="round"
								stroke-linejoin="round"
								stroke-width="2"
								d="M19 20H5a2 2 0 01-2-2V6a2 2 0 012-2h10a2 2 0 012 2v1m2 13a2 2 0 01-2-2V7m2 13a2 2 0 002-2V9a2 2 0 00-2-2h-2m-4-3H9M7 16h6M7 8h6v4H7V8z"
							/>
						</svg>
						<h3 class="mt-2 text-sm font-medium text-gray-900">{$t('owner.noArticles')}</h3>
						<p class="mt-1 text-sm text-gray-500">
							{$t('owner.getStartedByCreatingArticle')}
						</p>
						<div class="mt-6">
							<button
								onclick={() => goto('/owner/blog/new')}
								class="inline-flex items-center px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700"
							>
								<svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
									<path
										stroke-linecap="round"
										stroke-linejoin="round"
										stroke-width="2"
										d="M12 4v16m8-8H4"
									/>
								</svg>
								{$t('owner.createNewArticle')}
							</button>
						</div>
					</div>
				{:else}
					<div class="overflow-hidden">
						<table class="min-w-full divide-y divide-gray-200">
							<thead class="bg-gray-50">
								<tr>
									<th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
										Title
									</th>
									<th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
										Category
									</th>
									<th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
										Status
									</th>
									<th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
										Created
									</th>
									<th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
										Views
									</th>
									<th class="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">
										Actions
									</th>
								</tr>
							</thead>
							<tbody class="bg-white divide-y divide-gray-200">
								{#each articles as article}
									<tr class="hover:bg-gray-50">
										<td class="px-6 py-4 whitespace-nowrap">
											<div class="flex items-center">
												<div class="shrink-0 h-10 w-10">
													{#if article.leadingImage}
														<img
															class="h-10 w-10 rounded-lg object-cover"
															src={article.leadingImage.url}
															alt={MultiLangUtils.getTextValue(article.leadingImage.alt, $currentLanguage)}
														/>
													{:else}
														<div
															class="h-10 w-10 rounded-lg bg-gray-200 flex items-center justify-center"
														>
															<svg
																class="h-6 w-6 text-gray-400"
																fill="none"
																stroke="currentColor"
																viewBox="0 0 24 24"
															>
																<path
																	stroke-linecap="round"
																	stroke-linejoin="round"
																	stroke-width="2"
																	d="M19 20H5a2 2 0 01-2-2V6a2 2 0 012-2h10a2 2 0 012 2v1m2 13a2 2 0 01-2-2V7m2 13a2 2 0 002-2V9a2 2 0 00-2-2h-2m-4-3H9M7 16h6M7 8h6v4H7V8z"
																/>
															</svg>
														</div>
													{/if}
												</div>
												<div class="ml-4">
													<div class="text-sm font-medium text-gray-900">
														{MultiLangUtils.getTextValue(article.title, $currentLanguage)}
													</div>
												</div>
											</div>
										</td>
										<td class="px-6 py-4 whitespace-nowrap">
											<span
												class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-blue-100 text-blue-800"
											>
												{article.category}
											</span>
										</td>
										<td class="px-6 py-4 whitespace-nowrap">
											<span
												class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium {article.isPublished
													? 'bg-green-100 text-green-800'
													: 'bg-yellow-100 text-yellow-800'}"
											>
												{article.isPublished ? 'Published' : 'Draft'}
											</span>
										</td>
										<td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
											{new Date(article.createdAt).toLocaleDateString()}
										</td>
										<td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
											{article.viewCount || 0}
										</td>
										<td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
											<div class="flex justify-end space-x-2">
												<button
													onclick={() => handleTogglePublish(article)}
													class="{article.isPublished
														? 'text-yellow-600 hover:text-yellow-900'
														: 'text-green-600 hover:text-green-900'}"
												>
													{article.isPublished ? 'Unpublish' : 'Publish'}
												</button>
												<button
													onclick={() => handleDelete(article._id)}
													class="text-red-600 hover:text-red-900"
												>
													Delete
												</button>
											</div>
										</td>
									</tr>
								{/each}
							</tbody>
						</table>
					</div>
				{/if}
			</div>
		</div>
	</div>
{/if}

// src/app/owner/blog/page.tsx
'use client'

import { useState, useEffect } from 'react'
import { useSession } from 'next-auth/react'
import { useI18n } from '@/hooks/useI18n'
import { useLanguage } from '@/contexts/LanguageContext'
import { MultiLangUtils } from '@/types/multi-lang'
import Link from 'next/link'
import { BlogArticle } from '@/types'

export default function OwnerBlogPage() {
  const { t } = useI18n()
  const { isRTL, currentLanguage } = useLanguage()
  const { data: session } = useSession()
  const [articles, setArticles] = useState<BlogArticle[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [searchTerm, setSearchTerm] = useState('')
  const [categoryFilter, setCategoryFilter] = useState('')
  const [statusFilter, setStatusFilter] = useState('')
  const [categories, setCategories] = useState<string[]>([])

  useEffect(() => {
    fetchArticles()
  }, [])

  const fetchArticles = async () => {
    try {
      setLoading(true)
      const params = new URLSearchParams()
      if (searchTerm) params.append('search', searchTerm)
      if (categoryFilter) params.append('category', categoryFilter)
      if (statusFilter) params.append('isPublished', statusFilter)
      
      const response = await fetch(`/api/owner/blog?${params.toString()}`)
      if (!response.ok) {
        throw new Error('Failed to fetch articles')
      }
      
      const data = await response.json()
      if (data.success) {
        setArticles(data.data)
        
        // Extract unique categories
        const uniqueCategories = [...new Set(data.data.map((article: BlogArticle) => article.category))] as string[]
        setCategories(uniqueCategories)
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'An error occurred')
    } finally {
      setLoading(false)
    }
  }

  const handleDelete = async (articleId: string) => {
    if (!confirm(t('owner.confirmDeleteArticle'))) return
    
    try {
      const response = await fetch(`/api/owner/blog/${articleId}`, {
        method: 'DELETE'
      })
      
      if (!response.ok) {
        throw new Error('Failed to delete article')
      }
      
      setArticles(articles.filter(article => article._id !== articleId))
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to delete article')
    }
  }

  const handleTogglePublish = async (article: BlogArticle) => {
    try {
      const response = await fetch(`/api/owner/blog/${article._id}`, {
        method: 'PUT',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          ...article,
          isPublished: !article.isPublished
        })
      })
      
      if (!response.ok) {
        throw new Error('Failed to update article')
      }
      
      const data = await response.json()
      if (data.success) {
        setArticles(articles.map(a => 
          a._id === article._id ? { ...a, isPublished: !a.isPublished } : a
        ))
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to update article')
    }
  }

  const getArrowPath = () => isRTL ? "M15 19l-7-7 7-7" : "M9 5l7 7-7 7"

  if (loading) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary-600 mx-auto"></div>
          <p className="mt-4 text-gray-600">{t('loading.loading')}</p>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-gray-50 py-8">
      <div className="max-w-6xl mx-auto px-4">
        {/* Header */}
        <div className="flex justify-between items-center mb-8">
          <div>
            <h1 className="text-3xl font-bold text-gray-900">{t('owner.blogManagement')}</h1>
            <p className="text-gray-600 mt-2">{t('owner.manageYourBlogArticles')}</p>
          </div>
          <div className="flex space-x-3">
            <Link
              href="/owner/blog/new"
              className="inline-flex items-center px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-offset-2"
            >
              <svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
              </svg>
              {t('owner.createNewArticle')}
            </Link>
            <Link
              href="/owner"
              className="inline-flex items-center px-4 py-2 bg-gray-600 text-white rounded-md hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-gray-500 focus:ring-offset-2"
            >
              <svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 19l-7-7m0 0l7-7m-7 7h18" />
              </svg>
              {t('owner.backToDashboard')}
            </Link>
          </div>
        </div>

        {/* Filters */}
        <div className="bg-white rounded-lg shadow-md p-6 mb-6">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <div>
              <label htmlFor="search" className="block text-sm font-medium text-gray-700 mb-2">
                {t('owner.searchArticles')}
              </label>
              <input
                type="text"
                id="search"
                value={searchTerm}
                onChange={(e) => setSearchTerm(e.target.value)}
                className="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
                placeholder={t('owner.searchPlaceholder')}
              />
            </div>
            <div>
              <label htmlFor="category" className="block text-sm font-medium text-gray-700 mb-2">
                {t('owner.category')}
              </label>
              <select
                id="category"
                value={categoryFilter}
                onChange={(e) => setCategoryFilter(e.target.value)}
                className="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
              >
                <option value="">{t('owner.allCategories')}</option>
                {categories.map(category => (
                  <option key={category} value={category}>{category}</option>
                ))}
              </select>
            </div>
            <div>
              <label htmlFor="status" className="block text-sm font-medium text-gray-700 mb-2">
                {t('owner.status')}
              </label>
              <select
                id="status"
                value={statusFilter}
                onChange={(e) => setStatusFilter(e.target.value)}
                className="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
              >
                <option value="">{t('owner.allStatuses')}</option>
                <option value="true">{t('owner.published')}</option>
                <option value="false">{t('owner.draft')}</option>
              </select>
            </div>
          </div>
          <div className="mt-4">
            <button
              onClick={fetchArticles}
              className="inline-flex items-center px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2"
            >
              <svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
              </svg>
              {t('owner.filter')}
            </button>
          </div>
        </div>

        {/* Error Message */}
        {error && (
          <div className="mb-6 bg-red-50 border border-red-200 rounded-md p-4">
            <div className="flex">
              <div className="flex-shrink-0">
                <svg className="h-5 w-5 text-red-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
              </div>
              <div className="ml-3">
                <p className="text-sm text-red-800">{error}</p>
              </div>
            </div>
          </div>
        )}

        {/* Articles List */}
        <div className="bg-white rounded-lg shadow-md">
          {articles.length === 0 ? (
            <div className="text-center py-12">
              <svg className="mx-auto h-12 w-12 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 20H5a2 2 0 01-2-2V6a2 2 0 012-2h10a2 2 0 012 2v1m2 13a2 2 0 01-2-2V7m2 13a2 2 0 002-2V9a2 2 0 00-2-2h-2m-4-3H9M7 16h6M7 8h6v4H7V8z" />
              </svg>
              <h3 className="mt-2 text-sm font-medium text-gray-900">{t('owner.noArticles')}</h3>
              <p className="mt-1 text-sm text-gray-500">{t('owner.getStartedByCreatingArticle')}</p>
              <div className="mt-6">
                <Link
                  href="/owner/blog/new"
                  className="inline-flex items-center px-4 py-2 bg-green-600 text-white rounded-md hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-500 focus:ring-offset-2"
                >
                  <svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
                  </svg>
                  {t('owner.createNewArticle')}
                </Link>
              </div>
            </div>
          ) : (
            <div className="overflow-hidden">
              <table className="min-w-full divide-y divide-gray-200">
                <thead className="bg-gray-50">
                  <tr>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      {t('owner.title')}
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      {t('owner.category')}
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      {t('owner.status')}
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      {t('owner.created')}
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      {t('owner.views')}
                    </th>
                    <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">
                      {t('owner.actions')}
                    </th>
                  </tr>
                </thead>
                <tbody className="bg-white divide-y divide-gray-200">
                  {articles.map((article) => (
                    <tr key={article._id} className="hover:bg-gray-50">
                      <td className="px-6 py-4 whitespace-nowrap">
                        <div className="flex items-center">
                          <div className="flex-shrink-0 h-10 w-10">
                            {article.leadingImage ? (
                              <img
                                className="h-10 w-10 rounded-lg object-cover"
                                src={article.leadingImage.url}
                                alt={MultiLangUtils.getTextValue(article.leadingImage.alt, currentLanguage)}
                              />
                            ) : (
                              <div className="h-10 w-10 rounded-lg bg-gray-200 flex items-center justify-center">
                                <svg className="h-6 w-6 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 20H5a2 2 0 01-2-2V6a2 2 0 012-2h10a2 2 0 012 2v1m2 13a2 2 0 01-2-2V7m2 13a2 2 0 002-2V9a2 2 0 00-2-2h-2m-4-3H9M7 16h6M7 8h6v4H7V8z" />
                                </svg>
                              </div>
                            )}
                          </div>
                          <div className="ml-4">
                            <div className="text-sm font-medium text-gray-900">
                              {MultiLangUtils.getTextValue(article.title, currentLanguage)}
                            </div>
                            <div className="text-sm text-gray-500">
                              {article.slug}
                            </div>
                          </div>
                        </div>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-blue-100 text-blue-800">
                          {article.category}
                        </span>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${
                          article.isPublished 
                            ? 'bg-green-100 text-green-800' 
                            : 'bg-yellow-100 text-yellow-800'
                        }`}>
                          {article.isPublished ? t('owner.published') : t('owner.draft')}
                        </span>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                        {new Date(article.createdAt).toLocaleDateString()}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                        {article.viewCount}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                        <div className="flex justify-end space-x-2">
                          <Link
                            href={`/owner/blog/${article._id}/edit`}
                            className="text-blue-600 hover:text-blue-900"
                          >
                            {t('owner.edit')}
                          </Link>
                          <button
                            onClick={() => handleTogglePublish(article)}
                            className={`${
                              article.isPublished 
                                ? 'text-yellow-600 hover:text-yellow-900' 
                                : 'text-green-600 hover:text-green-900'
                            }`}
                          >
                            {article.isPublished ? t('owner.unpublish') : t('owner.publish')}
                          </button>
                          <button
                            onClick={() => handleDelete(article._id!)}
                            className="text-red-600 hover:text-red-900"
                          >
                            {t('owner.delete')}
                          </button>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
