// src/app/admin/photos/[id]/edit/page.tsx
'use client'

import { useState, useEffect, useCallback } from 'react'
import { use } from 'react'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import AdminGuard from '@/components/AdminGuard'
import Header from '@/templates/default/components/Header'
import Footer from '@/templates/default/components/Footer'
import MultiLangInput from '@/components/MultiLangInput'
import MultiLangHTMLEditor from '@/components/MultiLangHTMLEditor'
import PhotoMetadataEditor from '@/components/PhotoMetadataEditor'
import { MultiLangText, MultiLangHTML, MultiLangUtils } from '@/types/multi-lang'

interface Photo {
  _id: string
  title: string | { en: string }
  description: string | { en: string }
  filename: string
  originalFilename: string
  mimeType: string
  size: number
  dimensions?: {
    width: number
    height: number
  }
  storage: {
    url: string
    thumbnailPath: string
    path: string
    provider: string
  }
  albumId?: string
  tags: string[]
  people: string[]
  location?: {
    name: string
    coordinates?: {
      latitude: number
      longitude: number
    }
    address?: string
  }
  isLeading: boolean
  isPublished: boolean
  isGalleryLeading?: boolean
  createdAt: string
  updatedAt: string
}

export default function EditPhotoPage({ params }: { params: Promise<{ id: string }> }) {
  const resolvedParams = use(params)
  const router = useRouter()
  const [photo, setPhoto] = useState<Photo | null>(null)
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [formData, setFormData] = useState({
    title: {} as MultiLangText,
    description: {} as MultiLangHTML,
    tags: [] as string[],
    people: [] as string[],
    location: undefined as {
      name: string
      coordinates?: {
        latitude: number
        longitude: number
      }
      address?: string
    } | undefined,
    isPublished: false,
    isLeading: false,
    isGalleryLeading: false
  })

  useEffect(() => {
    const fetchPhoto = async () => {
      try {
        setLoading(true)
        const response = await fetch(`/api/photos/${resolvedParams.id}`)
        if (!response.ok) {
          throw new Error('Failed to fetch photo')
        }
        
        const result = await response.json()
        if (result.success) {
          const photoData = result.data
          setPhoto(photoData)
          
          // Initialize form data
          setFormData({
            title: (typeof photoData.title === 'string' ? { en: photoData.title } : (photoData.title || {})) as MultiLangText,
            description: (typeof photoData.description === 'string' ? { en: photoData.description } : (photoData.description || {})) as MultiLangHTML,
            tags: photoData.tags || [],
            people: photoData.people || [],
            location: photoData.location,
            isPublished: photoData.isPublished,
            isLeading: photoData.isLeading,
            isGalleryLeading: photoData.isGalleryLeading || false
          })
        } else {
          setError(result.error || 'Failed to fetch photo')
        }
      } catch (error) {
        console.error('Failed to fetch photo:', error)
        setError('Failed to fetch photo')
      } finally {
        setLoading(false)
      }
    }

    fetchPhoto()
  }, [resolvedParams.id])

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    
    try {
      setSaving(true)
      setError(null)

      const response = await fetch(`/api/photos/${resolvedParams.id}`, {
        method: 'PUT',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          title: MultiLangUtils.clean(formData.title),
          description: MultiLangUtils.clean(formData.description),
          tags: formData.tags,
          people: formData.people,
          location: formData.location,
          isPublished: formData.isPublished,
          isLeading: formData.isLeading,
          isGalleryLeading: formData.isGalleryLeading
        }),
      })

      if (response.ok) {
        const result = await response.json()
        if (result.success) {
          // Redirect back to the album page
          router.push(`/admin/albums/${photo?.albumId || ''}`)
        } else {
          setError(result.error || 'Failed to update photo')
        }
      } else {
        setError('Failed to update photo')
      }
    } catch (error) {
      console.error('Failed to update photo:', error)
      setError('Failed to update photo')
    } finally {
      setSaving(false)
    }
  }

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement>) => {
    const { name, value, type } = e.target
    setFormData(prev => ({
      ...prev,
      [name]: type === 'checkbox' ? (e.target as HTMLInputElement).checked : value
    }))
  }

  // Memoized metadata handlers to prevent child effect loops
  const handleTagsChange = useCallback((tags: string[]) => {
    setFormData(prev => ({ ...prev, tags }))
  }, [])

  const handlePeopleChange = useCallback((people: string[]) => {
    setFormData(prev => ({ ...prev, people }))
  }, [])

  const handleLocationChange = useCallback((location?: {
    name: string
    coordinates?: { latitude: number; longitude: number }
    address?: string
  }) => {
    setFormData(prev => ({ ...prev, location }))
  }, [])

  if (loading) {
    return (
      <AdminGuard>
        <div className="min-h-screen bg-gray-50">
          <Header />
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
            <div className="text-center">
              <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600 mx-auto"></div>
              <p className="mt-4 text-gray-600">Loading photo...</p>
            </div>
          </div>
          <Footer />
        </div>
      </AdminGuard>
    )
  }

  if (error || !photo) {
    return (
      <AdminGuard>
        <div className="min-h-screen bg-gray-50">
          <Header />
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
            <div className="text-center">
              <h1 className="text-2xl font-bold text-gray-900 mb-4">Error</h1>
              <p className="text-gray-600 mb-4">{error || 'Photo not found'}</p>
              <Link href="/admin/albums" className="btn-primary">
                Back to Albums
              </Link>
            </div>
          </div>
          <Footer />
        </div>
      </AdminGuard>
    )
  }

  return (
    <AdminGuard>
      <div className="min-h-screen bg-gray-50">
        <Header />
        
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
          {/* Header */}
          <div className="flex items-center justify-between mb-8">
            <div>
              <h1 className="text-3xl font-bold text-gray-900">Edit Photo</h1>
              <p className="mt-2 text-gray-600">
                {typeof photo.title === 'string' ? photo.title : photo.title.en}
              </p>
            </div>
            <div className="flex space-x-3">
              <button
                type="button"
                onClick={() => {
                  if (typeof window !== 'undefined' && window.history.length > 1) {
                    router.back()
                  } else {
                    router.push(photo?.albumId ? `/admin/albums/${String(photo.albumId)}` : '/admin/albums')
                  }
                }}
                className="btn-secondary"
              >
                Back to Album
              </button>
            </div>
          </div>

          <div className="bg-white rounded-lg shadow-sm border border-gray-200">
            <div className="p-6">
              <form onSubmit={handleSubmit} className="space-y-6">
                {/* Photo Preview */}
                <div className="flex items-start space-x-6">
                  <div className="flex-shrink-0">
                    <img
                      src={photo.storage.thumbnailPath || photo.storage.url}
                      alt={typeof photo.title === 'string' ? photo.title : photo.title.en}
                      className="w-32 h-32 object-cover rounded-lg"
                    />
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                      <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">
                          File Name
                        </label>
                        <p className="text-sm text-gray-600">{photo.originalFilename}</p>
                      </div>
                      <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">
                          File Size
                        </label>
                        <p className="text-sm text-gray-600">{(photo.size / 1024 / 1024).toFixed(2)} MB</p>
                      </div>
                      <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">
                          Dimensions
                        </label>
                        <p className="text-sm text-gray-600">
                          {photo.dimensions?.width || 0} × {photo.dimensions?.height || 0}
                        </p>
                      </div>
                      <div>
                        <label className="block text-sm font-medium text-gray-700 mb-1">
                          Type
                        </label>
                        <p className="text-sm text-gray-600">{photo.mimeType}</p>
                      </div>
                    </div>
                  </div>
                </div>

                {/* Title */}
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Title
                  </label>
                  <MultiLangInput
                    value={formData.title}
                    onChange={(value) => setFormData(prev => ({ ...prev, title: value as MultiLangText }))}
                    placeholder="Enter photo title..."
                    required
                  />
                </div>

                {/* Description */}
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Description
                  </label>
                  <MultiLangHTMLEditor
                    value={formData.description}
                    onChange={(value) => setFormData(prev => ({ ...prev, description: value as MultiLangHTML }))}
                    placeholder="Enter photo description..."
                    height={240}
                  />
                </div>

                {/* Metadata */}
                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-2">
                    Photo Metadata
                  </label>
                  <PhotoMetadataEditor
                    tags={formData.tags}
                    people={formData.people}
                    location={formData.location}
                    onTagsChange={handleTagsChange}
                    onPeopleChange={handlePeopleChange}
                    onLocationChange={handleLocationChange}
                  />
                </div>

                {/* Status Toggles */}
                <div className="flex flex-col space-y-4">
                  <div className="flex items-center">
                    <input
                      type="checkbox"
                      id="isPublished"
                      name="isPublished"
                      checked={formData.isPublished}
                      onChange={handleInputChange}
                      className="h-4 w-4 text-primary-600 focus:ring-primary-500 border-gray-300 rounded"
                    />
                    <label htmlFor="isPublished" className="ml-2 block text-sm text-gray-700">
                      Published (visible to public)
                    </label>
                  </div>
                  <div className="flex items-center">
                    <input
                      type="checkbox"
                      id="isLeading"
                      name="isLeading"
                      checked={formData.isLeading}
                      onChange={handleInputChange}
                      className="h-4 w-4 text-primary-600 focus:ring-primary-500 border-gray-300 rounded"
                    />
                    <label htmlFor="isLeading" className="ml-2 block text-sm text-gray-700">
                      Leading Photo (album cover)
                    </label>
                  </div>
                  <div className="flex items-center">
                    <input
                      type="checkbox"
                      id="isGalleryLeading"
                      name="isGalleryLeading"
                      checked={formData.isGalleryLeading}
                      onChange={handleInputChange}
                      className="h-4 w-4 text-primary-600 focus:ring-primary-500 border-gray-300 rounded"
                    />
                    <label htmlFor="isGalleryLeading" className="ml-2 block text-sm text-gray-700">
                      Gallery Leading Photo (hero showcase)
                    </label>
                  </div>
                </div>

                {/* Error Message */}
                {error && (
                  <div className="bg-red-50 border border-red-200 rounded-md p-4">
                    <p className="text-sm text-red-600">{error}</p>
                  </div>
                )}

                {/* Action Buttons */}
                <div className="flex justify-end space-x-3 pt-6 border-t border-gray-200">
                  <button
                    type="button"
                    onClick={() => {
                      if (typeof window !== 'undefined' && window.history.length > 1) {
                        router.back()
                      } else {
                        router.push(photo?.albumId ? `/admin/albums/${String(photo.albumId)}` : '/admin/albums')
                      }
                    }}
                    className="px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-primary-500"
                  >
                    Cancel
                  </button>
                  <button
                    type="submit"
                    disabled={saving}
                    className="px-4 py-2 text-sm font-medium text-white bg-primary-600 border border-transparent rounded-md hover:bg-primary-700 focus:outline-none focus:ring-2 focus:ring-primary-500 disabled:opacity-50 disabled:cursor-not-allowed"
                  >
                    {saving ? 'Saving...' : 'Save Changes'}
                  </button>
                </div>
              </form>
            </div>
          </div>
        </div>

        <Footer />
      </div>
    </AdminGuard>
  )
}

// frontend/src/routes/admin/albums/[id]/edit/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { page } from '$app/stores';
	import { goto } from '$app/navigation';
	import { currentLanguage } from '$stores/language';
	import { MultiLangUtils } from '$utils/multiLang';
	import MultiLangInput from '$lib/components/MultiLangInput.svelte';
	import MultiLangHTMLEditor from '$lib/components/MultiLangHTMLEditor.svelte';
	import AlbumBreadcrumbs from '$lib/components/AlbumBreadcrumbs.svelte';
	import NotificationDialog from '$lib/components/NotificationDialog.svelte';

	interface Album {
		_id: string;
		name: any;
		alias: string;
		description?: any;
		isPublic: boolean;
		isFeatured: boolean;
		showExifData?: boolean;
		order: number;
		storageProvider: string;
		photoCount: number;
		level: number;
		parentPath?: string;
		createdAt: string | Date;
		updatedAt: string | Date;
		createdBy?: string;
		tags?: string[];
		people?: string[];
		location?: string | null;
	}

	let albumId: string = $page.params.id;
	let album: Album | null = null;
	let loading = true;
	let saving = false;
	let error = '';
	let notification = { show: false, message: '', type: 'success' as 'success' | 'error' };

	let formData = {
		name: {} as Record<string, string>,
		description: {} as Record<string, string>,
		isPublic: false,
		isFeatured: false,
		showExifData: true,
		order: 0,
		tags: [] as string[],
		people: [] as string[],
		location: null as string | null,
	};

	async function loadAlbum() {
		try {
			loading = true;
			error = '';
			const response = await fetch(`/api/albums/${albumId}?t=${Date.now()}`, {
				cache: 'no-store',
			});
			if (!response.ok) {
				throw new Error('Failed to fetch album');
			}
			const data = await response.json();
			album = data;
			console.log('Album loaded:', album);

			// Initialize form data
			if (album) {
				formData.name =
					typeof album.name === 'string' ? { en: album.name } : album.name || {};
				formData.description =
					typeof album.description === 'string'
						? { en: album.description }
						: album.description || {};
				formData.isPublic = album.isPublic || false;
				formData.isFeatured = album.isFeatured || false;
				formData.showExifData = album.showExifData !== undefined ? album.showExifData : true;
				formData.order = album.order || 0;
				// Convert ObjectIds to strings if needed
				formData.tags =
					album.tags?.map((tag: any) =>
						typeof tag === 'string' ? tag : tag._id?.toString() || tag.toString()
					) || [];
				formData.people =
					album.people?.map((person: any) =>
						typeof person === 'string' ? person : person._id?.toString() || person.toString()
					) || [];
				formData.location =
					album.location
						? typeof album.location === 'string'
							? album.location
							: album.location._id?.toString() || album.location.toString()
						: null;
			}
		} catch (err) {
			console.error('Failed to fetch album:', err);
			error = `Failed to load album: ${err instanceof Error ? err.message : 'Unknown error'}`;
		} finally {
			loading = false;
		}
	}

	async function handleSubmit(e: Event) {
		e.preventDefault();
		if (!album) return;

		try {
			saving = true;
			error = '';

			const updateData = {
				name: MultiLangUtils.clean(formData.name),
				description: MultiLangUtils.clean(formData.description),
				isPublic: formData.isPublic,
				isFeatured: formData.isFeatured,
				showExifData: formData.showExifData,
				order: formData.order,
				tags: formData.tags,
				people: formData.people,
				location: formData.location,
			};

			const response = await fetch(`/api/admin/albums/${albumId}`, {
				method: 'PUT',
				headers: {
					'Content-Type': 'application/json',
				},
				body: JSON.stringify(updateData),
			});

			if (!response.ok) {
				const errorData = await response.json().catch(() => ({}));
				throw new Error(errorData.message || `Failed to update album: ${response.statusText}`);
			}

			const updatedAlbum = await response.json();
			console.log('Album updated:', updatedAlbum);

			notification = {
				show: true,
				message: 'Album updated successfully',
				type: 'success',
			};

			// Redirect after a short delay
			setTimeout(() => {
				goto(`/admin/albums/${albumId}`);
			}, 1000);
		} catch (err) {
			console.error('Failed to update album:', err);
			error = `Failed to update album: ${err instanceof Error ? err.message : 'Unknown error'}`;
			notification = {
				show: true,
				message: error,
				type: 'error',
			};
		} finally {
			saving = false;
		}
	}

	function handleInputChange(e: Event) {
		const target = e.target as HTMLInputElement;
		const { name, type, value } = target;
		if (type === 'checkbox') {
			formData = { ...formData, [name]: target.checked };
		} else if (type === 'number') {
			formData = { ...formData, [name]: parseInt(value) || 0 };
		} else {
			formData = { ...formData, [name]: value };
		}
	}

	onMount(() => {
		loadAlbum();
	});
</script>

<svelte:head>
	<title>
		{album
			? `${MultiLangUtils.getTextValue(album.name, $currentLanguage)} - Edit Album`
			: 'Edit Album'}
		- Admin
	</title>
</svelte:head>

<div class="min-h-screen bg-gray-50">
	<div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
		{#if loading}
			<div class="text-center py-12">
				<div class="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600 mx-auto"></div>
				<p class="mt-4 text-gray-600">Loading album...</p>
			</div>
		{:else if error && !album}
			<div class="text-center py-12">
				<h1 class="text-2xl font-bold text-gray-900 mb-4">Error</h1>
				<p class="text-gray-600 mb-4">{error}</p>
				<a href="/admin/albums" class="btn-primary">Back to Albums</a>
			</div>
		{:else if album}
			<!-- Breadcrumbs -->
			<AlbumBreadcrumbs album={album} role="admin" currentPage="edit" />

			<!-- Header -->
			<div class="flex items-center justify-between mb-8">
				<div>
					<h1 class="text-3xl font-bold text-gray-900">Edit Album</h1>
					<p class="mt-2 text-gray-600">
						{MultiLangUtils.getTextValue(album.name, $currentLanguage)}
					</p>
				</div>
			</div>

			<!-- Form -->
			<div class="bg-white rounded-lg shadow-sm border border-gray-200">
				<form on:submit={handleSubmit} class="p-6 space-y-6">
					<!-- Album Info -->
					<div class="grid grid-cols-1 md:grid-cols-2 gap-6">
						<div>
							<span class="block text-sm font-medium text-gray-700 mb-2">
								Album Name
							</span>
							<MultiLangInput
								value={formData.name}
								onChange={(value) => {
									formData = { ...formData, name: value };
								}}
								placeholder="Enter album name..."
								required
							/>
						</div>

						<div>
							<label for="alias" class="block text-sm font-medium text-gray-700 mb-2">
								URL Alias
							</label>
							<input
								type="text"
								id="alias"
								value={album.alias}
								class="w-full px-3 py-2 border border-gray-300 rounded-md bg-gray-50"
								disabled
							/>
							<p class="text-xs text-gray-500 mt-1">URL alias cannot be changed</p>
						</div>
					</div>

					<!-- Description -->
					<div>
						<span class="block text-sm font-medium text-gray-700 mb-2">
							Description
						</span>
						<MultiLangHTMLEditor
							value={formData.description}
							onChange={(value) => {
								formData = { ...formData, description: value };
							}}
							placeholder="Enter album description..."
							height={240}
						/>
					</div>

					<!-- Album Details -->
					<div class="grid grid-cols-1 md:grid-cols-3 gap-6">
						<div>
							<label for="order" class="block text-sm font-medium text-gray-700 mb-2">
								Display Order
							</label>
							<input
								type="number"
								id="order"
								name="order"
								value={formData.order}
								on:input={handleInputChange}
								min="0"
								class="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
							/>
						</div>

						<div>
							<label for="storage-provider" class="block text-sm font-medium text-gray-700 mb-2">
								Storage Provider
							</label>
							<input
								type="text"
								id="storage-provider"
								value={album.storageProvider}
								class="w-full px-3 py-2 border border-gray-300 rounded-md bg-gray-50"
								disabled
							/>
						</div>

						<div>
							<label for="photo-count" class="block text-sm font-medium text-gray-700 mb-2">
								Photo Count
							</label>
							<input
								type="text"
								id="photo-count"
								value={album.photoCount}
								class="w-full px-3 py-2 border border-gray-300 rounded-md bg-gray-50"
								disabled
							/>
						</div>
					</div>

					<!-- Status Toggles -->
					<div class="flex flex-wrap gap-6">
						<div class="flex items-center">
							<input
								type="checkbox"
								id="isPublic"
								name="isPublic"
								checked={formData.isPublic}
								on:change={handleInputChange}
								class="h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-300 rounded"
							/>
							<label for="isPublic" class="ml-2 block text-sm text-gray-700">
								Public (visible to visitors)
							</label>
						</div>
						<div class="flex items-center">
							<input
								type="checkbox"
								id="isFeatured"
								name="isFeatured"
								checked={formData.isFeatured}
								on:change={handleInputChange}
								class="h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-300 rounded"
							/>
							<label for="isFeatured" class="ml-2 block text-sm text-gray-700">
								Featured (highlighted on homepage)
							</label>
						</div>
						<div class="flex items-center">
							<input
								type="checkbox"
								id="showExifData"
								name="showExifData"
								checked={formData.showExifData}
								on:change={handleInputChange}
								class="h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-300 rounded"
							/>
							<label for="showExifData" class="ml-2 block text-sm text-gray-700">
								Show EXIF data in photo viewer
							</label>
						</div>
					</div>

					<!-- Read-only Information -->
					<div class="bg-gray-50 rounded-lg p-4">
						<h3 class="text-sm font-medium text-gray-700 mb-3">Album Information</h3>
						<div class="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm">
							<div>
								<span class="font-medium text-gray-700">Created:</span>
								<span class="ml-2 text-gray-600">
									{new Date(album.createdAt).toLocaleDateString()}
								</span>
							</div>
							<div>
								<span class="font-medium text-gray-700">Last Updated:</span>
								<span class="ml-2 text-gray-600">
									{new Date(album.updatedAt).toLocaleDateString()}
								</span>
							</div>
							<div>
								<span class="font-medium text-gray-700">Level:</span>
								<span class="ml-2 text-gray-600">{album.level}</span>
							</div>
							{#if album.parentPath}
								<div class="md:col-span-2">
									<span class="font-medium text-gray-700">Parent Path:</span>
									<span class="ml-2 text-gray-600">{album.parentPath}</span>
								</div>
							{/if}
						</div>
					</div>

					<!-- Error Message -->
					{#if error}
						<div class="bg-red-50 border border-red-200 rounded-md p-4">
							<p class="text-sm text-red-600">{error}</p>
						</div>
					{/if}

					<!-- Action Buttons -->
					<div class="flex justify-end space-x-3 pt-6 border-t border-gray-200">
						<a
							href="/admin/albums/{albumId}"
							class="px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-blue-500"
						>
							Cancel
						</a>
						<button
							type="submit"
							disabled={saving}
							class="px-4 py-2 text-sm font-medium text-white bg-blue-600 border border-transparent rounded-md hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 disabled:opacity-50 disabled:cursor-not-allowed"
						>
							{saving ? 'Saving...' : 'Save Changes'}
						</button>
					</div>
				</form>
			</div>
		{/if}
	</div>
</div>

<NotificationDialog
	isOpen={notification.show}
	message={notification.message}
	type={notification.type}
	onClose={() => {
		notification.show = false;
	}}
/>
