// frontend/src/lib/templates/minimal/components/Footer.svelte
<script lang="ts">
	const year = new Date().getFullYear();
</script>

<footer class="bg-white border-t border-black mt-16">
	<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
		<div class="text-center space-y-2">
			<p class="text-sm text-gray-600 font-light">
				© {year} OpenShutter. All rights reserved.
			</p>
		</div>
	</div>
</footer>

// src/templates/simple/components/Footer.tsx
import React from 'react';

const Footer: React.FC = () => {
  return (
    <footer className="footer footer-center bg-base-200 text-base-content p-6 mt-12">
      <aside>
        <p>© {new Date().getFullYear()} OpenShutter. All rights reserved.</p>
      </aside>
    </footer>
  );
};

export default Footer;
