// frontend/src/lib/components/LazyImage.svelte
<script lang="ts">
	import { onMount } from 'svelte';

	let {
		src: string,
		alt: string,
		width = undefined,
		height = undefined,
		className = $bindable(''),
		imageClassName = $bindable(''),
		priority = $bindable(false),
		sizes = undefined,
		style = undefined,
		fill = $bindable(false),
		quality = $bindable(75),
		placeholder = 'empty',
		blurDataURL = undefined,
		fetchPriority = 'auto',
		loading = undefined,
		unoptimized = $bindable(false)
	}: {
		src: string;
		alt: string;
		width?: number | undefined;
		height?: number | undefined;
		className?: unknown;
		imageClassName?: unknown;
		priority?: unknown;
		sizes?: string | undefined;
		style?: string | undefined;
		fill?: unknown;
		quality?: unknown;
		placeholder?: 'blur' | 'empty';
		blurDataURL?: string | undefined;
		fetchPriority?: 'high' | 'low' | 'auto';
		loading?: 'eager' | 'lazy' | undefined;
		unoptimized?: unknown;
	} = $props();

	let isLoaded = false;
	let isInView = priority;
	let imgRef: HTMLDivElement | null = null;

	onMount(() => {
		if (priority) return;

		const observer = new IntersectionObserver(
			([entry]) => {
				if (entry.isIntersecting) {
					isInView = true;
					observer.disconnect();
				}
			},
			{
				threshold: 0.1,
				rootMargin: '50px'
			}
		);

		if (imgRef) {
			observer.observe(imgRef);
		}

		return () => observer.disconnect();
	});

	function handleLoad() {
		isLoaded = true;
	}
</script>

<div bind:this={imgRef} class="relative {className}" style={style}>
	{#if !isInView}
		<div class="bg-gray-200 animate-pulse rounded flex items-center justify-center">
			{#if width && height}
				<div style="width: {width}px; height: {height}px;" class="flex items-center justify-center">
					<svg class="w-8 h-8 text-gray-400" fill="currentColor" viewBox="0 0 20 20">
						<path
							fill-rule="evenodd"
							d="M4 3a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V5a2 2 0 00-2-2H4zm12 12H4l4-8 3 6 2-4 3 6z"
							clip-rule="evenodd"
						/>
					</svg>
				</div>
			{:else}
				<div class="w-full h-full flex items-center justify-center">
					<svg class="w-8 h-8 text-gray-400" fill="currentColor" viewBox="0 0 20 20">
						<path
							fill-rule="evenodd"
							d="M4 3a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V5a2 2 0 00-2-2H4zm12 12H4l4-8 3 6 2-4 3 6z"
							clip-rule="evenodd"
						/>
					</svg>
				</div>
			{/if}
		</div>
	{:else}
		<img
			src={src}
			alt={alt}
			width={width}
			height={height}
			sizes={sizes}
			loading={loading ?? (priority ? 'eager' : 'lazy')}
			fetchpriority={fetchPriority}
			decoding="async"
			onload={handleLoad}
			class="transition-opacity duration-300 {isLoaded ? 'opacity-100' : 'opacity-0'} {imageClassName} {fill
				? 'absolute inset-0 w-full h-full object-cover'
				: ''}"
		/>
	{/if}
</div>

// src/components/LazyImage.tsx
'use client'

import { useState, useRef, useEffect } from 'react'
import Image from 'next/image'

interface LazyImageProps {
  src: string
  alt: string
  width?: number
  height?: number
  className?: string
  imageClassName?: string
  priority?: boolean
  sizes?: string
  style?: React.CSSProperties
  fill?: boolean
  quality?: number
  placeholder?: 'blur' | 'empty'
  blurDataURL?: string
  fetchPriority?: 'high' | 'low' | 'auto'
  loading?: 'eager' | 'lazy'
  unoptimized?: boolean
}

export default function LazyImage({
  src,
  alt,
  width,
  height,
  className = '',
  imageClassName = '',
  priority = false,
  sizes,
  style,
  fill = false,
  quality = 75,
  placeholder = 'empty',
  blurDataURL,
  fetchPriority = 'auto',
  loading,
  unoptimized = false
}: LazyImageProps) {
  const [isLoaded, setIsLoaded] = useState(false)
  const [isInView, setIsInView] = useState(priority)
  const imgRef = useRef<HTMLDivElement>(null)

  useEffect(() => {
    if (priority) return

    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          setIsInView(true)
          observer.disconnect()
        }
      },
      {
        threshold: 0.1,
        rootMargin: '50px'
      }
    )

    if (imgRef.current) {
      observer.observe(imgRef.current)
    }

    return () => observer.disconnect()
  }, [priority])

  const handleLoad = () => {
    setIsLoaded(true)
  }

  return (
    <div ref={imgRef} className={`relative ${className}`} style={style}>
      {!isInView ? (
        <div className="bg-gray-200 animate-pulse rounded flex items-center justify-center">
          {width && height ? (
            <div style={{ width, height }} className="flex items-center justify-center">
              <svg className="w-8 h-8 text-gray-400" fill="currentColor" viewBox="0 0 20 20">
                <path fillRule="evenodd" d="M4 3a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V5a2 2 0 00-2-2H4zm12 12H4l4-8 3 6 2-4 3 6z" clipRule="evenodd" />
              </svg>
            </div>
          ) : (
            <div className="w-full h-full flex items-center justify-center">
              <svg className="w-8 h-8 text-gray-400" fill="currentColor" viewBox="0 0 20 20">
                <path fillRule="evenodd" d="M4 3a2 2 0 00-2 2v10a2 2 0 002 2h12a2 2 0 002-2V5a2 2 0 00-2-2H4zm12 12H4l4-8 3 6 2-4 3 6z" clipRule="evenodd" />
              </svg>
            </div>
          )}
        </div>
      ) : (
        <Image
          src={src}
          alt={alt}
          width={width}
          height={height}
          fill={fill}
          sizes={sizes}
          quality={quality}
          priority={priority}
          placeholder={placeholder}
          blurDataURL={blurDataURL}
          onLoad={handleLoad}
          loading={loading ?? (priority ? 'eager' : 'lazy')}
          fetchPriority={fetchPriority}
          unoptimized={unoptimized}
          decoding="async"
          className={`transition-opacity duration-300 ${isLoaded ? 'opacity-100' : 'opacity-0'} ${imageClassName}`}
        />
      )}
    </div>
  )
}
