// frontend/src/lib/components/MultiLangHTMLEditor.svelte
<script lang="ts">
	import { siteConfigData } from '$stores/siteConfig';
	import { SUPPORTED_LANGUAGES } from '$lib/types/multi-lang';
	import type { MultiLangHTML, LanguageCode } from '$lib/types/multi-lang';
	import TiptapHTMLEditor from './TiptapHTMLEditor.svelte';

	export let value: MultiLangHTML = {};
	export let onChange: (value: MultiLangHTML) => void;
	export let placeholder = 'Start typing...';
	export let height = 200;
	export let showLanguageTabs = true;
	export let defaultLanguage: LanguageCode = 'en';
	export let className = '';

	let activeLanguage: LanguageCode = defaultLanguage;
	let editorValue = '';
	let isInternalUpdate = false;

	$: config = $siteConfigData;
	$: isRTL = activeLanguage === 'he' || activeLanguage === 'ar' || activeLanguage === 'fa';

	// Get active languages from site config and map to full language objects
	$: activeLanguages = config?.languages?.activeLanguages || ['en'];
	$: availableLanguages = SUPPORTED_LANGUAGES.filter((lang) =>
		activeLanguages.includes(lang.code)
	);

	// Update editor value when active language or value changes externally
	$: if (activeLanguage && !isInternalUpdate && value) {
		const newEditorValue = value[activeLanguage] || '';
		// Only update if different to avoid unnecessary updates
		if (newEditorValue !== editorValue) {
			editorValue = newEditorValue;
		}
		isInternalUpdate = false;
	}

	// Sync active language when defaultLanguage prop changes
	$: {
		if (defaultLanguage && activeLanguage !== defaultLanguage) {
			activeLanguage = defaultLanguage;
		}
	}

	function handleEditorChange(newValue: string) {
		isInternalUpdate = true;
		editorValue = newValue;

		// Update the multi-language object
		const updatedValue = {
			...value,
			[activeLanguage]: newValue
		};
		onChange(updatedValue);
	}

	function handleLanguageChange(language: LanguageCode) {
		// Don't do anything if clicking the same language
		if (language === activeLanguage) {
			return;
		}
		
		// Prevent reactive statement from interfering
		isInternalUpdate = true;
		
		// Save current content before switching
		const updatedValue = {
			...value,
			[activeLanguage]: editorValue
		};
		onChange(updatedValue);

		// Switch to new language
		activeLanguage = language;
		
		// Update editor value for the new language immediately
		const newValue = updatedValue[language] || '';
		editorValue = typeof newValue === 'string' ? newValue : '';
		
		// Allow reactive updates again after a brief delay
		setTimeout(() => {
			isInternalUpdate = false;
		}, 10);
	}

	$: hasContent = (langCode: LanguageCode) => !!(value && value[langCode] && value[langCode].trim());
</script>

<div class="space-y-3 {className}">
	<!-- Language Tabs -->
	{#if showLanguageTabs && availableLanguages.length > 1}
		<div class="flex border-b border-gray-200 {isRTL ? 'flex-row-reverse' : ''}" style="pointer-events: auto;">
			{#each availableLanguages as language}
				{@const isActive = language.code === activeLanguage}
				{@const hasLangContent = hasContent(language.code)}
				<button
					type="button"
					on:click|stopPropagation|preventDefault={() => handleLanguageChange(language.code)}
					on:mousedown|stopPropagation|preventDefault={() => handleLanguageChange(language.code)}
					class="flex items-center gap-2 px-3 py-2 text-sm font-medium rounded-t-lg border-b-2 transition-colors cursor-pointer z-10 relative pointer-events-auto {isActive
						? 'border-blue-500 text-blue-600 bg-blue-50'
						: 'border-transparent text-gray-500 hover:text-gray-700 hover:bg-gray-50'} {hasLangContent
						? 'font-semibold'
						: 'font-normal'} {isRTL ? 'flex-row-reverse' : ''}"
					style="pointer-events: auto; user-select: none;"
				>
					<span class="text-lg pointer-events-none">{language.flag}</span>
					<span class="hidden sm:inline pointer-events-none">{language.nativeName}</span>
					{#if hasLangContent}
						<span class="w-2 h-2 bg-green-500 rounded-full pointer-events-none"></span>
					{/if}
				</button>
			{/each}
		</div>
	{/if}

	<!-- Editor Field -->
	<TiptapHTMLEditor
		value={editorValue}
		onChange={handleEditorChange}
		{placeholder}
		{height}
		{isRTL}
		className="w-full"
	/>
</div>

// src/components/MultiLangHTMLEditor.tsx
'use client'

import { useState, useEffect } from 'react'
import { MultiLangHTML } from '@/types/multi-lang'
import { useLanguage } from '@/contexts/LanguageContext'
import { useSiteConfig } from '@/hooks/useSiteConfig'
import TiptapHTMLEditor from './TiptapHTMLEditor'

interface MultiLangHTMLEditorProps {
  value: MultiLangHTML
  onChange: (value: MultiLangHTML) => void
  placeholder?: string
  height?: number
  showLanguageTabs?: boolean
  defaultLanguage?: string
  className?: string
}

export default function MultiLangHTMLEditor({
  value,
  onChange,
  placeholder = 'Start typing...',
  height = 200,
  showLanguageTabs = true,
  defaultLanguage = 'en',
  className = ''
}: MultiLangHTMLEditorProps) {
  const { currentLanguage, isRTL: globalIsRTL } = useLanguage()
  const { config } = useSiteConfig()
  const [activeLanguage, setActiveLanguage] = useState(defaultLanguage)
  const [editorValue, setEditorValue] = useState('')

  // Get available languages from site config, fallback to English
  const availableLanguages = config?.languages?.activeLanguages?.length
    ? config.languages.activeLanguages
    : ['en']
  
  // Determine if current language is RTL
  const isRTL = activeLanguage === 'he' || activeLanguage === 'ar' || activeLanguage === 'fa'

  // Update editor value when active language changes
  useEffect(() => {
    const currentValue = value[activeLanguage] || ''
    setEditorValue(currentValue)
  }, [activeLanguage, value])

  // Sync active language when defaultLanguage prop changes (e.g., after config loads)
  useEffect(() => {
    if (defaultLanguage && activeLanguage !== defaultLanguage) {
      setActiveLanguage(defaultLanguage)
    }
  }, [defaultLanguage])

  // Handle editor content changes
  const handleEditorChange = (newValue: string) => {
    setEditorValue(newValue)
    
    // Update the multi-language object
    const updatedValue = {
      ...value,
      [activeLanguage]: newValue
    }
    onChange(updatedValue)
  }

  // Handle language tab changes
  const handleLanguageChange = (language: string) => {
    // Save current content before switching
    const updatedValue = {
      ...value,
      [activeLanguage]: editorValue
    }
    onChange(updatedValue)
    
    // Switch to new language
    setActiveLanguage(language)
  }

  return (
    <div className={`space-y-3 ${className}`}>
      {/* Language Tabs */}
      {showLanguageTabs && availableLanguages.length > 1 && (
        <div className={`flex border-b border-gray-200 ${isRTL ? 'flex-row-reverse space-x-reverse' : 'space-x-1'}`}>
          {availableLanguages.map((lang) => (
            <button
              key={lang}
              type="button"
              onClick={() => handleLanguageChange(lang)}
              className={`px-4 py-2 text-sm font-medium border-b-2 transition-colors ${
                activeLanguage === lang
                  ? 'border-blue-500 text-blue-600'
                  : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'
              }`}
            >
              {lang === 'en' ? 'English' : 
               lang === 'he' ? 'עברית' : 
               lang === 'ar' ? 'العربية' : 
               lang === 'fa' ? 'فارسی' : 
               lang.toUpperCase()}
            </button>
          ))}
        </div>
      )}

      {/* Editor */}
      <TiptapHTMLEditor
        value={editorValue}
        onChange={handleEditorChange}
        placeholder={placeholder}
        height={height}
        isRTL={isRTL}
        className="w-full"
      />

      {/* Language Indicator */}
      {showLanguageTabs && (
        <div className="flex items-center justify-between text-xs text-gray-500">
          <span>
            Editing in: {activeLanguage === 'en' ? 'English' : 
                        activeLanguage === 'he' ? 'עברית' : 
                        activeLanguage === 'ar' ? 'العربية' : 
                        activeLanguage === 'fa' ? 'فارسی' : 
                        activeLanguage.toUpperCase()}
          </span>
          <span className={`px-2 py-1 rounded text-xs ${
            isRTL ? 'bg-orange-100 text-orange-800' : 'bg-blue-100 text-blue-800'
          }`}>
            {isRTL ? 'RTL' : 'LTR'}
          </span>
        </div>
      )}
    </div>
  )
}
