// frontend/src/components/AlbumTree.tsx
'use client'

import React, { useMemo, useState, useEffect } from 'react'
import {
  DndContext,
  DragEndEvent,
  PointerSensor,
  useSensor,
  useSensors,
  useDroppable,
  useDraggable,
} from '@dnd-kit/core'
import {
  SortableContext,
  verticalListSortingStrategy,
  arrayMove,
} from '@dnd-kit/sortable'
import { CSS } from '@dnd-kit/utilities'

type AlbumItem = {
  _id: string
  name: string
  alias: string
  parentAlbumId?: string | null
  level: number
  order: number
  childAlbumCount?: number
}

export interface AlbumTreeNode extends AlbumItem {
  children: AlbumTreeNode[]
}

function buildTree(albums: AlbumItem[]): AlbumTreeNode[] {
  const byId = new Map<string, AlbumTreeNode>()
  albums.forEach(a => byId.set(a._id, { ...a, children: [] }))
  const roots: AlbumTreeNode[] = []
  byId.forEach(node => {
    const parentId = node.parentAlbumId ?? null
    if (parentId && byId.has(parentId)) {
      byId.get(parentId)!.children.push(node)
    } else {
      roots.push(node)
    }
  })
  const sortRecursive = (nodes: AlbumTreeNode[]) => {
    nodes.sort((a, b) => {
      const orderA = a.order ?? 0
      const orderB = b.order ?? 0
      if (orderA !== orderB) {
        return orderA - orderB
      }
      return a.name.localeCompare(b.name)
    })
    nodes.forEach(n => sortRecursive(n.children))
  }
  sortRecursive(roots)
  return roots
}

function flatten(nodes: AlbumTreeNode[]): AlbumTreeNode[] {
  const out: AlbumTreeNode[] = []
  const walk = (arr: AlbumTreeNode[]) => {
    for (const n of arr) {
      out.push(n)
      if (n.children.length) walk(n.children)
    }
  }
  walk(nodes)
  return out
}

import Link from 'next/link'

function TreeRow({ 
  node, 
  renderActions, 
  onOpen,
  isExpanded,
  onToggleExpand,
  showAccordion
}: { 
  node: AlbumTreeNode
  renderActions?: (node: AlbumTreeNode) => React.ReactNode
  onOpen?: (node: AlbumTreeNode) => void
  isExpanded?: boolean
  onToggleExpand?: () => void
  showAccordion?: boolean
}) {
  const { attributes, listeners, setNodeRef, transform, isDragging } = useDraggable({ 
    id: node._id,
    data: { node }
  })
  const { setNodeRef: setDroppableRef, isOver } = useDroppable({
    id: node._id,
    data: { node }
  })
  
  const style: React.CSSProperties = {
    transform: CSS.Transform.toString(transform),
    opacity: isDragging ? 0.5 : 1,
    backgroundColor: isOver ? 'rgba(59, 130, 246, 0.1)' : undefined,
  }
  
  const hasChildren = node.children.length > 0
  
  // Combine refs for both draggable and droppable
  const combinedRef = (element: HTMLDivElement | null) => {
    setNodeRef(element)
    setDroppableRef(element)
  }
  
  return (
    <div ref={combinedRef} style={style} className="flex items-center gap-2 py-1 px-2 cursor-pointer hover:bg-gray-50" onClick={() => onOpen?.(node)}>
      <span className="text-muted-foreground select-none" style={{ width: 16 * Math.max(0, node.level) }} />
      
      {/* Accordion toggle for level 2 nodes */}
      {showAccordion ? (
        <button
          onClick={(e) => {
            e.stopPropagation()
            onToggleExpand?.()
          }}
          className={`w-6 h-6 flex items-center justify-center text-gray-600 hover:text-gray-900 hover:bg-gray-200 rounded transition-all flex-shrink-0 ${
            hasChildren ? '' : 'opacity-50 cursor-default'
          }`}
          aria-label={isExpanded ? 'Collapse' : 'Expand'}
          title={hasChildren ? (isExpanded ? 'Collapse' : 'Expand') : 'No children'}
          disabled={!hasChildren}
        >
          <svg
            className={`w-5 h-5 transition-transform duration-200 ${isExpanded ? 'rotate-90' : ''}`}
            fill="none"
            stroke="currentColor"
            strokeWidth={2.5}
            viewBox="0 0 24 24"
          >
            <path strokeLinecap="round" strokeLinejoin="round" d="M9 5l7 7-7 7" />
          </svg>
        </button>
      ) : (
        <span className="w-4" />
      )}
      
      <button aria-label="drag" {...listeners} {...attributes} className="cursor-move text-muted-foreground">⋮⋮</button>
      <div className="flex-1 truncate">
        <span className="font-medium">{node.name}</span>
        <span className="ml-2 text-xs text-muted-foreground">/{node.alias}</span>
      </div>
      <div className="flex items-center gap-2">
        {typeof node.childAlbumCount === 'number' && (
          <span className="text-xs text-muted-foreground">{node.childAlbumCount}</span>
        )}
        {renderActions?.(node)}
      </div>
    </div>
  )
}

function TreeNode({ 
  node, 
  renderActions, 
  onOpen,
  expandedNodes,
  onToggleNode
}: { 
  node: AlbumTreeNode
  renderActions?: (node: AlbumTreeNode) => React.ReactNode
  onOpen?: (node: AlbumTreeNode) => void
  expandedNodes?: Set<string>
  onToggleNode: (nodeId: string) => void
}) {
  // Show accordion button on level 1 nodes (second level in 1-indexed counting)
  // BUT only if they have children (sub-albums)
  // Level 1 nodes can toggle visibility of level 2+ children
  // Level 2+ nodes don't show accordion button themselves
  const hasChildren = node.children.length > 0
  const showAccordion = node.level === 1 && hasChildren
  // Ensure expandedNodes is always a Set
  const safeExpandedNodes = expandedNodes || new Set<string>()
  const isExpanded = safeExpandedNodes.has(node._id)
  
  // Determine if children should be shown:
  // - Level 0: always show children (root level, no accordion)
  // - Level 1: show children (level 2+) only if expanded (accordion closed by default)
  // - Level 2+: always show children (they're already filtered by level 1 parent's expansion state)
  let shouldShowChildren: boolean
  if (node.level < 1) {
    // Level 0: always show children (root level)
    shouldShowChildren = true
  } else if (node.level === 1) {
    // Level 1: show children (level 2+) only if expanded (default: collapsed)
    shouldShowChildren = isExpanded
  } else {
    // Level 2+: always show children (parent level 1 controls visibility)
    // Note: Level 2+ nodes won't be rendered if their level 1 parent is not expanded
    shouldShowChildren = true
  }
  
  return (
    <>
      <TreeRow 
        node={node} 
        renderActions={renderActions} 
        onOpen={onOpen}
        isExpanded={isExpanded}
        onToggleExpand={() => onToggleNode(node._id)}
        showAccordion={showAccordion}
      />
      {shouldShowChildren && (
        <div className={showAccordion ? 'ml-4 border-l border-gray-200' : ''}>
          {node.children.map(child => (
            <TreeNode 
              key={child._id} 
              node={child} 
              renderActions={renderActions} 
              onOpen={onOpen}
              expandedNodes={safeExpandedNodes}
              onToggleNode={onToggleNode}
            />
          ))}
        </div>
      )}
    </>
  )
}

export function AlbumTree({
  albums,
  onReorder,
  renderActions,
  onOpen,
}: {
  albums: AlbumItem[]
  onReorder: (updates: Array<{ id: string; parentAlbumId: string | null; order: number }>) => Promise<void>
  renderActions?: (node: AlbumTreeNode) => React.ReactNode
  onOpen?: (node: AlbumTreeNode) => void
}) {
  const [localAlbums, setLocalAlbums] = useState(albums)
  const [expandedNodes, setExpandedNodes] = useState<Set<string>>(new Set())
  const sensors = useSensors(useSensor(PointerSensor, { activationConstraint: { distance: 5 } }))

  // Sync localAlbums when albums prop changes
  useEffect(() => {
    setLocalAlbums(albums)
  }, [albums])

  // Rebuild tree whenever localAlbums changes
  const tree = useMemo(() => {
    // Ensure all albums have order field
    const normalizedAlbums = localAlbums.map(a => ({
      ...a,
      order: a.order ?? 0
    }))
    return buildTree(normalizedAlbums)
  }, [localAlbums])
  
  const flat = useMemo(() => flatten(tree), [tree])
  
  const toggleNode = (nodeId: string) => {
    setExpandedNodes(prev => {
      const next = new Set(prev)
      if (next.has(nodeId)) {
        next.delete(nodeId)
      } else {
        next.add(nodeId)
      }
      return next
    })
  }

  const handleDragEnd = async (event: DragEndEvent) => {
    const { active, over } = event
    
    if (!over || active.id === over.id) return
    
    const fromIndex = flat.findIndex(n => n._id === active.id)
    const toIndex = flat.findIndex(n => n._id === over.id)
    
    if (fromIndex === -1 || toIndex === -1) return

    const activeNode = flat[fromIndex]
    const overNode = flat[toIndex]
    
    // Prevent moving an album into its own descendant
    const isDescendant = (parentId: string, childId: string): boolean => {
      const child = flat.find(n => n._id === childId)
      if (!child) return false
      if (child.parentAlbumId === parentId) return true
      if (!child.parentAlbumId) return false
      return isDescendant(parentId, child.parentAlbumId)
    }
    
    if (isDescendant(activeNode._id, overNode._id)) {
      console.warn('Cannot move album into its own descendant')
      return
    }

    const updates: Array<{ id: string; parentAlbumId: string | null; order: number }> = []
    
    // Same parent: reorder within siblings
    if ((activeNode.parentAlbumId ?? null) === (overNode.parentAlbumId ?? null)) {
      const siblings = localAlbums
        .filter(a => (a.parentAlbumId ?? null) === (activeNode.parentAlbumId ?? null))
        .sort((a,b) => (a.order - b.order) || a.name.localeCompare(b.name))
      const ids = siblings.map(s => s._id)
      const from = ids.indexOf(activeNode._id)
      const to = ids.indexOf(overNode._id)
      if (from === -1 || to === -1) return
      const newIds = arrayMove(ids, from, to)
      updates.push(...newIds.map((id, idx) => ({ 
        id, 
        parentAlbumId: activeNode.parentAlbumId ?? null, 
        order: idx 
      })))
    } else {
      // Different parent: move to new parent and reorder
      const newParentId = overNode.parentAlbumId ?? null
      
      // Get all siblings in the new parent (including the dragged item)
      const newSiblings = localAlbums
        .filter(a => (a.parentAlbumId ?? null) === newParentId && a._id !== activeNode._id)
        .sort((a,b) => (a.order - b.order) || a.name.localeCompare(b.name))
      
      // Find the position where we're inserting
      const overIndex = newSiblings.findIndex(s => s._id === overNode._id)
      const insertIndex = overIndex >= 0 ? overIndex : newSiblings.length
      
      // Create new order: insert dragged item at the target position
      const newOrder = [...newSiblings]
      newOrder.splice(insertIndex, 0, activeNode as any)
      
      // Update all affected albums
      // 1. Update the moved album's parent and order
      updates.push({
        id: activeNode._id,
        parentAlbumId: newParentId,
        order: insertIndex
      })
      
      // 2. Update order of siblings after insertion point
      newOrder.forEach((album, idx) => {
        if (album._id !== activeNode._id) {
          updates.push({
            id: album._id,
            parentAlbumId: newParentId,
            order: idx
          })
        }
      })
      
      // 3. Reorder siblings in the old parent
      const oldSiblings = localAlbums
        .filter(a => (a.parentAlbumId ?? null) === (activeNode.parentAlbumId ?? null) && a._id !== activeNode._id)
        .sort((a,b) => (a.order - b.order) || a.name.localeCompare(b.name))
      
      oldSiblings.forEach((album, idx) => {
        updates.push({
          id: album._id,
          parentAlbumId: activeNode.parentAlbumId ?? null,
          order: idx
        })
      })
    }
    
    if (updates.length === 0) return
    
    // Optimistically update local state immediately
    setLocalAlbums(prev => {
      const updated = prev.map(a => {
        const u = updates.find(x => x.id === a._id)
        if (u) {
          return { 
            ...a, 
            parentAlbumId: u.parentAlbumId ?? null, 
            order: u.order 
          }
        }
        return a
      })
      return updated
    })
    
    // Save to server
    try {
      await onReorder(updates)
      // After successful reorder, refresh from server to ensure consistency
      // The parent component should handle the refresh via fetchAlbums()
    } catch (error) {
      console.error('Failed to reorder albums:', error)
      // Revert on error - reload from original albums prop
      setLocalAlbums(albums)
      throw error // Re-throw so parent can show error message
    }
  }

  const allItemIds = useMemo(() => flat.map(n => n._id), [flat])

  // Ensure expandedNodes is always a Set
  const safeExpandedNodes = expandedNodes || new Set<string>()

  return (
    <DndContext sensors={sensors} onDragEnd={handleDragEnd}>
      <div className="border rounded-md overflow-hidden bg-background text-foreground">
        <SortableContext items={allItemIds} strategy={verticalListSortingStrategy}>
          {tree.map(parent => (
            <TreeNode 
              key={parent._id} 
              node={parent} 
              renderActions={renderActions} 
              onOpen={onOpen}
              expandedNodes={safeExpandedNodes}
              onToggleNode={toggleNode}
            />
          ))}
        </SortableContext>
      </div>
    </DndContext>
  )
}

export default AlbumTree

// frontend/src/lib/components/AlbumTree.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { currentLanguage } from '$stores/language';
	import { MultiLangUtils } from '$utils/multiLang';
	import { goto } from '$app/navigation';
	import { dndzone } from 'svelte-dnd-action';
	import { getAlbumName } from '$lib/utils/albumUtils';
	import { logger } from '$lib/utils/logger';

	interface Album {
		_id: string;
		name: string | { en?: string; he?: string };
		alias: string;
		parentAlbumId?: string | null;
		level: number;
		order: number;
		photoCount?: number;
		isPublic?: boolean;
		isFeatured?: boolean;
		childAlbumCount?: number;
	}

	interface AlbumTreeNode extends Album {
		children: AlbumTreeNode[];
	}

	export let albums: Album[] = [];
	export let onReorder:
		| ((updates: Array<{ id: string; parentAlbumId: string | null; order: number }>) => Promise<void>)
		| undefined = undefined;
	export let renderActions: ((node: AlbumTreeNode) => any) | undefined = undefined;
	export let onOpen: ((node: AlbumTreeNode) => void) | undefined = undefined;
	export let showAccordion = true;
	export let expandAllByDefault = false; // Option to expand all nodes by default

	let expandedNodes: Set<string> = new Set();
	let localAlbums = albums;
	let albumsInitialized = false;
	let flatItems: AlbumTreeNode[] = [];
	let isDragging = false;

	// Initialize expanded nodes if expandAllByDefault is true
	function initializeExpandedNodes() {
		if (expandAllByDefault && albums.length > 0) {
			const allNodeIds = new Set<string>();
			const collectIds = (nodes: AlbumTreeNode[]) => {
				nodes.forEach(node => {
					if (node.children.length > 0) {
						allNodeIds.add(node._id);
						collectIds(node.children);
					}
				});
			};
			const initialTree = buildTree(albums);
			collectIds(initialTree);
			expandedNodes = allNodeIds;
		}
	}

	// Initialize expanded nodes when albums first load
	$: if (albums.length > 0 && !albumsInitialized && expandAllByDefault) {
		initializeExpandedNodes();
		albumsInitialized = true;
	}

	// Reset flag if albums are cleared
	$: if (albums.length === 0) {
		albumsInitialized = false;
	}

	// Flatten tree for drag and drop
	function flatten(nodes: AlbumTreeNode[], expanded: Set<string>): AlbumTreeNode[] {
		const out: AlbumTreeNode[] = [];
		const walk = (arr: AlbumTreeNode[]) => {
			for (const n of arr) {
				out.push(n);
				if (n.children.length && (n.level < 1 || expanded.has(n._id))) {
					walk(n.children);
				}
			}
		};
		walk(nodes);
		return out;
	}

	function buildTree(albums: Album[]): AlbumTreeNode[] {
		const byId = new Map<string, AlbumTreeNode>();
		albums.forEach((a) => byId.set(a._id, { ...a, children: [] }));
		const roots: AlbumTreeNode[] = [];
		byId.forEach((node) => {
			const parentId = node.parentAlbumId ?? null;
			if (parentId && byId.has(parentId)) {
				byId.get(parentId)!.children.push(node);
			} else {
				roots.push(node);
			}
		});
		const sortRecursive = (nodes: AlbumTreeNode[]) => {
			nodes.sort((a, b) => {
				const orderA = a.order ?? 0;
				const orderB = b.order ?? 0;
				if (orderA !== orderB) {
					return orderA - orderB;
				}
				const nameA = typeof a.name === 'string' ? a.name : a.name?.en || '';
				const nameB = typeof b.name === 'string' ? b.name : b.name?.en || '';
				return nameA.localeCompare(nameB);
			});
			nodes.forEach((n) => sortRecursive(n.children));
		};
		sortRecursive(roots);
		return roots;
	}

	// Album name function is now imported from shared utility

	function toggleNode(nodeId: string) {
		// Create a new Set to trigger reactivity
		const newExpandedNodes = new Set(expandedNodes);
		if (newExpandedNodes.has(nodeId)) {
			newExpandedNodes.delete(nodeId);
		} else {
			newExpandedNodes.add(nodeId);
		}
		expandedNodes = newExpandedNodes;
	}

	function handleNodeClick(node: AlbumTreeNode) {
		if (onOpen) {
			onOpen(node);
		} else {
			goto(`/admin/albums/${node._id}`);
		}
	}

	// Handle drag consider (during drag, for visual feedback)
	function handleDndConsider(event: CustomEvent) {
		const { detail } = event;
		const { items } = detail;
		// Update flatItems with the reordered items from dndzone for visual feedback
		isDragging = true;
		flatItems = items;
	}

	// Handle drag end (when drag is complete)
	async function handleDndEnd(event: CustomEvent) {
		isDragging = false;
		const { detail } = event;
		const { items, info } = detail;

		if (!info) {
			// Reset flatItems from tree if no info
			flatItems = flatten(tree, expandedNodes);
			return;
		}

		const fromIndex = info.initialIndex;
		const toIndex = info.finalIndex;

		if (fromIndex === toIndex) {
			// No change, reset flatItems from tree
			flatItems = flatten(tree, expandedNodes);
			return;
		}

		// Get the original flat list to find the nodes
		const originalFlat = flatten(tree, expandedNodes);
		const activeNode = originalFlat[fromIndex];
		const overNode = originalFlat[toIndex];

		if (!activeNode || !overNode) {
			flatItems = flatten(tree, expandedNodes);
			return;
		}

		// Prevent moving an album into its own descendant
		const isDescendant = (parentId: string, childId: string): boolean => {
			const child = originalFlat.find((n: AlbumTreeNode) => n._id === childId);
			if (!child) return false;
			if (child.parentAlbumId === parentId) return true;
			if (!child.parentAlbumId) return false;
			return isDescendant(parentId, child.parentAlbumId);
		};

		if (isDescendant(activeNode._id, overNode._id)) {
			logger.warn('Cannot move album into its own descendant');
			return;
		}

		const updates: Array<{ id: string; parentAlbumId: string | null; order: number }> = [];

		// Same parent: reorder within siblings
		if ((activeNode.parentAlbumId ?? null) === (overNode.parentAlbumId ?? null)) {
			const siblings = localAlbums
				.filter((a) => (a.parentAlbumId ?? null) === (activeNode.parentAlbumId ?? null))
				.sort((a, b) => (a.order - b.order) || a.name.toString().localeCompare(b.name.toString()));
			const ids = siblings.map((s) => s._id);
			const from = ids.indexOf(activeNode._id);
			const to = ids.indexOf(overNode._id);
			if (from === -1 || to === -1) {
				flatItems = flatten(tree, expandedNodes);
				return;
			}
			// Simple array move
			const newIds = [...ids];
			const [moved] = newIds.splice(from, 1);
			newIds.splice(to, 0, moved);
			updates.push(
				...newIds.map((id, idx) => ({
					id,
					parentAlbumId: activeNode.parentAlbumId ?? null,
					order: idx
				}))
			);
		} else {
			// Different parent: move to new parent and reorder
			const newParentId = overNode.parentAlbumId ?? null;

			// Get all siblings in the new parent (excluding the dragged item)
			const newSiblings = localAlbums
				.filter((a) => (a.parentAlbumId ?? null) === newParentId && a._id !== activeNode._id)
				.sort((a, b) => (a.order - b.order) || a.name.toString().localeCompare(b.name.toString()));

			// Find the position where we're inserting
			const overIndex = newSiblings.findIndex((s) => s._id === overNode._id);
			const insertIndex = overIndex >= 0 ? overIndex : newSiblings.length;

			// Create new order: insert dragged item at the target position
			const newOrder = [...newSiblings];
			newOrder.splice(insertIndex, 0, activeNode as any);

			// Update all affected albums
			// 1. Update the moved album's parent and order
			updates.push({
				id: activeNode._id,
				parentAlbumId: newParentId,
				order: insertIndex
			});

			// 2. Update order of siblings after insertion point
			newOrder.forEach((album, idx) => {
				if (album._id !== activeNode._id) {
					updates.push({
						id: album._id,
						parentAlbumId: newParentId,
						order: idx
					});
				}
			});

			// 3. Reorder siblings in the old parent
			const oldSiblings = localAlbums
				.filter(
					(a) =>
						(a.parentAlbumId ?? null) === (activeNode.parentAlbumId ?? null) &&
						a._id !== activeNode._id
				)
				.sort((a, b) => (a.order - b.order) || a.name.toString().localeCompare(b.name.toString()));

			oldSiblings.forEach((album, idx) => {
				updates.push({
					id: album._id,
					parentAlbumId: activeNode.parentAlbumId ?? null,
					order: idx
				});
			});
		}

		if (updates.length === 0) {
			flatItems = flatten(tree, expandedNodes);
			return;
		}

		// Optimistically update local state
		localAlbums = localAlbums.map((a) => {
			const u = updates.find((x) => x.id === a._id);
			if (u) {
				return {
					...a,
					parentAlbumId: u.parentAlbumId ?? null,
					order: u.order
				};
			}
			return a;
		});

		// Update flatItems from the new tree structure
		const newTree = buildTree(localAlbums);
		flatItems = flatten(newTree, expandedNodes);

		// Save to server
		if (onReorder) {
			try {
				await onReorder(updates);
			} catch (error) {
				logger.error('Failed to reorder albums:', error);
				// Revert on error
				localAlbums = albums;
				flatItems = flatten(tree, expandedNodes);
				throw error;
			}
		}
	}

	// Sync localAlbums when albums prop changes
	$: {
		localAlbums = albums;
	}

	$: tree = buildTree(localAlbums);
	// Make flatItems reactive to both tree and expandedNodes changes
	// Convert Set to Array to ensure Svelte tracks changes properly
	// This ensures that when expandedNodes changes, this reactive statement re-runs
	$: expandedNodesArray = Array.from(expandedNodes).sort();
	// flatItems depends on both tree and expandedNodesArray to ensure reactivity
	// We reference expandedNodesArray to ensure Svelte tracks changes to expandedNodes
	// Only update flatItems from tree if we're not currently dragging
	$: {
		// Reference expandedNodesArray to ensure reactivity
		const _ = expandedNodesArray;
		if (!isDragging) {
			flatItems = flatten(tree, expandedNodes);
		}
	}
</script>

<div class="album-tree">
	<div
		use:dndzone={{
			items: flatItems,
			type: 'album-tree',
			dragDisabled: false,
			dropFromOthersDisabled: true,
			dropTargetStyle: {
				outline: '2px dashed rgba(59, 130, 246, 0.5)',
				backgroundColor: 'rgba(59, 130, 246, 0.1)'
			},
			dragDisabledStyle: {
				opacity: '0.5',
				cursor: 'not-allowed'
			}
		}}
		on:consider={handleDndConsider}
		on:finalize={handleDndEnd}
	>
		{#each flatItems as node (node._id)}
			<div class="album-tree-node" style="padding-left: {node.level * 1.5}rem;" data-id={node._id}>
				<div class="flex items-center gap-2 py-2 px-3 hover:bg-gray-50 rounded-md group cursor-move">
					{#if showAccordion && node.children && node.children.length > 0}
						<button
							type="button"
							on:click|stopPropagation={() => toggleNode(node._id)}
							class="flex-shrink-0 w-6 h-6 flex items-center justify-center text-gray-400 hover:text-gray-600"
							aria-label={expandedNodes.has(node._id) ? 'Collapse' : 'Expand'}
						>
							<svg
								class="w-4 h-4 transition-transform {expandedNodes.has(node._id) ? 'rotate-90' : ''}"
								fill="none"
								viewBox="0 0 24 24"
								stroke="currentColor"
							>
								<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 5l7 7-7 7" />
							</svg>
						</button>
					{:else}
						<div class="w-6"></div>
					{/if}

					<div class="flex-1 flex items-center gap-3 min-w-0">
						<!-- Drag handle - visible icon -->
						<div 
							class="drag-handle flex-shrink-0 cursor-move text-gray-600 hover:text-gray-800 p-1.5 rounded hover:bg-gray-200 transition-colors flex items-center justify-center border border-gray-300" 
							title="Drag to reorder"
							style="user-select: none; min-width: 28px; height: 28px; pointer-events: auto;"
						>
							<span class="text-base font-bold text-gray-600 leading-none" style="line-height: 1;">⋮⋮</span>
						</div>
						<button
							type="button"
							on:click={() => handleNodeClick(node)}
							class="flex-1 text-left flex items-center gap-3 min-w-0"
						>
							<div class="flex-1 min-w-0">
								<div class="flex items-center gap-2">
									<span class="font-medium text-gray-900 truncate">{getAlbumName(node)}</span>
									{#if node.isFeatured}
										<span
											class="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-yellow-100 text-yellow-800"
										>
											⭐ Featured
										</span>
									{/if}
									{#if !node.isPublic}
										<span
											class="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-gray-100 text-gray-800"
										>
											Private
										</span>
									{/if}
								</div>
								<div class="text-sm text-gray-500">
									{node.photoCount || 0} photos • Level {node.level}
								</div>
							</div>
						</button>

						{#if renderActions}
							<div class="flex-shrink-0 opacity-0 group-hover:opacity-100 transition-opacity">
								{@html renderActions(node)}
							</div>
						{/if}
					</div>
				</div>

			</div>
		{/each}
	</div>
</div>

<style>
	.album-tree {
		display: flex;
		flex-direction: column;
		gap: 0.25rem;
	}

	.album-tree-node {
		width: 100%;
	}
</style>
