// frontend/src/lib/page-builder/modules/AlbumGallery/PhotoCard.svelte
<script lang="ts">
	import { currentLanguage } from '$stores/language';
	import { MultiLangUtils } from '$lib/utils/multiLang';

	export let photo: any;
	export let coverAspectClass: string = 'aspect-video';
	export let cardFieldOrder: Array<'title' | 'cover' | 'description' | 'photoCount' | 'featuredBadge'> = ['cover', 'title', 'description', 'photoCount', 'featuredBadge'];
	export let showTitle = true;
	export let showCover = true;
	export let showDescription = true;
	export let descriptionLines = 2;
	export let showFeaturedBadge = true;

	$: photoTitle = photo?.name ?? photo?.title ?? photo?.originalName ?? 'Photo';
	$: photoUrl = photo?.coverUrl ?? photo?.thumbnailUrl ?? photo?.previewUrl ?? photo?.url ?? photo?.imageUrl ?? '';
</script>

<div class="group bg-white dark:bg-gray-800 rounded-xl shadow-md dark:shadow-gray-900/50 overflow-hidden hover:shadow-xl dark:hover:shadow-gray-900/70 transition-all duration-300 transform hover:-translate-y-1">
	<div class="p-6">
		{#each cardFieldOrder as field}
			{#if field === 'title' && showTitle}
				<h3 class="text-xl font-semibold text-gray-900 dark:text-gray-100 mb-3 group-hover:text-blue-600 dark:group-hover:text-blue-400 transition-colors">
					{photoTitle}
				</h3>
			{:else if field === 'cover' && showCover}
				<div class="{coverAspectClass} mb-3 bg-linear-to-b from-gray-200 to-gray-300 dark:from-gray-700 dark:to-gray-600 flex items-center justify-center overflow-hidden">
					{#if photoUrl}
						<img src={photoUrl} alt={photoTitle} class="w-full h-full object-cover" />
					{:else}
						<div class="text-gray-400 dark:text-gray-500 text-xl">No image</div>
					{/if}
				</div>
			{:else if field === 'description' && showDescription && photo?.description}
				<div class="text-gray-600 dark:text-gray-300 text-sm mb-3">
					<div
						class="prose prose-sm max-w-none"
						style="display:-webkit-box;-webkit-line-clamp:{descriptionLines};-webkit-box-orient:vertical;overflow:hidden;"
					>
						{@html (() => {
							if (typeof photo.description === 'string') return photo.description;
							const html = MultiLangUtils.getHTMLValue(photo.description as Record<string, string>, $currentLanguage);
							if (html) return html;
							return MultiLangUtils.getTextValue(photo.description as Record<string, string>, $currentLanguage) || '';
						})()}
					</div>
				</div>
			{:else if field === 'featuredBadge' && showFeaturedBadge && photo?.isFeatured}
				<div class="mb-2">
					<span class="inline-flex items-center px-2 py-1 rounded text-xs font-medium bg-yellow-100 dark:bg-yellow-900/40 text-yellow-800 dark:text-yellow-200">
						⭐ Featured
					</span>
				</div>
			{/if}
		{/each}
	</div>
</div>

// src/components/search/PhotoCard.tsx
'use client'

import { useState } from 'react'
// Using regular img tag for API-served images instead of Next.js Image
import { useLanguage } from '@/contexts/LanguageContext'
import { MultiLangUtils } from '@/types/multi-lang'
import { Photo } from '@/types'
import { Image as ImageIcon } from '@/lib/icons'

interface PhotoCardProps {
  photo: Photo
  viewMode?: 'grid' | 'list' // Optional, defaults to grid
  onClick?: () => void
}

export function PhotoCard({ photo, viewMode, onClick }: PhotoCardProps) {
  const { currentLanguage } = useLanguage()
  const [imageError, setImageError] = useState(false)
  
  // Construct image URL from storage info
  const getImageUrl = () => {
    if (!photo.storage) return ''
    
    // If thumbnailPath exists, use it (should already be a full URL from API)
    if (photo.storage.thumbnailPath) {
      // If it's already a full URL, use it as-is
      if (photo.storage.thumbnailPath.startsWith('/api/storage/serve/') || photo.storage.thumbnailPath.startsWith('http')) {
        return photo.storage.thumbnailPath
      }
      // Otherwise construct the URL
      const provider = photo.storage.provider || 'local'
      return `/api/storage/serve/${provider}/${encodeURIComponent(photo.storage.thumbnailPath)}`
    }
    
    // Fallback to url if available
    if (photo.storage.url) {
      if (photo.storage.url.startsWith('/api/storage/serve/') || photo.storage.url.startsWith('http')) {
        return photo.storage.url
      }
      return `/api/storage/serve/${photo.storage.provider || 'local'}/${encodeURIComponent(photo.storage.url)}`
    }
    
    return ''
  }
  
  const imageUrl = getImageUrl()
  
  // Grid view only (matching album view style)
  return (
    <div 
      className="bg-white rounded-lg shadow-sm border overflow-hidden hover:shadow-lg transition-all duration-300 cursor-pointer group"
      onClick={onClick}
    >
      {/* Image - matching album view style */}
      <div className="aspect-square bg-gray-200 relative overflow-hidden">
        {!imageError && imageUrl ? (
          <img
            src={imageUrl}
            alt={(typeof photo.title === 'string' ? photo.title : MultiLangUtils.getTextValue(photo.title as any, currentLanguage)) || photo.filename}
            className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300"
            onError={() => setImageError(true)}
          />
        ) : (
          <div className="w-full h-full flex items-center justify-center text-gray-400">
            <ImageIcon className="h-12 w-12" />
          </div>
        )}
      </div>
      
      {/* Content - matching album view style */}
      <div className="p-4">
        <h3 className="text-sm font-medium text-gray-900 truncate">
          {(typeof photo.title === 'string' ? photo.title : MultiLangUtils.getTextValue(photo.title as any, currentLanguage)) || photo.filename}
        </h3>
      </div>
    </div>
  )
}
