// frontend/src/routes/mobile/search/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { page } from '$app/stores';
	import { goto } from '$app/navigation';
	import { MultiLangUtils } from '$lib/utils/multiLang';
	import { currentLanguage } from '$lib/stores/language';

	interface SearchResult {
		_id: string;
		type: 'photo' | 'album' | 'person' | 'location';
		title?: string | { en?: string; he?: string };
		name?: string | { en?: string; he?: string };
		alias?: string;
		thumbnailUrl?: string;
		description?: string;
	}

	let query = $page.url.searchParams.get('q') || '';
	let type: 'all' | 'photos' | 'albums' | 'people' | 'locations' =
		($page.url.searchParams.get('type') as 'all' | 'photos' | 'albums' | 'people' | 'locations') || 'all';
	let results: SearchResult[] = [];
	let loading = false;
	let error: string | null = null;

	onMount(() => {
		if (query) {
			performSearch();
		}
	});

	$: if ($page.url.searchParams.get('q') !== query) {
		query = $page.url.searchParams.get('q') || '';
		if (query) {
			performSearch();
		}
	}

	async function performSearch() {
		if (!query.trim()) {
			results = [];
			return;
		}

		loading = true;
		error = null;

		try {
			const searchParams = new URLSearchParams({
				q: query,
				type: type
			});

			const response = await fetch(`/api/search?${searchParams}`);
			const data = await response.json();

			if (data.success) {
				results = [
					...(data.data.photos || []),
					...(data.data.albums || []),
					...(data.data.people || []),
					...(data.data.locations || [])
				];
			} else {
				error = data.error || 'Search failed';
			}
		} catch (err) {
			error = 'Search failed';
			console.error('Search error:', err);
		} finally {
			loading = false;
		}
	}

	function getResultTitle(result: SearchResult): string {
		if (result.title) {
			return typeof result.title === 'string'
				? result.title
				: MultiLangUtils.getTextValue(result.title, $currentLanguage);
		}
		if (result.name) {
			return typeof result.name === 'string'
				? result.name
				: MultiLangUtils.getTextValue(result.name, $currentLanguage);
		}
		return result.alias || 'Untitled';
	}
</script>

<svelte:head>
	<title>Mobile Search - OpenShutter</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
	<meta name="theme-color" content="#2563eb" />
</svelte:head>

<div class="min-h-screen bg-gray-50">
	<!-- Mobile Header -->
	<header class="bg-white shadow-sm sticky top-0 z-10">
		<div class="px-4 py-3">
			<div class="flex items-center justify-between mb-4">
				<h1 class="text-xl font-bold text-gray-900">Search</h1>
				<button
					on:click={() => goto('/')}
					class="text-blue-600 hover:text-blue-700 text-sm font-medium"
				>
					Close
				</button>
			</div>

			<!-- Search Input -->
			<div class="flex gap-2">
				<input
					type="text"
					bind:value={query}
					on:keydown={(e) => {
						if (e.key === 'Enter') performSearch();
					}}
					placeholder="Search photos, albums, people..."
					class="flex-1 px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500"
				/>
				<button
					on:click={performSearch}
					class="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700"
				>
					Search
				</button>
			</div>

			<!-- Type Filter -->
			<div class="mt-3 flex gap-2 overflow-x-auto">
				<button
					on:click={() => {
						type = 'all';
						if (query) performSearch();
					}}
					class="px-3 py-1 text-sm rounded-full whitespace-nowrap {type === 'all'
						? 'bg-blue-600 text-white'
						: 'bg-gray-200 text-gray-700'}"
				>
					All
				</button>
				<button
					on:click={() => {
						type = 'photos';
						if (query) performSearch();
					}}
					class="px-3 py-1 text-sm rounded-full whitespace-nowrap {type === 'photos'
						? 'bg-blue-600 text-white'
						: 'bg-gray-200 text-gray-700'}"
				>
					Photos
				</button>
				<button
					on:click={() => {
						type = 'albums';
						if (query) performSearch();
					}}
					class="px-3 py-1 text-sm rounded-full whitespace-nowrap {type === 'albums'
						? 'bg-blue-600 text-white'
						: 'bg-gray-200 text-gray-700'}"
				>
					Albums
				</button>
				<button
					on:click={() => {
						type = 'people';
						if (query) performSearch();
					}}
					class="px-3 py-1 text-sm rounded-full whitespace-nowrap {type === 'people'
						? 'bg-blue-600 text-white'
						: 'bg-gray-200 text-gray-700'}"
				>
					People
				</button>
				<button
					on:click={() => {
						type = 'locations';
						if (query) performSearch();
					}}
					class="px-3 py-1 text-sm rounded-full whitespace-nowrap {type === 'locations'
						? 'bg-blue-600 text-white'
						: 'bg-gray-200 text-gray-700'}"
				>
					Locations
				</button>
			</div>
		</div>
	</header>

	<!-- Results -->
	<main class="pb-8">
		{#if loading}
			<div class="flex items-center justify-center py-12">
				<div class="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600"></div>
				<p class="ml-4 text-gray-600">Searching...</p>
			</div>
		{:else if error}
			<div class="px-4 py-8">
				<div class="bg-red-50 border border-red-200 rounded-md p-4">
					<p class="text-red-800">{error}</p>
				</div>
			</div>
		{:else if results.length > 0}
			<div class="grid grid-cols-2 gap-4 p-4">
				{#each results as item}
					<button
						on:click={() => {
							if (item.type === 'album') {
								goto(`/albums/${item.alias || item._id}`);
							} else if (item.type === 'photo') {
								goto(`/photos/${item._id}`);
							} else {
								goto(`/${item.type}/${item.alias || item._id}`);
							}
						}}
						class="bg-white rounded-lg shadow overflow-hidden hover:shadow-lg transition-shadow text-left"
					>
						{#if item.thumbnailUrl}
							<img
								src={item.thumbnailUrl}
								alt={getResultTitle(item)}
								class="w-full h-32 object-cover"
							/>
						{:else}
							<div class="w-full h-32 bg-gray-200 flex items-center justify-center">
								<svg class="w-8 h-8 text-gray-400" fill="none" viewBox="0 0 24 24" stroke="currentColor">
									<path
										stroke-linecap="round"
										stroke-linejoin="round"
										stroke-width="2"
										d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z"
									/>
								</svg>
							</div>
						{/if}
						<div class="p-3">
							<h3 class="text-sm font-medium text-gray-900 truncate">{getResultTitle(item)}</h3>
							<p class="text-xs text-gray-500 capitalize mt-1">{item.type}</p>
						</div>
					</button>
				{/each}
			</div>
		{:else if query.trim()}
			<div class="text-center py-12 px-4">
				<p class="text-gray-600">No results found for "{query}".</p>
			</div>
		{:else}
			<div class="text-center py-12 px-4">
				<p class="text-gray-600">Start typing to search...</p>
			</div>
		{/if}
	</main>
</div>

// src/templates/minimal/pages/Search.tsx
'use client'

import { useState, useEffect } from 'react'
import { useSearchParams } from 'next/navigation'
import { useI18n } from '@/hooks/useI18n'
import { SearchFilters } from '@/components/search/SearchFilters'
import { SearchResults } from '@/components/search/SearchResults'
import Header from '../components/Header'
import Footer from '../components/Footer'

interface SearchFilters {
  tags: string[]
  albumId: string | null
  dateFrom: string
  dateTo: string
  storageProvider: string
  isPublic: string
  mine: boolean
}

interface SearchResult {
  _id: string
  type: 'photo' | 'album' | 'person'
  title: string
  description?: string
  thumbnail?: string
  albumId?: string
  albumName?: string
  createdAt: string
  updatedAt: string
  isPublished?: boolean
  tags?: string[]
  people?: string[]
  location?: {
    name: string
    coordinates?: [number, number]
  }
}

export default function SearchPage() {
  const { t } = useI18n()
  const searchParams = useSearchParams()
  const query = searchParams.get('q') || ''

  const [filters, setFilters] = useState<SearchFilters>({
    tags: [],
    albumId: null,
    dateFrom: '',
    dateTo: '',
    storageProvider: '',
    isPublic: '',
    mine: false
  })

  const [results, setResults] = useState<SearchResult[]>([])
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [type, setType] = useState<'all' | 'photos' | 'albums' | 'people'>('all')
  const [sortBy, setSortBy] = useState<'relevance' | 'date' | 'filename' | 'size'>('relevance')
  const [sortOrder, setSortOrder] = useState<'asc' | 'desc'>('desc')

  // Search function
  const performSearch = async () => {
    if (!query.trim()) {
      setResults([])
      return
    }

    setLoading(true)
    setError(null)

    try {
      const searchParams = new URLSearchParams({
        q: query,
        type: type,
        ...(filters.tags.length > 0 && { tags: filters.tags.join(',') }),
        ...(filters.albumId && { albumId: filters.albumId }),
        ...(filters.dateFrom && { dateFrom: filters.dateFrom }),
        ...(filters.dateTo && { dateTo: filters.dateTo }),
        ...(filters.storageProvider && { storageProvider: filters.storageProvider }),
        ...(filters.isPublic !== undefined && { isPublic: String(filters.isPublic) }),
        ...(filters.mine && { mine: 'true' }),
        sortBy,
        sortOrder
      })

      const response = await fetch(`/api/search?${searchParams}`)
      const data = await response.json()

      if (data.success) {
        setResults(data.results || [])
      } else {
        setError(data.error || 'Search failed')
      }
    } catch (err) {
      setError('Search failed')
      console.error('Search error:', err)
    } finally {
      setLoading(false)
    }
  }

  // Perform search when query or filters change
  useEffect(() => {
    performSearch()
  }, [query, type, filters, sortBy, sortOrder])

  const handleFilterChange = (newFilters: Partial<SearchFilters>) => {
    setFilters(prev => ({ ...prev, ...newFilters }))
  }

  const handleTypeChange = (newType: 'all' | 'photos' | 'albums' | 'people') => {
    setType(newType)
  }

  const handleSortChange = (newSortBy: 'relevance' | 'date' | 'filename' | 'size', newSortOrder: 'asc' | 'desc') => {
    setSortBy(newSortBy)
    setSortOrder(newSortOrder)
  }

  const clearFilters = () => {
    setFilters({
      tags: [],
      albumId: null,
      dateFrom: '',
      dateTo: '',
      storageProvider: '',
      isPublic: '',
      mine: false
    })
  }

  const hasActiveFilters = Object.values(filters).some(value => 
    Array.isArray(value) ? value.length > 0 : value !== '' && value !== false && value !== null
  )

  return (
    <div className="min-h-screen bg-background">
      <Header />
      
      <main className="container mx-auto px-4 py-8">
        {/* Search Header */}
        <div className="text-center mb-8">
          <h1 className="text-3xl font-bold text-foreground mb-2">
            {t('search.title', 'Search')}
          </h1>
          <p className="text-muted-foreground">
            {t('search.subtitle', 'Find what you\'re looking for')}
          </p>
        </div>

        {/* Search Query Display */}
        {query && (
          <div className="bg-card rounded-lg p-4 mb-6 border">
            <div className="flex items-center justify-between">
              <div>
                <h2 className="text-lg font-semibold text-foreground mb-1">
                  {t('search.resultsFor', 'Results for')}: "{query}"
                </h2>
                <p className="text-muted-foreground text-sm">
                  {loading ? t('search.searching', 'Searching...') : 
                   `${results.length} ${t('search.resultsFound', 'results found')}`}
                </p>
              </div>
              {hasActiveFilters && (
                <button
                  onClick={clearFilters}
                  className="px-3 py-1 text-sm bg-secondary hover:bg-secondary/80 text-secondary-foreground rounded transition-colors"
                >
                  {t('search.clearFilters', 'Clear Filters')}
                </button>
              )}
            </div>
          </div>
        )}

        <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
          {/* Filters Sidebar */}
          <div className="lg:col-span-1">
            <div className="bg-card rounded-lg p-4 border sticky top-8">
              <SearchFilters
                filters={filters}
                onFilterChange={handleFilterChange}
                type={type}
                onTypeChange={handleTypeChange}
                sortBy={sortBy}
                sortOrder={sortOrder}
                onSortChange={handleSortChange}
              />
            </div>
          </div>

          {/* Results */}
          <div className="lg:col-span-3">
            {error && (
              <div className="bg-destructive/10 border border-destructive/20 rounded-lg p-4 mb-6">
                <p className="text-destructive">{error}</p>
              </div>
            )}

            {loading && (
              <div className="text-center py-8">
                <div className="inline-block animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
                <p className="mt-2 text-muted-foreground">
                  {t('search.searching', 'Searching...')}
                </p>
              </div>
            )}

            {!loading && !error && (
              <SearchResults 
                results={{
                  photos: results.filter(r => r.type === 'photo') as any[],
                  albums: results.filter(r => r.type === 'album') as any[],
                  people: results.filter(r => r.type === 'person') as any[],
                  totalPhotos: results.filter(r => r.type === 'photo').length,
                  totalAlbums: results.filter(r => r.type === 'album').length,
                  totalPeople: results.filter(r => r.type === 'person').length,
                  page: 1,
                  limit: 20,
                  hasMore: false
                }}
                query={query}
                type={type}
                loading={loading}
                error={error}
                onLoadMore={() => {}}
              />
            )}

            {!loading && !error && results.length === 0 && query && (
              <div className="text-center py-8">
                <div className="text-4xl text-muted-foreground mb-4">🔍</div>
                <h3 className="text-lg font-semibold text-foreground mb-2">
                  {t('search.noResults', 'No Results Found')}
                </h3>
                <p className="text-muted-foreground mb-4">
                  {t('search.tryDifferentSearch', 'Try adjusting your search terms or filters')}
                </p>
                <button
                  onClick={clearFilters}
                  className="px-4 py-2 bg-primary hover:bg-primary/90 text-primary-foreground rounded transition-colors"
                >
                  {t('search.clearAllFilters', 'Clear All Filters')}
                </button>
              </div>
            )}
          </div>
        </div>
      </main>

      <Footer />
    </div>
  )
}
