// frontend/src/routes/admin/videos/upload/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { page } from '$app/stores';
	import { goto } from '$app/navigation';
	import { MultiLangUtils } from '$lib/utils/multiLang';
	import { currentLanguage } from '$stores/language';
	import { adminToast } from '$lib/admin/adminToast';
	import { adminBtnPrimarySm, adminBtnSecondary, adminRingPrimary } from '$lib/admin/admin-cerberus';
	import { logger } from '$lib/utils/logger';

	interface VideoMetadata {
		duration?: number;
		width?: number;
		height?: number;
	}

	let albumId: string | null = $state(null);
	let returnTo: string | null = $state(null);
	let albumName = $state('');
	let fileInput: HTMLInputElement | null = $state(null);
	let selectedFile: File | null = $state(null);
	let metadata: VideoMetadata | null = $state(null);
	let progress = $state(0);
	let isUploading = $state(false);
	let error: string | null = $state(null);

	const MAX_SIZE = 500 * 1024 * 1024; // 500MB

	onMount(() => {
		albumId = $page.url.searchParams.get('albumId');
		returnTo = $page.url.searchParams.get('returnTo');
		if (albumId) fetchAlbumName();
	});

	async function fetchAlbumName() {
		if (!albumId) return;
		try {
			const res = await fetch(`/api/admin/albums/${albumId}`);
			if (!res.ok) return;
			const result = await res.json();
			const album = result.data || result;
			const name = album.name;
			albumName =
				typeof name === 'string'
					? name
					: MultiLangUtils.getTextValue(name, $currentLanguage) || 'Album';
		} catch (err) {
			logger.error('Failed to fetch album name:', err);
		}
	}

	/**
	 * Read duration + intrinsic dimensions from the picked MP4 by loading it into a
	 * hidden `<video>`. Non-blocking: if the browser can't parse the file, we simply
	 * omit the fields (backend defaults them).
	 */
	function extractMetadata(file: File): Promise<VideoMetadata> {
		return new Promise((resolve) => {
			const url = URL.createObjectURL(file);
			const v = document.createElement('video');
			v.preload = 'metadata';
			const cleanup = () => {
				URL.revokeObjectURL(url);
				v.remove();
			};
			v.onloadedmetadata = () => {
				const out: VideoMetadata = {
					duration: Number.isFinite(v.duration) ? Math.round(v.duration) : undefined,
					width: v.videoWidth || undefined,
					height: v.videoHeight || undefined
				};
				cleanup();
				resolve(out);
			};
			v.onerror = () => {
				cleanup();
				resolve({});
			};
			v.src = url;
		});
	}

	async function handleFileSelected(files: FileList | null) {
		error = null;
		if (!files || files.length === 0) return;
		const file = files[0];
		if (file.type !== 'video/mp4') {
			error = `Only MP4 videos are supported (got ${file.type || 'unknown'}).`;
			return;
		}
		if (file.size > MAX_SIZE) {
			error = `File is ${(file.size / 1024 / 1024).toFixed(1)}MB — maximum is ${MAX_SIZE / 1024 / 1024}MB.`;
			return;
		}
		selectedFile = file;
		metadata = await extractMetadata(file);
	}

	function upload() {
		if (!selectedFile || !albumId || isUploading) return;
		isUploading = true;
		progress = 0;
		error = null;

		const form = new FormData();
		form.append('file', selectedFile);
		form.append('albumId', albumId);
		if (metadata?.duration != null) form.append('duration', String(metadata.duration));
		if (metadata?.width != null) form.append('width', String(metadata.width));
		if (metadata?.height != null) form.append('height', String(metadata.height));

		const xhr = new XMLHttpRequest();
		xhr.open('POST', '/api/videos/upload');
		xhr.withCredentials = true;
		xhr.upload.addEventListener('progress', (e) => {
			if (e.lengthComputable) progress = Math.round((e.loaded / e.total) * 100);
		});
		xhr.onload = () => {
			isUploading = false;
			if (xhr.status >= 200 && xhr.status < 300) {
				let body: any = null;
				try {
					body = xhr.responseText ? JSON.parse(xhr.responseText) : null;
				} catch {
					body = null;
				}
				if (body?.skipped) {
					adminToast.info({
						title: 'Video already exists',
						description: body.reason || 'Skipped duplicate.'
					});
				} else {
					adminToast.success({
						title: 'Video uploaded',
						description: selectedFile?.name || 'Upload complete'
					});
				}
				goto(returnTo || `/admin/albums/${albumId}`);
			} else {
				let msg = `Upload failed (${xhr.status})`;
				try {
					const body = JSON.parse(xhr.responseText || '{}');
					msg = body.message || body.error || msg;
				} catch {
					/* keep default */
				}
				error = msg;
				adminToast.error({ title: 'Upload failed', description: msg });
			}
		};
		xhr.onerror = () => {
			isUploading = false;
			error = 'Network error during upload.';
			adminToast.error({ title: 'Upload failed', description: error });
		};
		xhr.send(form);
	}

	function reset() {
		selectedFile = null;
		metadata = null;
		progress = 0;
		error = null;
		if (fileInput) fileInput.value = '';
	}
</script>

<svelte:head>
	<title>Upload Video</title>
</svelte:head>

<div class="min-h-screen bg-(--color-surface-50-950) p-6">
	<div class="mx-auto max-w-2xl">
		<div class="mb-6 flex items-center justify-between">
			<div>
				<h1 class="text-2xl font-bold text-(--color-surface-950-50)">Upload Video</h1>
				{#if albumName}
					<p class="mt-1 text-sm text-(--color-surface-600-400)">to album: {albumName}</p>
				{/if}
			</div>
			<a href={returnTo || (albumId ? `/admin/albums/${albumId}` : '/admin/albums')} class={adminBtnSecondary}>
				Cancel
			</a>
		</div>

		{#if !albumId}
			<div class="mb-4 rounded-md bg-red-50 p-4 text-sm text-red-700">
				No <code>albumId</code> in URL. Upload requires a target album.
			</div>
		{/if}

		<div class="card preset-outlined-surface-200-800 bg-surface-50-950 p-6">
			<label class="block">
				<span class="mb-2 block text-sm font-medium text-(--color-surface-950-50)">
					MP4 file (up to 500 MB)
				</span>
				<input
					bind:this={fileInput}
					type="file"
					accept="video/mp4"
					disabled={isUploading || !albumId}
					onchange={(e) => handleFileSelected((e.currentTarget as HTMLInputElement).files)}
					class="block w-full text-sm text-(--color-surface-700-300)
						file:mr-4 file:rounded-md file:border-0 file:bg-(--color-primary-500) file:px-4 file:py-2
						file:text-sm file:font-medium file:text-white hover:file:bg-(--color-primary-600)"
				/>
			</label>

			{#if selectedFile}
				<div class="mt-4 rounded-md bg-(--color-surface-100-800) p-3 text-sm text-(--color-surface-800-200)">
					<div class="font-medium">{selectedFile.name}</div>
					<div class="mt-1 text-xs opacity-80">
						{(selectedFile.size / 1024 / 1024).toFixed(1)} MB
						{#if metadata?.duration != null}
							· {metadata.duration}s
						{/if}
						{#if metadata?.width != null && metadata?.height != null}
							· {metadata.width}×{metadata.height}
						{/if}
					</div>
				</div>
			{/if}

			{#if isUploading}
				<div class="mt-4">
					<div class="mb-1 flex justify-between text-xs text-(--color-surface-700-300)">
						<span>Uploading…</span>
						<span>{progress}%</span>
					</div>
					<div class="h-2 w-full overflow-hidden rounded bg-(--color-surface-200-700)">
						<div
							class="h-full bg-(--color-primary-500) transition-all"
							style="width: {progress}%;"
						></div>
					</div>
				</div>
			{/if}

			{#if error}
				<div class="mt-4 rounded-md bg-red-50 p-3 text-sm text-red-700">{error}</div>
			{/if}

			<div class="mt-6 flex gap-2">
				<button
					type="button"
					onclick={upload}
					disabled={!selectedFile || !albumId || isUploading}
					class="{adminBtnPrimarySm} {adminRingPrimary} disabled:opacity-50"
				>
					{isUploading ? `Uploading… ${progress}%` : 'Upload'}
				</button>
				<button
					type="button"
					onclick={reset}
					disabled={isUploading || (!selectedFile && !error)}
					class={adminBtnSecondary}
				>
					Reset
				</button>
			</div>
		</div>
	</div>
</div>

// frontend/src/app/admin/photos/upload/page.tsx
'use client'

import dynamic from 'next/dynamic'

import { useState, useCallback, useEffect } from 'react'
import { Suspense } from 'react'
import { useSearchParams, useRouter } from 'next/navigation'
import { useDropzone } from 'react-dropzone'
import Link from 'next/link'
import AdminGuard from '@/components/AdminGuard'
import Header from '@/templates/default/components/Header'
import Footer from '@/templates/default/components/Footer'
import { MultiLangUtils } from '@/types/multi-lang'
import { useLanguage } from '@/contexts/LanguageContext'

interface UploadProgress {
  file: File
  progress: number
  status: 'uploading' | 'success' | 'error'
  error?: string
}

function PhotoUploadPageContent() {
  const searchParams = useSearchParams()
  const router = useRouter()
  const { currentLanguage } = useLanguage()
  const albumId = searchParams.get('albumId')
  
  const [uploads, setUploads] = useState<UploadProgress[]>([])
  const [isUploading, setIsUploading] = useState(false)
  const [albumName, setAlbumName] = useState<string>('')
  const [error, setError] = useState<string | null>(null)

  // Fetch album name on component mount
  useEffect(() => {
    if (albumId) {
      fetchAlbumName()
    }
  }, [albumId])

  const fetchAlbumName = async () => {
    try {
      const response = await fetch(`/api/albums/${albumId}`)
      if (response.ok) {
        const result = await response.json()
        if (result.success) {
          // Handle multilingual album name - extract text value using MultiLangUtils
          const name = result.data.name
          const nameText = typeof name === 'string' 
            ? name 
            : MultiLangUtils.getTextValue(name, currentLanguage) || 'Album'
          setAlbumName(nameText)
        }
      }
    } catch (error) {
      console.error('Failed to fetch album name:', error)
    }
  }

  const onDrop = useCallback((acceptedFiles: File[]) => {
    if (!albumId) {
      setError('No album selected for upload')
      return
    }

    // Initialize upload progress for each file
    const newUploads: UploadProgress[] = acceptedFiles.map(file => ({
      file,
      progress: 0,
      status: 'uploading'
    }))

    setUploads(prev => [...prev, ...newUploads])
    setIsUploading(true)
    setError(null)

    // Upload each file
    acceptedFiles.forEach((file, index) => {
      uploadFile(file, newUploads.length + uploads.length - acceptedFiles.length + index)
    })
  }, [albumId, uploads.length])

  const uploadFile = async (file: File, uploadIndex: number) => {
    const formData = new FormData()
    formData.append('file', file)
    formData.append('albumId', albumId!)

    try {
      const xhr = new XMLHttpRequest()
      
      // Track upload progress
      xhr.upload.addEventListener('progress', (event) => {
        if (event.lengthComputable) {
          const progress = Math.round((event.loaded / event.total) * 100)
          setUploads(prev => prev.map((upload, index) => 
            index === uploadIndex ? { ...upload, progress } : upload
          ))
        }
      })

      // Handle upload completion
      xhr.addEventListener('load', () => {
        if (xhr.status === 200) {
          const response = JSON.parse(xhr.responseText)
          if (response.success) {
            setUploads(prev => prev.map((upload, index) => 
              index === uploadIndex ? { ...upload, status: 'success', progress: 100 } : upload
            ))
          } else {
            setUploads(prev => prev.map((upload, index) => 
              index === uploadIndex ? { ...upload, status: 'error', error: response.error } : upload
            ))
          }
        } else {
          setUploads(prev => prev.map((upload, index) => 
            index === uploadIndex ? { ...upload, status: 'error', error: 'Upload failed' } : upload
          ))
        }
      })

      // Handle upload error
      xhr.addEventListener('error', () => {
        setUploads(prev => prev.map((upload, index) => 
          index === uploadIndex ? { ...upload, status: 'error', error: 'Network error' } : upload
        ))
      })

      xhr.open('POST', '/api/photos/upload')
      xhr.send(formData)
    } catch (error) {
      console.error('Upload error:', error)
      setUploads(prev => prev.map((upload, index) => 
        index === uploadIndex ? { ...upload, status: 'error', error: 'Upload failed' } : upload
      ))
    }
  }

  const { getRootProps, getInputProps, isDragActive } = useDropzone({
    onDrop,
    accept: {
      'image/*': ['.jpeg', '.jpg', '.png', '.gif', '.bmp', '.webp']
    },
    multiple: true
  })

  const handleFinish = () => {
    if (albumId) {
      router.push(`/admin/albums/${albumId}`)
    } else {
      router.push('/admin')
    }
  }

  const allUploadsComplete = uploads.length > 0 && uploads.every(upload => upload.status !== 'uploading')
  const hasErrors = uploads.some(upload => upload.status === 'error')

  return (
    <AdminGuard>
      <div className="min-h-screen bg-gray-50">
        <Header />
        
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
          {/* Header */}
          <div className="flex items-center justify-between mb-8">
            <div>
              <h1 className="text-3xl font-bold text-gray-900">Upload Photos</h1>
              {albumName && (
                <p className="mt-2 text-gray-600">
                  Uploading to album: <span className="font-medium">{albumName}</span>
                </p>
              )}
            </div>
            <div className="flex space-x-3">
              <Link href={albumId ? `/admin/albums/${albumId}` : "/admin"} className="btn-secondary">
                {albumId ? 'Back to Album' : 'Back to Photos'}
              </Link>
            </div>
          </div>

          {/* Error Message */}
          {error && (
            <div className="bg-red-50 border border-red-200 rounded-md p-4 mb-6">
              <p className="text-sm text-red-600">{error}</p>
            </div>
          )}

          {/* Upload Area */}
          <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-8">
            <div
              {...getRootProps()}
              className={`border-2 border-dashed rounded-lg p-12 text-center cursor-pointer transition-colors ${
                isDragActive
                  ? 'border-primary-400 bg-primary-50'
                  : 'border-gray-300 hover:border-primary-400 hover:bg-gray-50'
              }`}
            >
              <input {...getInputProps()} />
              
              <div className="space-y-4">
                <div className="mx-auto w-16 h-16 bg-gray-100 rounded-full flex items-center justify-center">
                  <svg className="w-8 h-8 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12" />
                  </svg>
                </div>
                
                <div>
                  <p className="text-lg font-medium text-gray-900">
                    {isDragActive ? 'Drop photos here' : 'Drag & drop photos here'}
                  </p>
                  <p className="text-sm text-gray-500 mt-1">
                    or click to select files
                  </p>
                </div>
                
                <div className="text-xs text-gray-400">
                  Supports: JPEG, PNG, GIF, BMP, WebP
                </div>
              </div>
            </div>
          </div>

          {/* Upload Progress */}
          {uploads.length > 0 && (
            <div className="mt-8 bg-white rounded-lg shadow-sm border border-gray-200 p-6">
              <h3 className="text-lg font-semibold text-gray-900 mb-4">Upload Progress</h3>
              
              <div className="space-y-4">
                {uploads.map((upload, index) => (
                  <div key={index} className="flex items-center space-x-4">
                    <div className="flex-shrink-0 w-12 h-12 bg-gray-100 rounded-lg flex items-center justify-center">
                      {upload.status === 'success' ? (
                        <svg className="w-6 h-6 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                        </svg>
                      ) : upload.status === 'error' ? (
                        <svg className="w-6 h-6 text-red-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
                        </svg>
                      ) : (
                        <svg className="w-6 h-6 text-blue-600 animate-spin" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15" />
                        </svg>
                      )}
                    </div>
                    
                    <div className="flex-1 min-w-0">
                      <p className="text-sm font-medium text-gray-900 truncate">
                        {upload.file.name}
                      </p>
                      <p className="text-xs text-gray-500">
                        {(upload.file.size / 1024 / 1024).toFixed(2)} MB
                      </p>
                    </div>
                    
                    <div className="flex-shrink-0 w-24">
                      <div className="w-full bg-gray-200 rounded-full h-2">
                        <div
                          className={`h-2 rounded-full transition-all duration-300 ${
                            upload.status === 'success'
                              ? 'bg-green-600'
                              : upload.status === 'error'
                              ? 'bg-red-600'
                              : 'bg-blue-600'
                          }`}
                          style={{ width: `${upload.progress}%` }}
                        />
                      </div>
                    </div>
                    
                    <div className="flex-shrink-0 w-16 text-right">
                      <span className={`text-xs font-medium ${
                        upload.status === 'success'
                          ? 'text-green-600'
                          : upload.status === 'error'
                          ? 'text-red-600'
                          : 'text-blue-600'
                      }`}>
                        {upload.status === 'success' ? 'Done' : upload.status === 'error' ? 'Error' : `${upload.progress}%`}
                      </span>
                    </div>
                  </div>
                ))}
              </div>
              
              {uploads.some(upload => upload.status === 'error') && (
                <div className="mt-4 p-3 bg-red-50 border border-red-200 rounded-md">
                  <p className="text-sm text-red-600">Some uploads failed. Please try again.</p>
                </div>
              )}
            </div>
          )}

          {/* Action Buttons */}
          {allUploadsComplete && (
            <div className="mt-8 flex justify-end space-x-3">
              <Link
                href={albumId ? `/admin/albums/${albumId}` : "/admin"}
                className="px-4 py-2 text-sm font-medium text-gray-700 bg-white border border-gray-300 rounded-md hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-primary-500"
              >
                {albumId ? 'Back to Album' : 'Upload More Photos'}
              </Link>
              <button
                onClick={handleFinish}
                className="px-4 py-2 text-sm font-medium text-white bg-primary-600 border border-transparent rounded-md hover:bg-primary-700 focus:outline-none focus:ring-2 focus:ring-primary-500"
              >
                {albumId ? 'Go to Album' : 'Go to Photos'}
              </button>
            </div>
          )}
        </div>

        <Footer />
      </div>
    </AdminGuard>
  )
}

export default dynamic(() => Promise.resolve(PhotoUploadPageContent), {
  ssr: false
})
