// frontend/src/routes/admin/blog-categories/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import MultiLangInput from '$lib/components/MultiLangInput.svelte';
	import MultiLangHTMLEditor from '$lib/components/MultiLangHTMLEditor.svelte';
	import type { MultiLangText } from '$lib/types/multi-lang';

	export let data; // From +layout.server.ts, contains user info

	interface BlogCategory {
		_id: string;
		alias: string;
		title: MultiLangText | string;
		description?: MultiLangText | string;
		leadingImage?: {
			url: string;
			alt?: MultiLangText | string;
			storageProvider?: string;
			storagePath?: string;
		};
		isActive?: boolean;
		sortOrder?: number;
		createdAt?: string;
		updatedAt?: string;
	}

	let categories: BlogCategory[] = [];
	let loading = true;
	let saving = false;
	let deleting = false;
	let message = '';
	let error = '';
	let searchTerm = '';
	let activeFilter = 'all';
	let showCreateDialog = false;
	let showEditDialog = false;
	let showDeleteDialog = false;
	let editingCategory: BlogCategory | null = null;
	let categoryToDelete: BlogCategory | null = null;

	// Form state
	let formData = {
		alias: '',
		title: { en: '', he: '' } as MultiLangText,
		description: { en: '', he: '' } as MultiLangText,
		leadingImage: {
			url: '',
			alt: { en: '', he: '' } as MultiLangText,
			storageProvider: '',
			storagePath: ''
		},
		isActive: true,
		sortOrder: 0
	};

	onMount(async () => {
		await loadCategories();
	});

	async function loadCategories() {
		loading = true;
		error = '';
		try {
			const params = new URLSearchParams();
			if (searchTerm) params.append('q', searchTerm);
			if (activeFilter !== 'all') params.append('isActive', activeFilter);

			const response = await fetch(`/api/admin/blog-categories?${params.toString()}`);
			if (!response.ok) {
				throw new Error('Failed to load blog categories');
			}
			const result = await response.json();
			categories = Array.isArray(result.data) ? result.data : (Array.isArray(result) ? result : []);
		} catch (err) {
			console.error('Error loading blog categories:', err);
			error = `Failed to load blog categories: ${err instanceof Error ? err.message : 'Unknown error'}`;
		} finally {
			loading = false;
		}
	}

	function resetForm() {
		formData = {
			alias: '',
			title: { en: '', he: '' },
			description: { en: '', he: '' },
			leadingImage: {
				url: '',
				alt: { en: '', he: '' },
				storageProvider: '',
				storagePath: ''
			},
			isActive: true,
			sortOrder: 0
		};
	}

	function openCreateDialog() {
		resetForm();
		showCreateDialog = true;
		error = '';
	}

	function openEditDialog(category: BlogCategory) {
		editingCategory = category;
		const titleField = typeof category.title === 'string' ? { en: category.title, he: '' } : category.title || { en: '', he: '' };
		const descField = typeof category.description === 'string'
			? { en: category.description, he: '' }
			: category.description || { en: '', he: '' };
		formData = {
			alias: category.alias || '',
			title: titleField,
			description: descField,
			leadingImage: category.leadingImage || {
				url: '',
				alt: { en: '', he: '' },
				storageProvider: '',
				storagePath: ''
			},
			isActive: category.isActive !== undefined ? category.isActive : true,
			sortOrder: category.sortOrder || 0
		};
		showEditDialog = true;
		error = '';
	}

	function openDeleteDialog(category: BlogCategory) {
		categoryToDelete = category;
		showDeleteDialog = true;
	}

	function getCategoryTitle(category: BlogCategory): string {
		const titleField = typeof category.title === 'string' ? category.title : category.title;
		if (typeof titleField === 'string') return titleField;
		return titleField?.en || titleField?.he || category.alias || '(No title)';
	}

	async function handleCreate() {
		saving = true;
		error = '';
		message = '';

		try {
			const payload: any = {
				title: formData.title,
				description: formData.description,
				isActive: formData.isActive,
				sortOrder: formData.sortOrder
			};
			if (formData.alias.trim()) payload.alias = formData.alias.trim();
			if (formData.leadingImage.url.trim()) {
				payload.leadingImage = formData.leadingImage;
			}

			const response = await fetch('/api/admin/blog-categories', {
				method: 'POST',
				headers: {
					'Content-Type': 'application/json'
				},
				body: JSON.stringify(payload)
			});

			const responseData = await response.json().catch((e) => {
				console.error('Failed to parse response:', e);
				return null;
			});

			if (!response.ok) {
				const errorMessage = responseData?.message || `HTTP ${response.status}: Failed to create blog category`;
				throw new Error(errorMessage);
			}

			if (!responseData) {
				throw new Error('No data returned from server');
			}

			const newCategory = responseData.data || responseData;
			categories = [...categories, newCategory];
			message = 'Blog category created successfully!';
			showCreateDialog = false;
			resetForm();

			setTimeout(() => {
				message = '';
			}, 3000);
		} catch (err) {
			console.error('Error creating blog category:', err);
			error = `Failed to create blog category: ${err instanceof Error ? err.message : 'Unknown error'}`;
		} finally {
			saving = false;
		}
	}

	async function handleEdit() {
		if (!editingCategory) return;

		saving = true;
		error = '';
		message = '';

		try {
			const payload: any = {
				title: formData.title,
				description: formData.description,
				isActive: formData.isActive,
				sortOrder: formData.sortOrder
			};
			if (formData.alias.trim() && formData.alias !== editingCategory.alias) {
				payload.alias = formData.alias.trim();
			}
			if (formData.leadingImage.url.trim()) {
				payload.leadingImage = formData.leadingImage;
			} else {
				payload.leadingImage = null;
			}

			const response = await fetch(`/api/admin/blog-categories/${editingCategory._id}`, {
				method: 'PUT',
				headers: {
					'Content-Type': 'application/json'
				},
				body: JSON.stringify(payload)
			});

			const responseData = await response.json().catch((e) => {
				console.error('Failed to parse response:', e);
				return null;
			});

			if (!response.ok) {
				const errorMessage = responseData?.message || `HTTP ${response.status}: Failed to update blog category`;
				throw new Error(errorMessage);
			}

			if (!responseData) {
				throw new Error('No data returned from server');
			}

			const updatedCategory = responseData.data || responseData;
			categories = categories.map((c) => (c._id === editingCategory._id ? updatedCategory : c));
			message = 'Blog category updated successfully!';
			showEditDialog = false;
			editingCategory = null;
			resetForm();

			setTimeout(() => {
				message = '';
			}, 3000);
		} catch (err) {
			console.error('Error updating blog category:', err);
			error = `Failed to update blog category: ${err instanceof Error ? err.message : 'Unknown error'}`;
		} finally {
			saving = false;
		}
	}

	async function handleDelete() {
		if (!categoryToDelete) return;

		deleting = true;
		error = '';
		message = '';

		try {
			const response = await fetch(`/api/admin/blog-categories/${categoryToDelete._id}`, {
				method: 'DELETE'
			});

			if (!response.ok) {
				const errorData = await response.json().catch(() => ({}));
				throw new Error(errorData.message || 'Failed to delete blog category');
			}

			categories = categories.filter((c) => c._id !== categoryToDelete._id);
			message = 'Blog category deleted successfully!';
			showDeleteDialog = false;
			categoryToDelete = null;

			setTimeout(() => {
				message = '';
			}, 3000);
		} catch (err) {
			console.error('Error deleting blog category:', err);
			error = `Failed to delete blog category: ${err instanceof Error ? err.message : 'Unknown error'}`;
		} finally {
			deleting = false;
		}
	}
</script>

<svelte:head>
	<title>Blog Categories Management - Admin</title>
</svelte:head>

<div class="min-h-screen bg-gray-50 py-8">
	<div class="max-w-6xl mx-auto px-4">
		<div class="bg-white rounded-lg shadow-md p-6">
			<div class="flex items-center justify-between mb-6">
				<div>
					<h1 class="text-2xl font-bold text-gray-900">Blog Categories Management</h1>
					<p class="text-gray-600 mt-2">Organize blog articles into categories</p>
				</div>
				<a href="/admin" class="text-blue-600 hover:text-blue-800 text-sm font-medium">
					← Back to Admin
				</a>
			</div>

			{#if message}
				<div class="mb-4 p-4 rounded-md bg-green-50 text-green-700">{message}</div>
			{/if}

			{#if error}
				<div class="mb-4 p-4 rounded-md bg-red-50 text-red-700">{error}</div>
			{/if}

			<!-- Search and Filters -->
			<div class="flex items-center justify-between mb-6">
				<div class="flex items-center space-x-4">
					<div class="relative">
						<input
							type="text"
							placeholder="Search categories..."
							bind:value={searchTerm}
							on:input={() => loadCategories()}
							class="pl-10 pr-4 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-2 focus:ring-blue-500 focus:border-blue-500 w-64"
						/>
						<svg
							class="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400 h-4 w-4"
							fill="none"
							stroke="currentColor"
							viewBox="0 0 24 24"
						>
							<path
								stroke-linecap="round"
								stroke-linejoin="round"
								stroke-width="2"
								d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"
							/>
						</svg>
					</div>

					<select
						bind:value={activeFilter}
						on:change={() => loadCategories()}
						class="px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
					>
						<option value="all">All Status</option>
						<option value="true">Active</option>
						<option value="false">Inactive</option>
					</select>
				</div>

				<button
					type="button"
					on:click={openCreateDialog}
					class="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 text-sm font-medium flex items-center gap-2"
				>
					<svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
						<path
							stroke-linecap="round"
							stroke-linejoin="round"
							stroke-width="2"
							d="M12 4v16m8-8H4"
						/>
					</svg>
					Add Category
				</button>
			</div>

			<!-- Categories List -->
			{#if loading}
				<div class="text-center py-8">
					<div class="inline-block animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
					<p class="mt-2 text-gray-600">Loading categories...</p>
				</div>
			{:else if categories.length === 0}
				<div class="text-center py-8">
					<svg
						class="h-12 w-12 text-gray-400 mx-auto mb-4"
						fill="none"
						stroke="currentColor"
						viewBox="0 0 24 24"
					>
						<path
							stroke-linecap="round"
							stroke-linejoin="round"
							stroke-width="2"
							d="M7 7h.01M7 3h5c.512 0 1.024.195 1.414.586l7 7a2 2 0 010 2.828l-7 7a2 2 0 01-2.828 0l-7-7A1.994 1.994 0 013 12V7a4 4 0 014-4z"
						/>
					</svg>
					<h3 class="text-lg font-semibold text-gray-900 mb-2">No categories found</h3>
					<p class="text-gray-600">Start by creating your first blog category.</p>
				</div>
			{:else}
				<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
					{#each categories as category}
						<div class="bg-white rounded-lg shadow-sm border border-gray-200 p-4">
							<div class="flex items-start justify-between mb-3">
								<div class="flex-1">
									<h3 class="font-semibold text-gray-900 mb-1">{getCategoryTitle(category)}</h3>
									<p class="text-sm text-gray-500">
										Alias: <code class="bg-gray-100 px-1 rounded">{category.alias}</code>
									</p>
								</div>

								<div class="flex space-x-1">
									<button
										type="button"
										on:click={() => openEditDialog(category)}
										class="p-1 text-gray-600 hover:text-blue-600 hover:bg-blue-50 rounded"
									>
										<svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
											<path
												stroke-linecap="round"
												stroke-linejoin="round"
												stroke-width="2"
												d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z"
											/>
										</svg>
									</button>
									<button
										type="button"
										on:click={() => openDeleteDialog(category)}
										class="p-1 text-gray-600 hover:text-red-600 hover:bg-red-50 rounded"
									>
										<svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
											<path
												stroke-linecap="round"
												stroke-linejoin="round"
												stroke-width="2"
												d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16"
											/>
										</svg>
									</button>
								</div>
							</div>

							<div class="flex items-center justify-between mt-3">
								<span class="text-xs text-gray-500">
									Order: {category.sortOrder || 0}
								</span>
								{#if category.isActive}
									<span class="px-2 py-1 text-xs font-medium rounded bg-green-100 text-green-800">
										Active
									</span>
								{:else}
									<span class="px-2 py-1 text-xs font-medium rounded bg-gray-100 text-gray-800">
										Inactive
									</span>
								{/if}
							</div>
						</div>
					{/each}
				</div>
			{/if}
		</div>
	</div>
</div>

<!-- Create Dialog -->
{#if showCreateDialog}
	<div class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
		<div class="bg-white rounded-lg shadow-xl w-full max-w-2xl p-6 max-h-[90vh] overflow-y-auto">
			<h2 class="text-xl font-bold text-gray-900 mb-4">Add New Blog Category</h2>

			{#if error}
				<div class="mb-4 p-4 bg-red-50 text-red-700 rounded-md">{error}</div>
			{/if}

			<div class="space-y-4">
				<div>
					<label class="block text-sm font-medium text-gray-700 mb-2">
						Title *
					</label>
					<MultiLangInput bind:value={formData.title} />
				</div>

				<div>
					<label class="block text-sm font-medium text-gray-700 mb-2">
						Alias (optional - auto-generated if not provided)
					</label>
					<input
						type="text"
						bind:value={formData.alias}
						placeholder="category-slug"
						class="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
					/>
				</div>

				<div>
					<label class="block text-sm font-medium text-gray-700 mb-2">
						Description
					</label>
					<MultiLangHTMLEditor bind:value={formData.description} />
				</div>

				<div>
					<label class="block text-sm font-medium text-gray-700 mb-2">
						Leading Image URL
					</label>
					<input
						type="text"
						bind:value={formData.leadingImage.url}
						placeholder="https://..."
						class="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
					/>
				</div>

				<div class="grid grid-cols-2 gap-4">
					<div>
						<label class="block text-sm font-medium text-gray-700 mb-2">
							Sort Order
						</label>
						<input
							type="number"
							bind:value={formData.sortOrder}
							class="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
						/>
					</div>

					<div class="flex items-center pt-8">
						<label class="relative inline-flex items-center cursor-pointer">
							<input
								type="checkbox"
								bind:checked={formData.isActive}
								class="sr-only peer"
							/>
							<div
								class="w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-blue-300 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-blue-600"
							></div>
							<span class="ml-3 text-sm font-medium text-gray-700">
								Active
							</span>
						</label>
					</div>
				</div>

				<div class="flex justify-end space-x-2 pt-4">
					<button
						type="button"
						on:click={() => {
							showCreateDialog = false;
							resetForm();
						}}
						class="px-4 py-2 bg-gray-200 text-gray-700 rounded-md hover:bg-gray-300 text-sm font-medium"
					>
						Cancel
					</button>
					<button
						type="button"
						on:click={handleCreate}
						disabled={saving || !formData.title}
						class="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 disabled:opacity-50 text-sm font-medium"
					>
						{#if saving}
							Creating...
						{:else}
							Create Category
						{/if}
					</button>
				</div>
			</div>
		</div>
	</div>
{/if}

<!-- Edit Dialog -->
{#if showEditDialog && editingCategory}
	<div class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
		<div class="bg-white rounded-lg shadow-xl w-full max-w-2xl p-6 max-h-[90vh] overflow-y-auto">
			<h2 class="text-xl font-bold text-gray-900 mb-4">Edit Blog Category</h2>

			{#if error}
				<div class="mb-4 p-4 bg-red-50 text-red-700 rounded-md">{error}</div>
			{/if}

			<div class="space-y-4">
				<div>
					<label class="block text-sm font-medium text-gray-700 mb-2">
						Title *
					</label>
					<MultiLangInput bind:value={formData.title} />
				</div>

				<div>
					<label class="block text-sm font-medium text-gray-700 mb-2">
						Alias
					</label>
					<input
						type="text"
						bind:value={formData.alias}
						placeholder="category-slug"
						class="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
					/>
				</div>

				<div>
					<label class="block text-sm font-medium text-gray-700 mb-2">
						Description
					</label>
					<MultiLangHTMLEditor bind:value={formData.description} />
				</div>

				<div>
					<label class="block text-sm font-medium text-gray-700 mb-2">
						Leading Image URL
					</label>
					<input
						type="text"
						bind:value={formData.leadingImage.url}
						placeholder="https://..."
						class="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
					/>
				</div>

				<div class="grid grid-cols-2 gap-4">
					<div>
						<label class="block text-sm font-medium text-gray-700 mb-2">
							Sort Order
						</label>
						<input
							type="number"
							bind:value={formData.sortOrder}
							class="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
						/>
					</div>

					<div class="flex items-center pt-8">
						<label class="relative inline-flex items-center cursor-pointer">
							<input
								type="checkbox"
								bind:checked={formData.isActive}
								class="sr-only peer"
							/>
							<div
								class="w-11 h-6 bg-gray-200 peer-focus:outline-none peer-focus:ring-4 peer-focus:ring-blue-300 rounded-full peer peer-checked:after:translate-x-full peer-checked:after:border-white after:content-[''] after:absolute after:top-[2px] after:left-[2px] after:bg-white after:border-gray-300 after:border after:rounded-full after:h-5 after:w-5 after:transition-all peer-checked:bg-blue-600"
							></div>
							<span class="ml-3 text-sm font-medium text-gray-700">
								Active
							</span>
						</label>
					</div>
				</div>

				<div class="flex justify-end space-x-2 pt-4">
					<button
						type="button"
						on:click={() => {
							showEditDialog = false;
							editingCategory = null;
							resetForm();
						}}
						class="px-4 py-2 bg-gray-200 text-gray-700 rounded-md hover:bg-gray-300 text-sm font-medium"
					>
						Cancel
					</button>
					<button
						type="button"
						on:click={handleEdit}
						disabled={saving || !formData.title}
						class="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 disabled:opacity-50 text-sm font-medium"
					>
						{#if saving}
							Updating...
						{:else}
							Update Category
						{/if}
					</button>
				</div>
			</div>
		</div>
	</div>
{/if}

<!-- Delete Dialog -->
{#if showDeleteDialog && categoryToDelete}
	<div class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
		<div class="bg-white rounded-lg shadow-xl w-full max-w-md p-6">
			<h2 class="text-xl font-bold text-gray-900 mb-4">Delete Blog Category</h2>

			{#if error}
				<div class="mb-4 p-4 bg-red-50 text-red-700 rounded-md">{error}</div>
			{/if}

			<div class="space-y-4">
				<p class="text-gray-600">
					Are you sure you want to delete <strong>{getCategoryTitle(categoryToDelete)}</strong> ({categoryToDelete.alias})? This
					action cannot be undone.
				</p>
				<div class="p-3 bg-yellow-50 border border-yellow-200 rounded-md">
					<p class="text-sm text-yellow-800">
						⚠️ Make sure no blog articles are assigned to this category before deleting.
					</p>
				</div>
				<div class="flex justify-end space-x-2">
					<button
						type="button"
						on:click={() => {
							showDeleteDialog = false;
							categoryToDelete = null;
						}}
						class="px-4 py-2 bg-gray-200 text-gray-700 rounded-md hover:bg-gray-300 text-sm font-medium"
					>
						Cancel
					</button>
					<button
						type="button"
						on:click={handleDelete}
						disabled={deleting}
						class="px-4 py-2 bg-red-600 text-white rounded-md hover:bg-red-700 disabled:opacity-50 text-sm font-medium"
					>
						{#if deleting}
							Deleting...
						{:else}
							Delete Category
						{/if}
					</button>
				</div>
			</div>
		</div>
	</div>
{/if}

// src/app/admin/blog-categories/page.tsx
'use client'

import { useState, useEffect, useCallback, Suspense } from 'react'
import { useSession } from 'next-auth/react'
import { useI18n } from '@/hooks/useI18n'
import { useLanguage } from '@/contexts/LanguageContext'
import { MultiLangUtils } from '@/types/multi-lang'
import Link from 'next/link'
import { BlogCategory, ApiResponse, PaginatedResponse } from '@/types'
import { useRouter, useSearchParams } from 'next/navigation'
import AdminGuard from '@/components/AdminGuard'

function AdminBlogCategoriesContent() {
  const { t } = useI18n()
  const { isRTL, currentLanguage } = useLanguage()
  const { data: session } = useSession()
  const router = useRouter()
  const searchParams = useSearchParams()

  const [categories, setCategories] = useState<BlogCategory[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [searchQuery, setSearchQuery] = useState(searchParams.get('q') || '')
  const [isActiveFilter, setIsActiveFilter] = useState(searchParams.get('isActive') || '')
  const [page, setPage] = useState(parseInt(searchParams.get('page') || '1'))
  const [totalPages, setTotalPages] = useState(1)

  const fetchCategories = useCallback(async () => {
    if (!session?.user) return

    setLoading(true)
    setError(null)

    const params = new URLSearchParams()
    if (searchQuery) params.set('q', searchQuery)
    if (isActiveFilter) params.set('isActive', isActiveFilter)
    params.set('page', page.toString())
    params.set('limit', '10')

    try {
      const response = await fetch(`/api/admin/blog-categories?${params.toString()}`)
      if (!response.ok) {
        throw new Error('Failed to fetch categories')
      }

      const data = await response.json()
      if (data?.success) {
        const categoriesData: BlogCategory[] = Array.isArray(data.data)
          ? data.data
          : (data.data?.data || [])
        const pagination = data.pagination || data.data?.pagination
        setCategories(categoriesData || [])
        setTotalPages(pagination?.totalPages || 1)
      } else {
        setCategories([])
        setTotalPages(1)
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : 'An error occurred')
    } finally {
      setLoading(false)
    }
  }, [session, searchQuery, isActiveFilter, page])

  useEffect(() => {
    fetchCategories()
  }, [fetchCategories])

  useEffect(() => {
    const current = new URLSearchParams(Array.from(searchParams.entries()))
    if (searchQuery) {
      current.set('q', searchQuery)
    } else {
      current.delete('q')
    }
    if (isActiveFilter) {
      current.set('isActive', isActiveFilter)
    } else {
      current.delete('isActive')
    }
    current.set('page', page.toString())
    router.push(`?${current.toString()}`)
  }, [searchQuery, isActiveFilter, page, router, searchParams])

  const handleSearchChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setSearchQuery(e.target.value)
    setPage(1)
  }

  const handleActiveFilterChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    setIsActiveFilter(e.target.value)
    setPage(1)
  }

  const handlePageChange = (newPage: number) => {
    setPage(newPage)
  }

  const handleAction = async (categoryId: string, action: 'toggle-active' | 'delete') => {
    if (!session?.user) return

    if (action === 'delete') {
      if (!confirm(t('admin.confirmDeleteCategory'))) {
        return
      }
    }

    setLoading(true)
    setError(null)

    try {
      let response: Response | undefined
      if (action === 'delete') {
        response = await fetch(`/api/admin/blog-categories/${categoryId}`, { method: 'DELETE' })
      } else {
        // Toggle active status
        const category = (categories || []).find(c => c._id === categoryId)
        if (category) {
          response = await fetch(`/api/admin/blog-categories/${categoryId}`, {
            method: 'PUT',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ isActive: !category.isActive })
          })
        }
      }

      if (!response || !response.ok) {
        const errorData = response ? await response.json() : { error: 'No response received' }
        throw new Error(errorData.error || `Failed to ${action} category`)
      }

      fetchCategories() // Re-fetch categories to update the list
    } catch (err) {
      setError(err instanceof Error ? err.message : `Failed to ${action} category`)
    } finally {
      setLoading(false)
    }
  }

  const getArrowPath = () => isRTL ? "M10 19l-7-7m0 0l7-7m-7 7h18" : "M14 5l7 7-7 7M21 12H3"

  return (
    <AdminGuard>
      <div className="min-h-screen bg-gray-50 py-8">
        <div className="max-w-7xl mx-auto px-4">
          <div className="flex justify-between items-center mb-8">
            <div>
              <h1 className="text-3xl font-bold text-gray-900">{t('admin.blogCategories')}</h1>
              <p className="text-gray-600 mt-2">{t('admin.manageBlogCategories')}</p>
            </div>
            <div className="flex space-x-3">
              <Link
                href="/admin"
                className="inline-flex items-center px-4 py-2 bg-gray-600 text-white rounded-md hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-gray-500 focus:ring-offset-2"
              >
                <svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10 19l-7-7m0 0l7-7m-7 7h18" />
                </svg>
                {t('admin.backToDashboard')}
              </Link>
              <Link
                href="/admin/blog-categories/new"
                className="inline-flex items-center px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2"
              >
                <svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
                </svg>
                {t('admin.createNewCategory')}
              </Link>
            </div>
          </div>

          {error && (
            <div className="mb-6 bg-red-50 border border-red-200 rounded-md p-4">
              <div className="flex">
                <div className="flex-shrink-0">
                  <svg className="h-5 w-5 text-red-400" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 8v4m0 4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                  </svg>
                </div>
                <div className="ml-3">
                  <p className="text-sm text-red-800">{error}</p>
                </div>
              </div>
            </div>
          )}

          <div className="bg-white rounded-lg shadow-md p-6 mb-8">
            <h2 className="text-xl font-semibold text-gray-900 mb-4">{t('admin.searchCategories')}</h2>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <label htmlFor="search" className="block text-sm font-medium text-gray-700 mb-1">
                  {t('admin.search')}
                </label>
                <input
                  type="text"
                  id="search"
                  className="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
                  placeholder={t('admin.searchPlaceholder')}
                  value={searchQuery}
                  onChange={handleSearchChange}
                />
              </div>
              <div>
                <label htmlFor="isActive" className="block text-sm font-medium text-gray-700 mb-1">
                  {t('admin.status')}
                </label>
                <select
                  id="isActive"
                  className="w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-blue-500 focus:border-blue-500"
                  value={isActiveFilter}
                  onChange={handleActiveFilterChange}
                >
                  <option value="">{t('admin.allStatuses')}</option>
                  <option value="true">{t('admin.active')}</option>
                  <option value="false">{t('admin.inactive')}</option>
                </select>
              </div>
            </div>
          </div>

          {loading ? (
            <div className="text-center py-10">
              <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary-600 mx-auto"></div>
              <p className="mt-4 text-gray-600">{t('loading.loading')}</p>
            </div>
          ) : !categories || categories.length === 0 ? (
            <div className="text-center py-10 bg-white rounded-lg shadow-md">
              <p className="text-gray-600 text-lg">{t('admin.noCategories')}</p>
              <p className="text-gray-500 mt-2">{t('admin.getStartedByCreatingCategory')}</p>
              <Link
                href="/admin/blog-categories/new"
                className="mt-6 inline-flex items-center px-6 py-3 border border-transparent text-base font-medium rounded-md shadow-sm text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500"
              >
                {t('admin.createNewCategory')}
              </Link>
            </div>
          ) : (
            <div className="bg-white rounded-lg shadow-md overflow-hidden">
              <table className="min-w-full divide-y divide-gray-200">
                <thead className="bg-gray-50">
                  <tr>
                    <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      {t('admin.title')}
                    </th>
                    <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      {t('admin.alias')}
                    </th>
                    <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      {t('admin.status')}
                    </th>
                    <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      {t('admin.sortOrder')}
                    </th>
                    <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                      {t('admin.created')}
                    </th>
                    <th scope="col" className="relative px-6 py-3">
                      <span className="sr-only">{t('admin.actions')}</span>
                    </th>
                  </tr>
                </thead>
                <tbody className="bg-white divide-y divide-gray-200">
                  {(categories || []).map((category) => (
                    <tr key={category._id}>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <div className="flex items-center">
                          {category.leadingImage?.url && (
                            <div className="flex-shrink-0 h-10 w-10">
                              <img
                                className="h-10 w-10 rounded-full object-cover"
                                src={category.leadingImage.url}
                                alt={MultiLangUtils.getTextValue(category.leadingImage.alt, currentLanguage) || ''}
                              />
                            </div>
                          )}
                          <div className="ml-4">
                            <div className="text-sm font-medium text-gray-900">
                              {MultiLangUtils.getTextValue(category.title, currentLanguage)}
                            </div>
                            {category.description && (
                              <div className="text-sm text-gray-500">
                                {MultiLangUtils.getTextValue(category.description, currentLanguage)}
                              </div>
                            )}
                          </div>
                        </div>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <div className="text-sm text-gray-900">{category.alias}</div>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <span className={`px-2 inline-flex text-xs leading-5 font-semibold rounded-full ${
                          category.isActive ? 'bg-green-100 text-green-800' : 'bg-red-100 text-red-800'
                        }`}>
                          {category.isActive ? t('admin.active') : t('admin.inactive')}
                        </span>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                        {category.sortOrder}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                        {new Date(category.createdAt).toLocaleDateString()}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                        <Link href={`/admin/blog-categories/${category._id}/edit`} className="text-indigo-600 hover:text-indigo-900 mr-4">
                          {t('admin.edit')}
                        </Link>
                        <button
                          onClick={() => handleAction(category._id!, 'toggle-active')}
                          className={`mr-4 ${category.isActive ? 'text-yellow-600 hover:text-yellow-900' : 'text-green-600 hover:text-green-900'}`}
                        >
                          {category.isActive ? t('admin.deactivate') : t('admin.activate')}
                        </button>
                        <button
                          onClick={() => handleAction(category._id!, 'delete')}
                          className="text-red-600 hover:text-red-900"
                        >
                          {t('admin.delete')}
                        </button>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>

              {/* Pagination */}
              {totalPages > 1 && (
                <nav
                  className="bg-white px-4 py-3 flex items-center justify-between border-t border-gray-200 sm:px-6"
                  aria-label="Pagination"
                >
                  <div className="flex-1 flex justify-between sm:justify-end">
                    <button
                      onClick={() => handlePageChange(page - 1)}
                      disabled={page === 1}
                      className="relative inline-flex items-center px-4 py-2 border border-gray-300 text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                      {t('pagination.previous')}
                    </button>
                    <button
                      onClick={() => handlePageChange(page + 1)}
                      disabled={page === totalPages}
                      className="ml-3 relative inline-flex items-center px-4 py-2 border border-gray-300 text-sm font-medium rounded-md text-gray-700 bg-white hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                      {t('pagination.next')}
                    </button>
                  </div>
                </nav>
              )}
            </div>
          )}
        </div>
      </div>
    </AdminGuard>
  )
}

export default function AdminBlogCategoriesPage() {
  return (
    <Suspense fallback={
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary-600 mx-auto"></div>
          <p className="mt-4 text-gray-600">Loading...</p>
        </div>
      </div>
    }>
      <AdminBlogCategoriesContent />
    </Suspense>
  )
}
