// frontend/src/routes/admin/audit-logs/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import Header from '$lib/components/Header.svelte';
	import Footer from '$lib/components/Footer.svelte';

  export const data = undefined as any; // From +layout.server.ts, not used in this component

	interface Log {
		_id: string;
		timestamp: string;
		action: string;
		userId?: string;
		userRole?: string;
		ip?: string;
		userAgent?: string;
		resourceType: string;
		resourceId?: string;
		resourceAlias?: string;
		details?: any;
	}

	let logs: Log[] = [];
	let loading = true;
	let error = '';

	onMount(async () => {
		await loadLogs();
	});

	async function loadLogs() {
		loading = true;
		error = '';
		try {
			const response = await fetch('/api/admin/audit-logs?limit=100');
			if (!response.ok) {
				throw new Error('Failed to load audit logs');
			}
			const result = await response.json();
			if (result.success) {
				logs = result.data || [];
			} else {
				throw new Error(result.error || 'Failed to load audit logs');
			}
		} catch (err) {
			console.error('Error loading audit logs:', err);
			error = `Failed to load audit logs: ${err instanceof Error ? err.message : 'Unknown error'}`;
		} finally {
			loading = false;
		}
	}
</script>

<svelte:head>
	<title>Audit Logs - Admin</title>
</svelte:head>

<Header />

<main class="min-h-screen bg-gray-50 py-8">
	<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
		<div class="mb-6">
			<h1 class="text-3xl font-bold text-gray-900">Audit Logs</h1>
			<p class="mt-2 text-gray-600">View system activity and user actions</p>
		</div>

		{#if error}
			<div class="mb-4 p-4 bg-red-50 border border-red-200 rounded-md">
				<p class="text-red-800">{error}</p>
			</div>
		{/if}

		{#if loading}
			<div class="flex items-center justify-center py-12">
				<div class="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600"></div>
				<p class="ml-4 text-gray-600">Loading audit logs...</p>
			</div>
		{:else if logs.length === 0}
			<div class="text-center py-12">
				<p class="text-gray-500">No audit logs found</p>
			</div>
		{:else}
			<div class="bg-white rounded-lg shadow overflow-hidden">
				<div class="overflow-x-auto">
					<table class="min-w-full divide-y divide-gray-200">
						<thead class="bg-gray-50">
							<tr>
								<th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
									Time
								</th>
								<th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
									Action
								</th>
								<th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
									User
								</th>
								<th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
									Resource
								</th>
								<th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
									IP Address
								</th>
								<th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
									User Agent
								</th>
							</tr>
						</thead>
						<tbody class="bg-white divide-y divide-gray-200">
							{#each logs as log}
								<tr class="hover:bg-gray-50">
									<td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
										{new Date(log.timestamp).toLocaleString()}
									</td>
									<td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
										{log.action}
									</td>
									<td class="px-6 py-4 whitespace-nowrap text-sm text-gray-600">
										{log.userId || 'anon'} {log.userRole ? `(${log.userRole})` : ''}
									</td>
									<td class="px-6 py-4 whitespace-nowrap text-sm text-gray-600">
										{log.resourceType}:{log.resourceAlias || log.resourceId || '-'}
									</td>
									<td class="px-6 py-4 whitespace-nowrap text-sm text-gray-600">
										{log.ip || '-'}
									</td>
									<td class="px-6 py-4 text-sm text-gray-600 max-w-xs truncate" title={log.userAgent || ''}>
										{log.userAgent || '-'}
									</td>
								</tr>
							{/each}
						</tbody>
					</table>
				</div>
			</div>
		{/if}
	</div>
</main>

<Footer />

// frontend/src/app/admin/audit-logs/page.tsx
'use client'

import { useEffect, useState } from 'react'

interface Log {
  _id: string
  timestamp: string
  action: string
  userId?: string
  userRole?: string
  ip?: string
  userAgent?: string
  resourceType: string
  resourceId?: string
  resourceAlias?: string
  details?: any
}

export default function AuditLogsPage() {
  const [logs, setLogs] = useState<Log[]>([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    async function load() {
      setLoading(true)
      try {
        const res = await fetch('/api/admin/audit-logs?limit=100')
        const json = await res.json()
        if (json.success) setLogs(json.data)
      } finally {
        setLoading(false)
      }
    }
    load()
  }, [])

  return (
    <div className="p-6">
      <h1 className="text-2xl font-semibold mb-4">Audit Logs</h1>
      {loading ? (
        <div>Loading…</div>
      ) : (
        <div className="overflow-auto border rounded">
          <table className="min-w-full text-sm">
            <thead className="bg-muted">
              <tr>
                <th className="p-2 text-left">Time</th>
                <th className="p-2 text-left">Action</th>
                <th className="p-2 text-left">User</th>
                <th className="p-2 text-left">Resource</th>
                <th className="p-2 text-left">IP</th>
                <th className="p-2 text-left">UA</th>
              </tr>
            </thead>
            <tbody>
              {logs.map((l) => (
                <tr key={l._id} className="border-t">
                  <td className="p-2 whitespace-nowrap">{new Date(l.timestamp).toLocaleString()}</td>
                  <td className="p-2">{l.action}</td>
                  <td className="p-2">{l.userId || 'anon'} ({l.userRole || '-'})</td>
                  <td className="p-2">{l.resourceType}:{l.resourceAlias || l.resourceId}</td>
                  <td className="p-2">{l.ip || '-'}</td>
                  <td className="p-2 max-w-[320px] truncate" title={l.userAgent}>{l.userAgent || '-'}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  )
}
