// frontend/src/templates/modern/pages/Album.tsx
'use client'

import { useState, useEffect } from 'react'
import Image from 'next/image'
import Link from 'next/link'
import { useParams } from 'next/navigation'
import { useSiteConfig } from '@/hooks/useSiteConfig'
import { MultiLangUtils } from '@/types/multi-lang'
import { useLanguage } from '@/contexts/LanguageContext'
import { useI18n } from '@/hooks/useI18n'
import { TemplateAlbum, TemplatePhoto } from '@/types'
import Header from '../components/Header'
import Footer from '../components/Footer'
import AlbumBreadcrumbs from '@/components/AlbumBreadcrumbs'
import styles from '../styles.module.scss'
import PhotoLightbox from '@/components/PhotoLightbox'

export default function AlbumPage() {
  const params = useParams()
  const alias = params?.alias as string
  const { config, loading: configLoading } = useSiteConfig()
  const { currentLanguage } = useLanguage()
  const { t } = useI18n()
  const [lightboxOpen, setLightboxOpen] = useState(false)
  const [lightboxIndex, setLightboxIndex] = useState(0)
  const [album, setAlbum] = useState<TemplateAlbum | null>(null)
  const [photos, setPhotos] = useState<TemplatePhoto[]>([])
  const [subAlbums, setSubAlbums] = useState<TemplateAlbum[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [subAlbumCoverPhotos, setSubAlbumCoverPhotos] = useState<Record<string, TemplatePhoto>>({})
  const [pagination, setPagination] = useState<{ page: number; limit: number; total: number; pages: number } | null>(null)
  const [loadingMore, setLoadingMore] = useState(false)

  // Function to load more photos
  const loadMorePhotos = async () => {
    if (!album || !pagination || loadingMore) return
    
    const albumId = String(album._id)
    const nextPage = pagination.page + 1
    
    if (nextPage > pagination.pages) return // No more pages
    
    try {
      setLoadingMore(true)
      const photosResponse = await fetch(`/api/albums/${albumId}/photos?page=${nextPage}&limit=50&t=${Date.now()}`, { cache: 'no-store' })
      if (photosResponse.ok) {
        const photosResult = await photosResponse.json()
        const newPhotos = photosResult.photos || []
        setPhotos(prev => [...prev, ...newPhotos])
        if (photosResult.pagination) {
          setPagination(photosResult.pagination)
        }
      }
    } catch (error) {
      console.error('Failed to load more photos:', error)
    } finally {
      setLoadingMore(false)
    }
  }

  // Function to fetch cover photo for a sub-album
  const fetchSubAlbumCoverPhoto = async (albumId: string, coverPhotoId: string) => {
    try {
      const response = await fetch(`/api/photos/${coverPhotoId}?t=${Date.now()}`, { cache: 'no-store' })
      if (response.ok) {
        const photo = await response.json()
        setSubAlbumCoverPhotos(prev => ({
          ...prev,
          [albumId]: photo
        }))
      }
    } catch (error) {
      console.error(`Failed to fetch cover photo for sub-album ${albumId}:`, error)
    }
  }

  useEffect(() => {
    const fetchAlbumData = async () => {
      if (!alias) return
      
      try {
        setLoading(true)
        
        // Fetch album by alias
        const albumResponse = await fetch(`/api/albums/by-alias/${alias}?t=${Date.now()}`, { cache: 'no-store' })
        if (!albumResponse.ok) {
          throw new Error('Album not found')
        }
        
        const album = await albumResponse.json()
        setAlbum(album)
        
        // Convert album._id to string (handles both string and ObjectId)
        const albumId = String(album._id || '')
        
        // Fetch photos for this album (first page)
        const photosResponse = await fetch(`/api/albums/${albumId}/photos?page=1&limit=50&t=${Date.now()}`, { cache: 'no-store' })
        if (photosResponse.ok) {
          const photosResult = await photosResponse.json()
          // Backend returns { photos: [...], pagination: {...} }
          const photosData = photosResult.photos || []
          setPhotos(Array.isArray(photosData) ? photosData : [])
          if (photosResult.pagination) {
            setPagination(photosResult.pagination)
          }
        }
        
        // Fetch sub-albums
        console.log('Fetching sub-albums for album:', { alias, albumId, album })
        const subAlbumsResponse = await fetch(`/api/albums?parentId=${albumId}&t=${Date.now()}`, { cache: 'no-store' })
        if (subAlbumsResponse.ok) {
          const subAlbums = await subAlbumsResponse.json()
          console.log('Sub-albums response:', subAlbums)
          console.log('First sub-album sample:', subAlbums[0] ? {
            _id: subAlbums[0]._id,
            alias: subAlbums[0].alias,
            name: subAlbums[0].name,
            nameType: typeof subAlbums[0].name
          } : 'No albums')
          // Backend returns array directly
          setSubAlbums(Array.isArray(subAlbums) ? subAlbums : [])
          
          // Fetch cover photos for sub-albums that have them
          subAlbums.forEach((subAlbum: TemplateAlbum) => {
            if (subAlbum.coverPhotoId) {
              fetchSubAlbumCoverPhoto(subAlbum._id, subAlbum.coverPhotoId)
            }
          })
        } else {
          console.error('Failed to fetch sub-albums:', subAlbumsResponse.status, subAlbumsResponse.statusText)
        }
        
      } catch (error) {
        console.error('Failed to fetch album data:', error)
        setError(error instanceof Error ? error.message : 'Failed to fetch album')
      } finally {
        setLoading(false)
      }
    }

    fetchAlbumData()
  }, [alias])

  // Show loading state while config or album is loading
  if (configLoading || loading) {
    return (
      <div className={`min-h-screen ${styles.theme}`}>
        <Header />
        <div className="flex-1 flex items-center justify-center">
          <div className="text-center">
            <div className={`w-16 h-16 ${styles.loading} rounded-full mx-auto mb-4`}></div>
            <div className={styles.textSecondary}>Loading album...</div>
          </div>
        </div>
        <Footer />
      </div>
    )
  }

  // Show error state
  if (error) {
    return (
      <div className={`min-h-screen ${styles.theme}`}>
        <Header />
        <div className="flex-1 flex items-center justify-center">
          <div className="text-center">
            <div className={`${styles.textSecondary} mb-4`}>
              {error}
            </div>
            <Link href="/albums" className={styles.button}>
              Back to Albums
            </Link>
          </div>
        </div>
        <Footer />
      </div>
    )
  }

  // Show not found state
  if (!album) {
    return (
      <div className={`min-h-screen ${styles.theme}`}>
        <Header />
        <div className="flex-1 flex items-center justify-center">
          <div className="text-center">
            <div className={`${styles.textSecondary} mb-4`}>
              Album not found
            </div>
            <Link href="/albums" className={styles.button}>
              Back to Albums
            </Link>
          </div>
        </div>
        <Footer />
      </div>
    )
  }

  return (
    <div className={`min-h-screen ${styles.theme}`}>
      <Header />
      
      <main className="flex-1">
        {/* Breadcrumbs */}
        {album && (
          <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 pt-6 pb-1">
            <AlbumBreadcrumbs album={album} role="public" />
          </div>
        )}
        
        {/* Album Header */}
        <section className={styles.sectionTight}>
          <div className="max-w-6xl mx-auto">
            <div className="flex items-center justify-end mb-4">
              <div className={`${styles.textSecondary} text-sm`}>
                {photos.length} photos
                {subAlbums.length > 0 && (
                  <span> • {subAlbums.length} sub-albums</span>
                )}
              </div>
            </div>
            
            <div className="text-center">
              <h1 className={`${styles.sectionTitle} ${styles.animateFadeInUp}`}>
                {MultiLangUtils.getTextValue(album.name, currentLanguage)}
              </h1>
              {album.description && (
                <div 
                  className={`${styles.sectionContent} ${styles.animateFadeIn}`} 
                  style={{ animationDelay: '0.2s' }}
                  dangerouslySetInnerHTML={{
                    __html: MultiLangUtils.getHTMLValue(album.description, currentLanguage)
                  }}
                />
              )}
            </div>
          </div>
        </section>

        {/* Sub-albums Section */}
        {subAlbums.length > 0 && (
          <section className={styles.sectionTight}>
            <div className="max-w-6xl mx-auto">
              <div className={styles.galleryGrid}>
                {subAlbums.map((subAlbum, i) => (
                  <Link key={subAlbum._id} href={`/albums/${subAlbum.alias}`}>
                    <div className={`${styles.card} ${styles.animateScaleIn} h-full flex flex-col`} style={{ animationDelay: `${i * 0.1}s` }}>
                      <div className="overflow-hidden shrink-0">
                        {subAlbum.coverPhotoId && subAlbumCoverPhotos[subAlbum._id] ? (
                          <Image
                            src={subAlbumCoverPhotos[subAlbum._id].storage?.thumbnailPath || subAlbumCoverPhotos[subAlbum._id].url || '/placeholder.jpg'}
                            alt={MultiLangUtils.getTextValue(subAlbum.name, currentLanguage)}
                            width={400}
                            height={300}
                            className={styles.cardImage}
                            sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
                            loading="lazy"
                            fetchPriority={i < 2 ? 'low' : 'auto'}
                          />
                        ) : null}
                        <div 
                          className={`${styles.cardImage} ${styles.bgSecondary} flex items-center justify-center`}
                          style={{ display: (subAlbum.coverPhotoId && subAlbumCoverPhotos[subAlbum._id]) ? 'none' : 'flex' }}
                        >
                          <div className="text-4xl text-gray-400">📁</div>
                        </div>
                      </div>
                      <div className="p-4 flex flex-col grow">
                        <h3 className={`${styles.heading3} mb-2`}>
                          {subAlbum.name 
                            ? (typeof subAlbum.name === 'string' 
                                ? subAlbum.name 
                                : MultiLangUtils.getTextValue(subAlbum.name, currentLanguage))
                            : subAlbum.alias || 'Untitled Album'}
                        </h3>
                        <div className={`${styles.textSecondary} text-sm mb-2`}>
                          {subAlbum.photoCount > 0 && (
                            <span>{subAlbum.photoCount} photos</span>
                          )}
                          {subAlbum.photoCount === 0 && (
                            <span>Empty album</span>
                          )}
                        </div>
                        {subAlbum.description && (
                          <div 
                            className={`${styles.textSecondary} text-sm grow`}
                            dangerouslySetInnerHTML={{
                              __html: MultiLangUtils.getHTMLValue(subAlbum.description, currentLanguage)
                            }}
                          />
                        )}
                      </div>
                    </div>
                  </Link>
                ))}
              </div>
            </div>
          </section>
        )}

        {/* Photos Section */}
        {photos.length > 0 && (
          <section className={`${styles.gallery} ${styles.sectionTight}`}>
            <div className="max-w-6xl mx-auto">
              <div className={styles.galleryGrid}>
                {photos.map((photo, i) => (
                  <div 
                    key={photo._id} 
                    className={`${styles.card} ${styles.animateScaleIn} cursor-pointer`} 
                    style={{ animationDelay: `${i * 0.05}s` }}
                    onClick={() => { setLightboxIndex(i); setLightboxOpen(true) }}
                  >
                    <div className="overflow-hidden">
                      <Image
                        src={photo.storage?.thumbnailPath || photo.url || '/placeholder.jpg'}
                        alt={photo.alt ? MultiLangUtils.getTextValue(photo.alt, currentLanguage) : `Photo ${i + 1}`}
                        width={400}
                        height={300}
                        className={styles.cardImage}
                        sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
                        loading="lazy"
                        fetchPriority="low"
                      />
                    </div>
                    <div className="p-4">
                      <h3 className={`${styles.heading3} mb-1`}>
                        {MultiLangUtils.getTextValue(photo.title, currentLanguage) || `Photo ${i + 1}`}
                      </h3>
                      {photo.description && (
                        <div 
                          className={`${styles.textSecondary} text-sm mb-2`}
                          dangerouslySetInnerHTML={{
                            __html: MultiLangUtils.getHTMLValue(photo.description, currentLanguage)
                          }}
                        />
                      )}
                      
                      {/* Tags, People, Location */}
                      {(photo.tags?.length > 0 || photo.people?.length > 0 || photo.location) && (
                        <div className="flex flex-wrap gap-1 mt-2">
                          {/* Tags */}
                          {photo.tags && Array.isArray(photo.tags) && photo.tags.length > 0 && (
                            <>
                              {photo.tags.slice(0, 2).map((tag: any, tagIdx: number) => {
                                const tagName = typeof tag === 'string' 
                                  ? tag 
                                  : (tag.name 
                                      ? (typeof tag.name === 'string' 
                                          ? tag.name 
                                          : MultiLangUtils.getTextValue(tag.name, currentLanguage))
                                      : 'Untagged')
                                return (
                                  <span key={tagIdx} className="inline-flex items-center px-1.5 py-0.5 rounded text-xs bg-blue-100 text-blue-800">
                                    {tagName}
                                  </span>
                                )
                              })}
                              {photo.tags.length > 2 && (
                                <span className="inline-flex items-center px-1.5 py-0.5 rounded text-xs bg-gray-100 text-gray-600">
                                  +{photo.tags.length - 2}
                                </span>
                              )}
                            </>
                          )}
                          
                          {/* People */}
                          {photo.people && Array.isArray(photo.people) && photo.people.length > 0 && (
                            <>
                              {photo.people.slice(0, 2).map((person: any, personIdx: number) => {
                                let personName: string
                                if (typeof person === 'string') {
                                  personName = person
                                } else if (person.name) {
                                  personName = typeof person.name === 'string' 
                                    ? person.name 
                                    : MultiLangUtils.getTextValue(person.name, currentLanguage)
                                } else if (person.fullName) {
                                  personName = typeof person.fullName === 'string'
                                    ? person.fullName
                                    : MultiLangUtils.getTextValue(person.fullName, currentLanguage)
                                } else if (person.firstName) {
                                  personName = typeof person.firstName === 'string'
                                    ? person.firstName
                                    : MultiLangUtils.getTextValue(person.firstName, currentLanguage)
                                } else {
                                  personName = 'Unknown'
                                }
                                return (
                                  <span key={personIdx} className="inline-flex items-center px-1.5 py-0.5 rounded text-xs bg-purple-100 text-purple-800">
                                    👤 {personName}
                                  </span>
                                )
                              })}
                              {photo.people.length > 2 && (
                                <span className="inline-flex items-center px-1.5 py-0.5 rounded text-xs bg-gray-100 text-gray-600">
                                  +{photo.people.length - 2}
                                </span>
                              )}
                            </>
                          )}
                          
                          {/* Location */}
                          {photo.location && (
                            <span className="inline-flex items-center px-1.5 py-0.5 rounded text-xs bg-green-100 text-green-800">
                              📍 {typeof photo.location === 'string' 
                                ? photo.location 
                                : (photo.location.name 
                                    ? MultiLangUtils.getTextValue(photo.location.name, currentLanguage)
                                    : 'Unknown location')}
                            </span>
                          )}
                        </div>
                      )}
                    </div>
                  </div>
                ))}
              </div>
              
              {/* Load More Button */}
              {pagination && pagination.page < pagination.pages && (
                <div className="text-center mt-8">
                  <button
                    onClick={loadMorePhotos}
                    disabled={loadingMore}
                    className={`${styles.button} ${loadingMore ? 'opacity-50 cursor-not-allowed' : ''}`}
                  >
                    {loadingMore ? 'Loading...' : `Load More (${pagination.total - photos.length} remaining)`}
                  </button>
                </div>
              )}
            </div>
          </section>
        )}

        {/* Empty State */}
        {photos.length === 0 && subAlbums.length === 0 && (
          <section className={styles.section}>
            <div className="max-w-6xl mx-auto text-center">
              <div className={`${styles.textSecondary} mb-4`}>
                This album is empty.
              </div>
            </div>
          </section>
        )}

        {/* Photo Lightbox: prev/next, EXIF toggle, autoplay support */}
        <PhotoLightbox
          photos={photos.map(p => ({
            _id: p._id,
            url: p.storage?.url || p.url || '/placeholder.jpg',
            thumbnailUrl: p.storage?.thumbnailPath,
            title: typeof p.title === 'string' ? p.title : (p.title as any)?.[currentLanguage] || (p.title as any)?.en,
            takenAt: (p as any).exif?.dateTimeOriginal,
            exif: (p as any).exif ? {
              make: (p as any).exif.make,
              model: (p as any).exif.model,
              serialNumber: (p as any).exif.serialNumber,
              dateTime: (p as any).exif.dateTime,
              dateTimeOriginal: (p as any).exif.dateTimeOriginal,
              dateTimeDigitized: (p as any).exif.dateTimeDigitized,
              offsetTime: (p as any).exif.offsetTime,
              offsetTimeOriginal: (p as any).exif.offsetTimeOriginal,
              offsetTimeDigitized: (p as any).exif.offsetTimeDigitized,
              exposureTime: (p as any).exif.exposureTime,
              fNumber: (p as any).exif.fNumber,
              iso: (p as any).exif.iso,
              focalLength: (p as any).exif.focalLength,
              exposureProgram: (p as any).exif.exposureProgram,
              exposureMode: (p as any).exif.exposureMode,
              exposureBiasValue: (p as any).exif.exposureBiasValue,
              maxApertureValue: (p as any).exif.maxApertureValue,
              shutterSpeedValue: (p as any).exif.shutterSpeedValue,
              apertureValue: (p as any).exif.apertureValue,
              whiteBalance: (p as any).exif.whiteBalance,
              meteringMode: (p as any).exif.meteringMode,
              flash: (p as any).exif.flash,
              colorSpace: (p as any).exif.colorSpace,
              customRendered: (p as any).exif.customRendered,
              sceneCaptureType: (p as any).exif.sceneCaptureType,
              xResolution: (p as any).exif.xResolution,
              yResolution: (p as any).exif.yResolution,
              resolutionUnit: (p as any).exif.resolutionUnit,
              focalPlaneXResolution: (p as any).exif.focalPlaneXResolution,
              focalPlaneYResolution: (p as any).exif.focalPlaneYResolution,
              focalPlaneResolutionUnit: (p as any).exif.focalPlaneResolutionUnit,
              lensInfo: (p as any).exif.lensInfo,
              lensModel: (p as any).exif.lensModel,
              lensSerialNumber: (p as any).exif.lensSerialNumber,
              software: (p as any).exif.software,
              copyright: (p as any).exif.copyright,
              exifVersion: (p as any).exif.exifVersion,
              gps: (p as any).exif.gps ? {
                latitude: (p as any).exif.gps.latitude,
                longitude: (p as any).exif.gps.longitude,
                altitude: (p as any).exif.gps.altitude,
              } : undefined,
              recommendedExposureIndex: (p as any).exif.recommendedExposureIndex,
              subsecTimeOriginal: (p as any).exif.subsecTimeOriginal,
              subsecTimeDigitized: (p as any).exif.subsecTimeDigitized,
              gpsLatitude: (p as any).exif.gpsLatitude,
              gpsLongitude: (p as any).exif.gpsLongitude,
            } : undefined,
            metadata: (p as any).metadata ? {
              width: (p as any).metadata.width,
              height: (p as any).metadata.height,
              fileSize: (p as any).metadata.fileSize,
              format: (p as any).metadata.format,
            } : undefined,
            faceRecognition: (p as any).faceRecognition ? {
              faces: (p as any).faceRecognition.faces?.map((face: any) => ({
                box: face.box,
                matchedPersonId: face.matchedPersonId?.toString(),
                confidence: face.confidence
              })) || []
            } : undefined,
          }))}
          startIndex={lightboxIndex}
          isOpen={lightboxOpen}
          onClose={() => setLightboxOpen(false)}
          autoPlay={false}
          intervalMs={4000}
        />

        {/* Navigation - Commented out */}
        {/* <section className={`${styles.section} ${styles.bgSecondary}`}>
          <div className="max-w-4xl mx-auto text-center">
            <h2 className={`${styles.sectionTitle} ${styles.animateFadeInUp}`}>
              Explore More Albums
            </h2>
            <p className={`${styles.sectionContent} ${styles.animateFadeIn}`} style={{ animationDelay: '0.2s' }}>
              Discover more beautiful photo collections
            </p>
            <div className={styles.animateFadeIn} style={{ animationDelay: '0.4s' }}>
              <Link href="/albums" className={styles.button}>
                View All Albums
              </Link>
            </div>
          </div>
        </section> */}
      </main>
      
      <Footer />
    </div>
  )
}

// frontend/src/lib/templates/modern/Album.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { page } from '$app/stores';
	import { goto, afterNavigate } from '$app/navigation';
	import { browser } from '$app/environment';
	import { currentLanguage } from '$stores/language';
	import { siteConfigData } from '$stores/siteConfig';
	import AlbumBreadcrumbs from '$lib/components/AlbumBreadcrumbs.svelte';
	import PhotoLightbox from '$lib/components/PhotoLightbox.svelte';
	import MultiLangText from '$lib/components/MultiLangText.svelte';
	import MultiLangHTML from '$lib/components/MultiLangHTML.svelte';

	interface AlbumData {
		album: {
			_id: string;
			name: any;
			description?: any;
			alias: string;
			photoCount?: number;
			coverPhotoId?: string;
			parentAlbumId?: string;
			showExifData?: boolean;
		};
		subAlbums: Array<{
			_id: string;
			name: any;
			description?: any;
			alias: string;
			photoCount?: number;
			coverPhotoId?: string;
		}>;
		photos: Array<{
			_id: string;
			title?: any;
			description?: any;
			alt?: any;
			url?: string;
			storage?: {
				provider?: string;
				url?: string;
				path?: string;
				thumbnailPath?: string;
				thumbnails?: Record<string, string>;
			};
			exif?: any;
			metadata?: {
				width?: number;
				height?: number;
				fileSize?: number;
				format?: string;
			};
			dimensions?: {
				width?: number;
				height?: number;
			};
			size?: number;
			mimeType?: string;
			faceRecognition?: any;
			tags?: Array<string | { _id: string; name: any }>;
			people?: Array<string | { _id: string; fullName?: any; firstName?: any }>;
			location?: string | { _id: string; name: any };
		}>;
		pagination: {
			page: number;
			limit: number;
			total: number;
			pages: number;
		};
	}

	let alias = $page.params.alias || $page.params.id;
	let albumData: AlbumData | null = null;
	let loading = true;
	let error: string | null = null;
	let lightboxOpen = false;
	let lightboxIndex = 0;
	let loadingMore = false;
	let subAlbumCoverPhotos: Record<string, any> = {};
	let subAlbumCoverImages: Record<string, string> = {};
	let isInitialLoad = true;

	// React to route parameter changes using afterNavigate (recommended for SvelteKit)
	afterNavigate(({ to, from }) => {
		if (!browser) return;
		
		const newAlias = to?.params?.alias || to?.params?.id;
		const oldAlias = from?.params?.alias || from?.params?.id;
		
		// Only fetch if the alias actually changed (not on initial load)
		if (newAlias && newAlias !== oldAlias) {
			alias = newAlias;
			fetchAlbumData();
		} else if (isInitialLoad && newAlias) {
			// Handle initial load
			alias = newAlias;
			fetchAlbumData();
			isInitialLoad = false;
		}
	});

	function getPhotoUrl(photo: any): string {
		if (!photo.storage) {
			return photo.url || '/placeholder.jpg';
		}

		// Check thumbnails object first
		if (photo.storage.thumbnails && typeof photo.storage.thumbnails === 'object') {
			const thumbnails = photo.storage.thumbnails as Record<string, string>;
			const thumbnailUrl = thumbnails.medium || thumbnails.small || Object.values(thumbnails)[0];
			if (thumbnailUrl) {
				if (thumbnailUrl.startsWith('/api/storage/serve/') || thumbnailUrl.startsWith('http')) {
					return thumbnailUrl;
				}
				const provider = photo.storage.provider || 'local';
				const cleanPath = thumbnailUrl.startsWith('/') ? thumbnailUrl.slice(1) : thumbnailUrl;
				return `/api/storage/serve/${provider}/${encodeURIComponent(cleanPath)}`;
			}
		}

		// Check thumbnailPath
		if (photo.storage.thumbnailPath) {
			if (photo.storage.thumbnailPath.startsWith('/api/storage/serve/') || photo.storage.thumbnailPath.startsWith('http')) {
				return photo.storage.thumbnailPath;
			}
			const provider = photo.storage.provider || 'local';
			const cleanPath = photo.storage.thumbnailPath.startsWith('/') 
				? photo.storage.thumbnailPath.slice(1) 
				: photo.storage.thumbnailPath;
			return `/api/storage/serve/${provider}/${encodeURIComponent(cleanPath)}`;
		}

		// Fallback to url
		if (photo.storage.url) {
			if (photo.storage.url.startsWith('/api/storage/serve/') || photo.storage.url.startsWith('http')) {
				return photo.storage.url;
			}
			const provider = photo.storage.provider || 'local';
			const cleanPath = photo.storage.url.startsWith('/') 
				? photo.storage.url.slice(1) 
				: photo.storage.url;
			return `/api/storage/serve/${provider}/${encodeURIComponent(cleanPath)}`;
		}

		return photo.url || '/placeholder.jpg';
	}

	function getPhotoFullUrl(photo: any): string {
		if (!photo.storage) {
			return photo.url || '/placeholder.jpg';
		}

		// For full image, prefer url or path over thumbnailPath
		if (photo.storage.url) {
			if (photo.storage.url.startsWith('/api/storage/serve/') || photo.storage.url.startsWith('http')) {
				return photo.storage.url;
			}
			const provider = photo.storage.provider || 'local';
			const cleanPath = photo.storage.url.startsWith('/') 
				? photo.storage.url.slice(1) 
				: photo.storage.url;
			// Skip thumbnail paths
			if (!cleanPath.includes('/medium/') && !cleanPath.includes('/small/') && !cleanPath.includes('/thumb/')) {
				return `/api/storage/serve/${provider}/${encodeURIComponent(cleanPath)}`;
			}
		}

		// Fallback to thumbnailPath if no url
		return getPhotoUrl(photo);
	}

	async function fetchSubAlbumCoverPhoto(albumId: string, coverPhotoId: string) {
		try {
			const response = await fetch(`/api/photos/${coverPhotoId}?t=${Date.now()}`, {
				cache: 'no-store',
			});
			if (response.ok) {
				const photo = await response.json();
				subAlbumCoverPhotos = { ...subAlbumCoverPhotos, [albumId]: photo };
			}
		} catch (error) {
			console.error(`Failed to fetch cover photo for sub-album ${albumId}:`, error);
		}
	}

	async function fetchSubAlbumCoverImages(albumIds: string[]) {
		if (albumIds.length === 0) return;

		try {
			const response = await fetch('/api/albums/cover-images', {
				method: 'POST',
				headers: {
					'Content-Type': 'application/json',
				},
				body: JSON.stringify({ albumIds }),
			});

			if (response.ok) {
				const result = await response.json();
				
				// Handle both wrapped {success, data} and direct Record<string, string> formats
				if (result.success && result.data) {
					subAlbumCoverImages = result.data;
				} else if (result && typeof result === 'object' && !result.success) {
					subAlbumCoverImages = result;
				}
			}
		} catch (error) {
			console.error('Failed to fetch sub-album cover images:', error);
		}
	}

	async function loadMorePhotos() {
		if (!albumData || !albumData.pagination || loadingMore || !albumData.album) return;
		const albumId = albumData.album._id;
		const pagination = albumData.pagination;
		const nextPage = pagination.page + 1;
		if (nextPage > pagination.pages) return;

		try {
			loadingMore = true;
			const response = await fetch(
				`/api/albums/${albumId}/data?page=${nextPage}&limit=50&t=${Date.now()}`,
				{ cache: 'no-store' }
			);
			if (response.ok && albumData) {
				const result = await response.json();
				const newPhotos = result.photos || [];
				albumData.photos = [...albumData.photos, ...newPhotos];
				if (result.pagination) {
					albumData.pagination = result.pagination;
				}
			}
		} catch (error) {
			console.error('Failed to load more photos:', error);
		} finally {
			loadingMore = false;
		}
	}

	async function fetchAlbumData() {
		if (!alias || !browser) return;

		try {
			loading = true;
			error = null;
			// Clear previous sub-album cover photos when loading new album
			subAlbumCoverPhotos = {};

			const response = await fetch(`/api/albums/${encodeURIComponent(alias)}/data?page=1&limit=50&t=${Date.now()}`, {
				cache: 'no-store',
			});
			
			if (!response.ok) {
				throw new Error('Album not found');
			}

			albumData = await response.json();
			console.log('Album data loaded:', albumData);

			// Fetch cover images for sub-albums using the batch API (hierarchical logic)
			if (albumData && albumData.subAlbums && albumData.subAlbums.length > 0) {
				fetchSubAlbumCoverImages(albumData.subAlbums.map((a: any) => a._id));
			}
		} catch (err) {
			console.error('Failed to fetch album data:', err);
			error = err instanceof Error ? err.message : 'Failed to fetch album';
		} finally {
			loading = false;
		}
	}

	// Initial load is handled by afterNavigate
	// But we also need onMount as a fallback for cases where afterNavigate doesn't fire
	onMount(() => {
		if (browser && alias && isInitialLoad) {
			fetchAlbumData();
			isInitialLoad = false;
		}
	});
</script>

{#if loading}
	<div class="min-h-screen bg-gray-50 flex items-center justify-center">
		<div class="text-center">
			<div class="w-16 h-16 border-4 border-blue-600 border-t-transparent rounded-full animate-spin mx-auto mb-4"></div>
			<div class="text-gray-600">Loading album...</div>
		</div>
	</div>
{:else if error}
	<div class="min-h-screen bg-gray-50 flex items-center justify-center">
		<div class="text-center">
			<div class="text-gray-600 mb-4">{error}</div>
			<button on:click={() => goto('/albums')} class="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700">
				Back to Albums
			</button>
		</div>
	</div>
{:else if !albumData || !albumData.album}
	<div class="min-h-screen bg-gray-50 flex items-center justify-center">
		<div class="text-center">
			<div class="text-gray-600 mb-4">Album not found</div>
			<button on:click={() => goto('/albums')} class="px-4 py-2 bg-blue-600 text-white rounded-md hover:bg-blue-700">
				Back to Albums
			</button>
		</div>
	</div>
{:else}
	<div class="flex-1 min-h-screen bg-gray-50">
		{#if albumData.album}
			<div class="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 pt-6 pb-1">
				<AlbumBreadcrumbs album={albumData.album} role="public" />
			</div>
		{/if}

		<section class="py-8">
			<div class="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
				<div class="text-center mb-8">
					<h1 class="text-4xl font-bold text-gray-900 mb-4">
						<MultiLangText value={albumData.album.name} fallback="Untitled Album" />
					</h1>
					{#if albumData.album.description}
						<div class="text-lg text-gray-600">
							<MultiLangHTML value={albumData.album.description} />
						</div>
					{/if}
					<div class="mt-4 text-sm text-gray-500">
						{albumData.photos.length} photos
						{#if albumData.subAlbums && albumData.subAlbums.length > 0}
							• {albumData.subAlbums.length} sub-albums
						{/if}
					</div>
				</div>

				{#if albumData.subAlbums && albumData.subAlbums.length > 0}
					<div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 mb-12">
						{#each albumData.subAlbums as subAlbum}
							{@const coverImageUrl = subAlbumCoverImages[subAlbum._id]}
							{@const isLogo = coverImageUrl && (coverImageUrl.includes('/logos/') || coverImageUrl.includes('logo') || (coverImageUrl.includes('/api/storage/serve/') && coverImageUrl.includes('logo')))}
							<a href={`/albums/${subAlbum.alias}`} class="group">
								<div class="bg-white rounded-lg shadow-sm hover:shadow-md transition-shadow overflow-hidden">
									<div class="aspect-4/3 bg-gray-100 flex items-center justify-center overflow-hidden">
										{#if coverImageUrl}
											<img
												src={coverImageUrl}
												alt=""
												class="w-full h-full {isLogo
													? 'object-contain p-8 opacity-60 group-hover:opacity-80 transition-opacity'
													: 'object-cover group-hover:scale-105 transition-transform'}"
											/>
										{:else}
											<div class="text-4xl text-gray-400">📁</div>
										{/if}
									</div>
									<div class="p-4">
										<h3 class="text-lg font-semibold text-gray-900 group-hover:text-blue-600">
											<MultiLangText value={subAlbum.name} fallback="Untitled Album" />
										</h3>
										<div class="text-sm text-gray-500 mt-1">
											{subAlbum.photoCount || 0} photos
										</div>
									</div>
								</div>
							</a>
						{/each}
					</div>
				{/if}

				{#if albumData.photos && albumData.photos.length > 0}
					<div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
						{#each albumData.photos as photo, i}
							<button
								type="button"
								on:click={() => {
									lightboxIndex = i;
									lightboxOpen = true;
								}}
								class="group bg-white rounded-lg shadow-sm hover:shadow-md transition-shadow overflow-hidden text-left flex flex-col"
							>
								<div class="aspect-4/3 bg-gray-100 overflow-hidden shrink-0">
									<img
										src={getPhotoUrl(photo)}
										alt=""
										class="w-full h-full object-cover group-hover:scale-105 transition-transform"
									/>
								</div>
								<div class="p-3 flex-1 flex flex-col">
									{#if photo.title}
										<h3 class="text-sm font-medium text-gray-900 mb-2">
											<MultiLangText value={photo.title} fallback={`Photo ${i + 1}`} />
										</h3>
									{/if}
									
									<!-- Tags -->
									{#if photo.tags && Array.isArray(photo.tags) && photo.tags.length > 0}
										<div class="mb-2">
											<div class="flex flex-wrap gap-1">
												{#each photo.tags as tag}
													{@const tagName = typeof tag === 'object' && tag.name ? (typeof tag.name === 'string' ? tag.name : tag.name[$currentLanguage] || tag.name.en || tag.name.he || '') : (typeof tag === 'string' ? tag : '')}
													{#if tagName}
														<span class="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-blue-100 text-blue-800">
															#{tagName}
														</span>
													{/if}
												{/each}
											</div>
										</div>
									{/if}
									
									<!-- People -->
									{#if photo.people && Array.isArray(photo.people) && photo.people.length > 0}
										<div class="mb-2">
											<div class="flex flex-wrap gap-1 items-center">
												{#each photo.people as person}
													{@const personName = typeof person === 'object' && person.fullName ? (typeof person.fullName === 'string' ? person.fullName : person.fullName[$currentLanguage] || person.fullName.en || person.fullName.he || '') : (typeof person === 'object' && person.firstName ? (typeof person.firstName === 'string' ? person.firstName : person.firstName[$currentLanguage] || person.firstName.en || person.firstName.he || '') : (typeof person === 'string' ? person : ''))}
													{#if personName}
														<span class="inline-flex items-center px-2 py-0.5 rounded text-xs font-medium bg-green-100 text-green-800">
															{personName}
														</span>
													{/if}
												{/each}
											</div>
										</div>
									{/if}
									
									<!-- Location -->
									{#if photo.location}
										{@const locationName = typeof photo.location === 'object' && photo.location.name ? (typeof photo.location.name === 'string' ? photo.location.name : photo.location.name[$currentLanguage] || photo.location.name.en || photo.location.name.he || '') : (typeof photo.location === 'string' ? photo.location : '')}
										{#if locationName}
											<div class="mb-2">
												<div class="flex items-center gap-1 text-xs text-gray-600">
													<span>📍</span>
													<span>{locationName}</span>
												</div>
											</div>
										{/if}
									{/if}
									
									<!-- Description -->
									{#if photo.description}
										<div class="mt-auto text-xs text-gray-600 line-clamp-2">
											<MultiLangText value={photo.description} fallback="" />
										</div>
									{/if}
								</div>
							</button>
						{/each}
					</div>

					{#if albumData.pagination && albumData.pagination.page < albumData.pagination.pages}
						<div class="text-center mt-8">
							<button
								on:click={loadMorePhotos}
								disabled={loadingMore}
								class="px-6 py-3 bg-blue-600 text-white rounded-md hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed"
							>
								{loadingMore ? 'Loading...' : `Load More (${albumData.pagination.total - albumData.photos.length} remaining)`}
							</button>
						</div>
					{/if}
				{:else if !albumData.subAlbums || albumData.subAlbums.length === 0}
					<div class="text-center py-12">
						<div class="text-gray-600">This album is empty.</div>
					</div>
				{/if}
			</div>
		</section>
	</div>

	{#if albumData.photos && albumData.photos.length > 0}
		<PhotoLightbox
			photos={albumData.photos.map((p) => ({
				_id: p._id,
				url: getPhotoFullUrl(p),
				thumbnailUrl: getPhotoUrl(p),
				title: typeof p.title === 'string' ? p.title : p.title?.[$currentLanguage] || p.title?.en || '',
				takenAt: p.exif?.dateTimeOriginal,
				exif: p.exif, // Include full EXIF data
				metadata: p.metadata || (p.storage ? {
					width: p.dimensions?.width,
					height: p.dimensions?.height,
					fileSize: p.size,
					format: p.mimeType?.split('/')[1]?.toUpperCase()
				} : undefined),
				storage: p.storage,
				faceRecognition: p.faceRecognition
			}))}
			startIndex={lightboxIndex}
			isOpen={lightboxOpen}
			onClose={() => (lightboxOpen = false)}
			autoPlay={false}
			intervalMs={4000}
			showExifData={albumData.album.showExifData !== false}
		/>
	{/if}
{/if}
