// src/templates/dark/pages/Home.tsx
'use client'

import { useState, useEffect } from 'react'
import Header from '../components/Header'
import Hero from '../components/Hero'
import AlbumList from '../components/AlbumList'
import AlbumCard from '../components/AlbumCard'
import Footer from '../components/Footer'
import { useI18n } from '@/hooks/useI18n'
import { useTemplateConfig } from '@/hooks/useTemplateConfig'
import { useAlbumPhotoCounts } from '@/hooks/useAlbumPhotoCounts'
import { MultiLangUtils } from '@/types/multi-lang'
import { useLanguage } from '@/contexts/LanguageContext'
import { Album } from '@/types'

export default function HomePage() {
  const { t } = useI18n()
  const { isComponentVisible } = useTemplateConfig()
  const { currentLanguage } = useLanguage()
  const [rootAlbums, setRootAlbums] = useState<Album[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const { getTotalPhotosCount, loading: photoCountsLoading } = useAlbumPhotoCounts(rootAlbums)

  useEffect(() => {
    const fetchRootAlbums = async () => {
      try {
        setLoading(true)
        // Fetch only root albums (no parent)
        const response = await fetch('/api/albums?parentId=root&isPublic=true')
        
        if (!response.ok) {
          throw new Error('Failed to fetch albums')
        }
        
        const result = await response.json()
        if (result.success) {
          const albums = result.data
          
          // Filter to only public albums
          const publicAlbums = albums.filter((album: Album) => album.isPublic)
          setRootAlbums(publicAlbums)
        } else {
          setError(result.error || 'Failed to fetch albums')
        }
      } catch (error) {
        console.error('Failed to fetch albums:', error)
        setError('Failed to fetch albums')
      } finally {
        setLoading(false)
      }
    }

    fetchRootAlbums()
  }, [])

  // Show loading state until all data is loaded
  if (loading || photoCountsLoading) {
    return (
      <div className="min-h-screen bg-gray-900 flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-500 mx-auto"></div>
          <p className="mt-4 text-gray-300">Loading gallery...</p>
        </div>
      </div>
    )
  }

  // Show error state
  if (error) {
    return (
      <div className="min-h-screen bg-gray-900 flex items-center justify-center">
        <div className="text-center">
          <div className="p-6 bg-red-900/20 border border-red-500/30 rounded-lg">
            <h2 className="text-xl font-semibold text-red-400 mb-2">Error Loading Gallery</h2>
            <p className="text-gray-300 mb-4">{error}</p>
            <button 
              onClick={() => window.location.reload()} 
              className="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg transition-colors"
            >
              Try Again
            </button>
          </div>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-gray-900">
      {/* Header */}
      <Header />
      
      {/* Hero Section */}
      {isComponentVisible('hero') && <Hero />}
      
      {/* Albums Section */}
      {rootAlbums.length > 0 && (
        <section className="py-20 bg-gradient-to-br from-gray-900 via-gray-800 to-black">
          <div className="max-w-6xl mx-auto px-6">
            <div className="text-center mb-16">
              <h2 className="text-3xl md:text-4xl font-bold text-white mb-4">
                <span className="bg-gradient-to-r from-blue-400 via-purple-400 to-pink-400 bg-clip-text text-transparent">
                  {t('albums.galleryTitle')}
                </span>
              </h2>
              <p className="text-lg text-gray-300 max-w-2xl mx-auto">
                {t('albums.gallerySubtitle')}
              </p>
            </div>

            {/* Featured albums grid with dark theme */}
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-8 mb-16">
              {rootAlbums.filter(album => album._id).slice(0, 8).map((album) => (
                <AlbumCard key={album._id} album={album} />
              ))}
            </div>

            {/* View all albums button with dark theme */}
            {rootAlbums.length > 8 && (
              <div className="text-center">
                <a
                  href="/albums"
                  className="inline-flex items-center px-6 py-3 bg-gradient-to-r from-blue-600 to-purple-600 text-white font-medium rounded-lg hover:from-blue-500 hover:to-purple-500 transition-all duration-300 shadow-lg hover:shadow-blue-500/25 transform hover:scale-105"
                >
                  View All Albums
                  <svg className="w-4 h-4 ml-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
                  </svg>
                </a>
              </div>
            )}
          </div>
        </section>
      )}

      {/* Statistics Section with dark theme */}
      {isComponentVisible('statistics') && (
        <section className="py-20 bg-gradient-to-r from-gray-900 to-black border-t border-gray-800">
          <div className="max-w-6xl mx-auto px-6">
            <div className="grid grid-cols-1 md:grid-cols-3 gap-8 text-center">
              <div className="group">
                <div className="text-3xl md:text-4xl font-bold text-white mb-2 group-hover:text-blue-400 transition-colors duration-300">
                  {rootAlbums.length}
                </div>
                <div className="text-gray-400">
                  Albums Created
                </div>
              </div>
              <div className="group">
                <div className="text-3xl md:text-4xl font-bold text-white mb-2 group-hover:text-purple-400 transition-colors duration-300">
                  {getTotalPhotosCount()}
                </div>
                <div className="text-gray-400">
                  Photos Shared
                </div>
              </div>
              <div className="group">
                <div className="text-3xl md:text-4xl font-bold text-white mb-2 group-hover:text-pink-400 transition-colors duration-300">
                  24/7
                </div>
                <div className="text-gray-400">
                  Always Available
                </div>
              </div>
            </div>
          </div>
        </section>
      )}

      {/* Promotion Section with dark theme */}
      {isComponentVisible('promotion') && (
        <section className="py-20 bg-gradient-to-br from-black via-gray-900 to-gray-800 border-t border-gray-800">
          <div className="max-w-4xl mx-auto px-6 text-center">
            <h2 className="text-3xl md:text-4xl font-bold text-white mb-6">
              <span className="bg-gradient-to-r from-blue-400 via-purple-400 to-pink-400 bg-clip-text text-transparent">
                Ready to Share Your Story?
              </span>
            </h2>
            <p className="text-lg text-gray-300 mb-8">
              Create stunning galleries, organize your memories, and share them with the world in style.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <a
                href="/albums"
                className="px-6 py-3 bg-gradient-to-r from-blue-600 to-purple-600 text-white font-medium rounded-lg hover:from-blue-500 hover:to-purple-500 transition-all duration-300 shadow-lg hover:shadow-blue-500/25 transform hover:scale-105"
              >
                Explore Gallery
              </a>
              <a
                href="/login"
                className="px-6 py-3 border border-gray-600 text-gray-300 font-medium rounded-lg hover:bg-gray-800 hover:text-white transition-all duration-300"
              >
                Get Started
              </a>
            </div>
          </div>
        </section>
      )}

      {/* Footer */}
      <Footer />
    </div>
  )
}

// frontend/src/lib/templates/modern/Home.svelte
<script lang="ts">
	import type { PageData } from '../../../routes/$types';
	import HomeHero from '$components/HomeHero.svelte';
	import { currentLanguage } from '$stores/language';
	import { MultiLangUtils } from '$utils/multiLang';
	import { onMount } from 'svelte';

	export let data: PageData;

	let coverImages: Record<string, string> = {};
	let coverImagesLoading: Record<string, boolean> = {};

	onMount(async () => {
		if (!data.rootAlbums || data.rootAlbums.length === 0) return;

		// Initialize loading state for all albums
		data.rootAlbums.forEach((album) => {
			coverImagesLoading[album._id] = true;
		});

		// Fetch cover images for all albums using batch API
		try {
			const response = await fetch('/api/albums/cover-images', {
				method: 'POST',
				headers: {
					'Content-Type': 'application/json',
				},
				body: JSON.stringify({
					albumIds: data.rootAlbums.map((a) => a._id),
				}),
			});

			if (response.ok) {
				const result = await response.json();
				console.log('Cover images API response:', result);
				if (result.success && result.data) {
					// result.data is a Record<string, string> mapping albumId -> coverImageUrl
					coverImages = result.data;
					console.log('Cover images set:', coverImages);
				} else {
					console.warn('Unexpected response structure:', result);
				}
			} else {
				console.error('Failed to fetch cover images, status:', response.status);
			}
		} catch (err) {
			console.error('Failed to fetch cover images:', err);
		} finally {
			// Mark all albums as no longer loading
			data.rootAlbums.forEach((album) => {
				coverImagesLoading[album._id] = false;
			});
		}
	});
</script>

<!-- Modern template home layout -->
<HomeHero />

<section class="bg-white">
	<div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-10">
		<div class="flex items-center justify-between mb-6">
			<div>
				<h2 class="text-2xl font-semibold text-gray-900">Featured Albums</h2>
				<p class="mt-1 text-sm text-gray-500">Root-level public albums from your gallery.</p>
			</div>
			<a href="/albums" class="text-sm font-medium text-primary-600 hover:text-primary-700">
				View all
			</a>
		</div>

		{#if data.albumsError}
			<div class="bg-red-50 text-red-700 px-4 py-3 rounded-md text-sm">
				Failed to load albums: {data.albumsError}
			</div>
		{:else if !data.rootAlbums || data.rootAlbums.length === 0}
			<div class="bg-gray-50 text-gray-600 px-4 py-3 rounded-md text-sm">
				No albums available yet.
			</div>
		{:else}
			<div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6">
				{#each data.rootAlbums as album}
					{@const coverImageUrl = coverImages[album._id]}
					{@const isLogo = coverImageUrl && (coverImageUrl.includes('/logos/') || coverImageUrl.includes('logo') || (coverImageUrl.includes('/api/storage/serve/') && coverImageUrl.includes('logo')))}
					<a
						href={`/albums/${album.alias ?? album._id}`}
						class="group rounded-lg border border-gray-200 overflow-hidden shadow-sm hover:shadow-md transition-shadow bg-white flex flex-col"
					>
						<div class="aspect-4/3 bg-gray-100 relative overflow-hidden">
							{#if coverImagesLoading[album._id]}
								<div class="absolute inset-0 flex items-center justify-center">
									<div class="w-8 h-8 border-2 border-gray-300 border-t-primary-600 rounded-full animate-spin"></div>
								</div>
							{:else if coverImageUrl}
								<img
									src={coverImageUrl}
									alt={MultiLangUtils.getTextValue(album.name, $currentLanguage) || 'Album cover'}
									class="w-full h-full transition-transform duration-300 group-hover:scale-110 {isLogo
										? 'object-contain p-4 bg-white'
										: 'object-cover'}"
								/>
							{:else}
								<div class="absolute inset-0 flex items-center justify-center text-gray-400">
									<svg class="w-12 h-12" fill="none" stroke="currentColor" viewBox="0 0 24 24">
										<path
											stroke-linecap="round"
											stroke-linejoin="round"
											stroke-width="1.5"
											d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z"
										/>
									</svg>
								</div>
							{/if}
						</div>
						<div class="p-4 flex-1 flex flex-col">
							<h3 class="text-base font-semibold text-gray-900 group-hover:text-primary-600 truncate">
								{#if album.name}
									{MultiLangUtils.getTextValue(album.name, $currentLanguage)}
								{:else}
									Untitled album
								{/if}
							</h3>
							{#if album.description}
								<p class="mt-1 text-xs text-gray-500 line-clamp-2">
									{MultiLangUtils.getTextValue(album.description, $currentLanguage)}
								</p>
							{/if}
						</div>
					</a>
				{/each}
			</div>
		{/if}
	</div>
</section>
